### ISSUE TITLE
ETH blockchain prices not working

### ISSUE THREAD

**Issue by HiimNaruto** [infotrex/bulk-upload-to-opensea#10]
Hello there, 
I tried this with ETH blockchain. When it comes to putting the price, the program stopped after filling 0.05 as price. it's not completing the listing.

**Comment by infotrex** [comment]
please try to use filename called upload2.py,
it will resolved the last step.

**Comment by HiimNaruto** [comment]
Thank you very much. I will try and let you know. !

**Comment by HiimNaruto** [comment]
Still same. meta mask open and its not sign in

**Comment by infotrex** [comment]
same issue withe another user,
but at the moment still cannot find any solution yet.
thx

**Comment by HiimNaruto** [comment]
Oh.. okay. I think the problem is with the ETH blockchain. its works fine with the polygon. I hope you will find a solution soon. Thank you so much for your time <3

**Comment by infotrex** [comment]
> Oh.. okay. I think the problem is with the ETH blockchain. its works fine with the polygon. I hope you will find a solution soon. Thank you so much for your time <3

download the latest file, i believe it can resolved the ETH blockchain. thx

**Comment by HiimNaruto** [comment]
Hey. thank you very much <3
