### ISSUE TITLE
While I solved the captcha, the program quit

### ISSUE THREAD

**Issue by truong161** [infotrex/bulk-upload-to-opensea#100]
I tried to read the code but don't know how to make the program wait for me to finish the captcha.
When I finished, the program exited.
Please help me add delay when "Almost Done" popup appears.
Many thanks!

**Comment by infotrex** [comment]
@truong161 
you can download the test file at this link, it will delay 25 second for manual solve the puzzle.
pls try and feedback. thx
https://github.com/infotrex/files/blob/main/upload18-25s.py

**Comment by truong161** [comment]
Thanks for your taking care of it!!!
I have tested about 300 items, meet captcha 30 times, but no command line is output (print("captcha found"))
I think the if statement is not working.
-----
I also discovered that:
1. Polygon blockchain checkbox not save then "Save this form"
2. Duration radio button not save then "Save this form"

**Comment by truong161** [comment]
I think this tool dimention is a too big, about 400x600 is nice.
Duration: change to listbox style will take less space

**Comment by truong161** [comment]
After a few hours of use (in 4 virtual machines) I have some feedback;
- Sometimes need to login metamask, the previous version can't see
- Regularly stop at the "You created..." popup
- Sometimes stop before entering property
- Many times (but not all) stops at “Your nft is listed” (after solving captcha)
Every time I run, I can upload from few to 10, some time > 20. The stops are all due to the above errors
