### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by ImHereThen** [infotrex/bulk-upload-to-opensea#101]
Hi for some reason after uploading a vast amount of nfts correctly, whenever i start upload18 it does not start the process of creating nfts it instead takes me to open sea's homepage.
Can i have some help please :)

**Comment by infotrex** [comment]
@ImHereThen 
Opensea collection link must end with "assets/create",
look like this : https://www.opensea.io/collection/yourcollectionsname/assets/create

**Comment by ImHereThen** [comment]
Hey thanks for the response unfortunately it does that is why it has baffled me i was in the process of uploading then it stopped once i tried to restart, it ended up only taking me to the homepage of opensea

**Comment by infotrex** [comment]
@ImHereThen 
maybe something wrong the input setting.
can send me screenshot?

**Comment by ImHereThen** [comment]
Of which part the settings for upload18.py?

**Comment by ImHereThen** [comment]
![screenshot](https://user-images.githubusercontent.com/100538719/155930918-0bcadd7b-57ef-409d-b9a9-10c4180655aa.PNG)

**Comment by truong161** [comment]
start number: 226
end number: 200
????
should it be "start" < "end"?

**Comment by ImHereThen** [comment]
Omg... i am so sorry for wasting your time this is completely my fault i did not even realize that.
so so sorry thx for the help anyay.
