### ISSUE TITLE
How would you like to open this file

### ISSUE THREAD

**Issue by Kugesz** [infotrex/bulk-upload-to-opensea#103]
So I start to run the upload.py and a popup came up that says How would you like to open this file. If I select the Chrome options I get this window (second picture).

Anyone could help me?
![image](https://user-images.githubusercontent.com/81580775/156071766-83689746-614d-45f6-b9c7-5119b814513b.png)
![image](https://user-images.githubusercontent.com/81580775/156071884-4edbd007-6a65-4ed8-bea2-cd31e38e6a51.png)

**Comment by truong161** [comment]
First, download visual studio code here: https://code.visualstudio.com/download
open vs code, select folder python, menu terminal> new terminal > type "python upload.py" here
https://www.youtube.com/watch?v=9o4gDQvVkLU

**Comment by Kugesz** [comment]
> First, download visual studio code here: https://code.visualstudio.com/download open vs code, select folder python, menu terminal> new terminal > type "python upload.py" here https://www.youtube.com/watch?v=9o4gDQvVkLU
Yes I opended with VS Studi and did what you said to do and still dosent work

**Comment by truong161** [comment]
Have you installed python yet?
I installed by typing "python" in the terminal of vs
Or install python in microsoft store

**Comment by Kugesz** [comment]
> Have you installed python yet? I installed by typing "python" in the terminal of vs Or install python in microsoft store

Yes I have python 3.10 install and  connected to the PATH. If the "connected" is the right word to say.
