### ISSUE TITLE
I am not a robot recaptcha

### ISSUE THREAD

**Issue by Kugesz** [infotrex/bulk-upload-to-opensea#105]
So after a long week of trying I finally can generate my NFTs and the upload script is working too. I have a little problem every 10th NFTs to upload I need to fill out a recaptcha. I installed that one that the creator suggested but it doesn't seem to be working for me.

Any idea how I can fix it?

**Comment by kaikecloss** [comment]
I found this code and they solve tha captcha problem, but I got another problem.. I'm stuck in the properties.
https://github.com/xeonsim/opensea-upload-with-recaptcha-solution/issues/4
I'm not a robot recaptcha too! LOL

**Comment by Kugesz** [comment]
> I found this code and they solve tha captcha problem, but I got another problem.. I'm stuck in the properties. [xeonsim/opensea-upload-with-recaptcha-solution#4](https://github.com/xeonsim/opensea-upload-with-recaptcha-solution/issues/4) I'm not a robot recaptcha too! LOL

Maybe ur json file is not right or got somthing messed up inside of it

**Comment by infotrex** [comment]
@Kugesz @Kugesz 
Give me your email address, i send you a beta version file to bypass captcha
but it not 100% perfect to solve the issue. :)
buy me a coffee, if that work for you.

TQ

**Comment by kaikecloss** [comment]
can you send to me too?

**Comment by SJFAFA** [comment]
NFTs to upload I need to fill out a recaptcha in evertime.
Can I get an email too?
woo1004312@gmail.com

**Comment by Juchuhsu** [comment]
@infotrex [infotrex](https://github.com/infotrex)
Hi , I also have recaptcha every single upload :(
Can you send me new version please? Thank you.
My email: anserini1994@gmail.com

**Comment by calvinvalerian** [comment]
Email me too:
calvinvalerian@gmail.com

**Comment by skyocean** [comment]
Hi thanks a lot. Could you please send it to me? I will test it and let you know. Thank you. My email: six.one.four@hotmail.com

**Comment by calvinvalerian** [comment]
Error
https://youtu.be/6MBrQnc-nmg

**Comment by calvinvalerian** [comment]
More errors https://youtu.be/oDn4So9ifAE

The the script incorrectly handles captcha and the program stop at Metamask Contract Sign.

**Comment by aaaiiee** [comment]
> 

Plz, Can you send me a new version, please? Thank you.
aaaiiee2@gmail.com

**Comment by infotrex** [comment]
> @infotrex [infotrex](https://github.com/infotrex) Hi , I also have recaptcha every single upload :( Can you send me new version please? Thank you. My email: [anserini1994@gmail.com](mailto:anserini1994@gmail.com)

sent

**Comment by infotrex** [comment]
> @infotrex [infotrex](https://github.com/infotrex)
> 
> Plz, Can you send me a new version, please? Thank you. [aaaiiee2@gmail.com](mailto:aaaiiee2@gmail.com)

sent

**Comment by weefk** [comment]
@infotrex me too bro hacker.hflag@gmail.com thx

**Comment by needstat** [comment]
@infotrex Hi , I also have recaptcha every single upload... Can you send me new version please? Thank you. My email: needstat@yandex.com

**Comment by mseymore13** [comment]
I have the recaptcha after every download and it's not signing metamask, could you send me the updated version so i can see if I can get it to work.

**Comment by Sats05** [comment]
@infotrex can I have an email too pls redcirclart@gmail.com

**Comment by sahu2225** [comment]
@infotrex Hi , I also have try 5 hrs download extension but not work help Plz, Can you send me a new version, please? Thank you saurabhsahu4111@gmail.com

**Comment by VladHefner** [comment]
@infotrex pls send me .... wascone1@gmail.com big thanks

**Comment by Jay2Co** [comment]
Hi, @infotrex 

I have recaptcha issue, can you send me a new version, please? Mine is 
jcmj5434@gmail.com 

Thanks!

**Comment by anonmous232** [comment]
Hi @infotrex.  Anychance I could get a copy of the update to bypass recaptcha?

anonmouse232@gmail.com 

Thanks in advance,

Cheers,

**Comment by nana2523** [comment]
Email me too:
dong04102@naver.com

**Comment by daikyunjung** [comment]
Can I get the code?
jungdee92@gmail.com
Thanks, Regards.

**Comment by pratikpranay1612** [comment]
Hi, @infotrex 
Plz, Can you send me a new version, please? Thank you. pratikpranay1612@gmail.com

**Comment by lenanaYH** [comment]
Hi @infotrex
Plz, could you please send me the new version?.. I want to upload 1,000 picture..! thank you.
yhkim6584@gmail.com

**Comment by ken39677** [comment]
Hi @infotrex
Plz, could you please send me the new version? thanks.
[ken39677@gmail.com](mailto:ken39677@gmail.com)

**Comment by hay997** [comment]
could you please send it me too? h.avagyan1993@gmail.com
Thanks

**Comment by Kugesz** [comment]
> @Kugesz @Kugesz Give me your email address, i send you a beta version file to bypass captcha but it not 100% perfect to solve the issue. :) buy me a coffee, if that work for you.
> 
> TQ

Sry for the late reply here is my email address kovacsgergo.algyo@gmail.com
Thanks for it in advance!

**Comment by Alegeliu** [comment]
Hi @infotrex  
Could you please send me the new version? Thank you! alegeliu6@gmail.com

**Comment by infotrex** [comment]
all sent

**Comment by weefk** [comment]
My email is empty

**Comment by weefk** [comment]
> all sent

I have not received

**Comment by infotrex** [comment]
> > all sent
> 
> I have not received

im resent, your email address too special :)

**Comment by weefk** [comment]
> all sent

Big thanks

**Comment by Kugesz** [comment]
> all sent

I have not recived yet

**Comment by pratikpranay1612** [comment]
I also didn't got it... Please send it again pratikpranay1612@gmail.com

**Comment by kraussian** [comment]
@infotrex Could you send me a copy too? My email is maxahn@duck.com

**Comment by kaikecloss** [comment]
send me pls kaikecloss@gmail.com

**Comment by Mousteezy** [comment]
Amazing work you guys did here! I am a programming noob and not familiar with the technology but even I could run the programm. Very nicely made. The tutorial helped a lot.

Since last week I have the same Captcha problem as everyone. Could you please sent me a copy of the new beta version? (ripperathell@web.de)? Greetings!

**Comment by BirdWord** [comment]
sup! let's try. pls email me too danncassnft@gmail.com

Thanks, Regards.

**Comment by bizi27** [comment]
can you send me program and rechapta bypass on mail

rokbizjak24@gmail.com please

**Comment by jeppert** [comment]
If not too much trouble, please send it to me too, thank you:
jenslyn42@gmail.com

**Comment by harrislop** [comment]
@infotrex pls send me .... harrislrr12@gmail.com big thanks

**Comment by lightdesigns** [comment]
> @Kugesz @Kugesz Give me your email address, i send you a beta version file to bypass captcha but it not 100% perfect to solve the issue. :) buy me a coffee, if that work for you.
> 
> TQ

edog.beatz31@gmail.com
send me file please

**Comment by infotrex** [comment]
I'm uploaded the to my repo - upload_captcha.py
Please install https://chrome.google.com/webstore/detail/buster-captcha-solver-for/mpbjkejclgfgadiemmefgebjfooflfhl?hl=en
and set your API key.

**Comment by realpablosantos** [comment]
> @Kugesz @Kugesz Dê-me seu endereço de e-mail, eu lhe envio um arquivo de versão beta para ignorar o captcha , mas não é 100% perfeito para resolver o problema. :) me compre um café, se isso funcionar para você.
> 
> QT

Pode enviar para o meu email por favor? Agradeço!!!

email: realpablosantos@protonmail.com

**Comment by infotrex** [comment]
@realpablosantos 
pls download the another file upload_captcha.py

**Comment by damith48** [comment]
> beta version

need to me.:eds4ksm@gmail.com

**Comment by infotrex** [comment]
@damith48 
Download the latest file upload_captcha.py

**Comment by lightdesigns** [comment]
> @damith48 Download the latest file upload_captcha.py

where to download it and where to instal it or just unzip it in folder ?

**Comment by damith48** [comment]
> @damith48 Download the latest file upload_captcha.py

thx hope work
