### ISSUE TITLE
Not adding Properties, then Program stops running

### ISSUE THREAD

**Issue by Jakeo420** [infotrex/bulk-upload-to-opensea#107]
After opening the "Add Properties" tab, my traits are not added and then it ends the program and the start button turns green again. Please help!!! Thank you for your time.
![Capture](https://user-images.githubusercontent.com/100708891/156860887-d3b46de6-c15a-4f08-bf6c-902b41c20ca9.PNG)
.

**Comment by infotrex** [comment]
@Jakeo420 
please confirm all your json put under "json" folder
thx

**Comment by Jakeo420** [comment]
yes they all are
![Capture1](https://user-images.githubusercontent.com/100708891/156887115-888873ed-4890-477b-8f33-09fe0b748a4c.PNG)
![Capture2](https://user-images.githubusercontent.com/100708891/156887120-431a5692-8c18-4230-9638-dd7e94986e5d.PNG)
.

**Comment by Jakeo420** [comment]
I just tried to rerun the program again, and it ran again until the same add properties window and then stopped, the terminal looks like this
![Capture4](https://user-images.githubusercontent.com/100708891/156887371-75219245-0959-4a3e-980f-e9991c6c85ff.PNG)
.

**Comment by kaikecloss** [comment]
I'm having the same issue. Anyone can help?

**Comment by infotrex** [comment]
can show me your json file?
do all the metadata files put into "json" folder?

**Comment by Jakeo420** [comment]
here is what my metadata files look like 
![Screenshot 2022-03-06 100210](https://user-images.githubusercontent.com/100708891/156928830-9ce76145-0f5c-4178-835d-b6a9b7fb35b9.png)

and I've made sure that they are all properly put under my "json file" which is under the "src" folder
![Screenshot 2](https://user-images.githubusercontent.com/100708891/156928983-72ae6043-b32d-4423-8338-ed9031c60276.png)
![Screenshot 3](https://user-images.githubusercontent.com/100708891/156928984-0df7f85e-26da-4411-b4df-704f06890820.png)
![Screenshot 4](https://user-images.githubusercontent.com/100708891/156928990-901b8948-d689-492f-a5ab-88dd2def82eb.png)

**Comment by Jakeo420** [comment]
???

**Comment by infotrex** [comment]
> ???
do you have twitter or discord can contact?

**Comment by Jakeo420** [comment]
@infotrex hey  sorry it took me so long to reply, a whole bunch shit came up I had to deal with, but yes, my discord is : Jake_2003
Hope to hear from you soon, and thank you for your help!
