### ISSUE TITLE
Recaptcha after every design

### ISSUE THREAD

**Issue by Mikromz747** [infotrex/bulk-upload-to-opensea#108]
Hello, is there any updated script to bypass this reCaptcha that appears after every upload? Right now I’m completing it manually after every design but I still have 9000 designs to go hahaha. Just asking in case there was a solution, will make sure to buy coffee ;)

**Comment by weefk** [comment]
same problem

**Comment by MedAhenna** [comment]
I found a software that solve captcha, It's work great for me
https://opencbot.com/

**Comment by nabeelsaleem** [comment]
It is a paid software

**Comment by damith48** [comment]
mee too plese fix this bro..
