### ISSUE TITLE
ReCaptcha problem suggestion

### ISSUE THREAD

**Issue by D3NIS4O** [infotrex/bulk-upload-to-opensea#109]
Hello I have a suggestion for the creator. So you got to download [This extension](https://chrome.google.com/webstore/detail/buster-captcha-solver-for/mpbjkejclgfgadiemmefgebjfooflfhl) and make the code click the I'm not a robot square and then click the extension icon in the captca.

**Comment by infotrex** [comment]
@D3NIS4O 
Yes, i have this script for using this extension with my script.
i can give you try, but sometimes the captcha will block our IP address or need manual solve the puzzle.
give me your email address.

**Comment by hongdohyun877** [comment]
@infotrex  can i get too sir? please 
Hongdohyun@gmail.com

**Comment by johnfarsi21** [comment]
@infotrex please I need it too? Can you send it to my email tarekfares2003@gmail.com

**Comment by D3NIS4O** [comment]
> @D3NIS4O Yes, i have this script for using this extension with my script. i can give you try, but sometimes the captcha will block our IP address or need manual solve the puzzle. give me your email address, i email you the file. thx

My email is denislav21.12@abv.bg

**Comment by k3nai** [comment]
@infotrex If you don't mind, could you send it to me too? Please, it would save my life. 
My email: gustavo.luiz.slv@gmail.com

**Comment by needstat** [comment]
@infotrex could you please send it me too? needstat@yandex.com

**Comment by Intangibil** [comment]
@infotrex I would also like to see the fix. Thank you. kwisatzhaderachdev@gmail.com

**Comment by awebosas** [comment]
@infotrex can you please send it me too? backstagelabs23@gmail.com

**Comment by logistic-people-deutschland** [comment]
@infotrex I would also like to see the fix. Thank you. blitz@vx0.de

**Comment by mindgap00** [comment]
@infotrex please I need it too! Could you please send it me? hyungseok.k@gmail.com

**Comment by elbarto140948** [comment]
@infotrex send it me too please makar140948@gmail.com

**Comment by asankaM96** [comment]
please send me to transformationvibes2558@gmail.com

**Comment by arinze01** [comment]
@infotrex i will be so glad if you send this to me email chrisomar042@gmail.com

**Comment by wingsolo1** [comment]
@infotrex  Its will help me alot if you send this to me email wingsolobot@gmail.com

**Comment by bizi27** [comment]
rokbizjak24@gmail.com 

please help me with chapta bypass!

**Comment by harrislop** [comment]
pls send me .... harrislrr12@gmail.com big thanks

**Comment by Lurpigi** [comment]
could you please send me the beta version as well? thank you
superSonickirby0@gmail.com

**Comment by asb1512** [comment]
If possible, could you send it to me as well?
asb1512@gmail.com

**Comment by hwangdesign** [comment]
please send me to hwangdesign@gmail.com

**Comment by infotrex** [comment]
I'm uploaded the to my repo - upload_captcha.py
Please install https://chrome.google.com/webstore/detail/buster-captcha-solver-for/mpbjkejclgfgadiemmefgebjfooflfhl?hl=en
and set your API key.

TQ
