### ISSUE TITLE
start after checking the complete listing, After listing one nft,  need to modify the number of nft and restart it

### ISSUE THREAD

**Issue by hongdohyun877** [infotrex/bulk-upload-to-opensea#110]
start after checking the complete listing,
After listing one nft,  need to modify the number of nft and restart it

Can I upload the nft automatically without pressing the restart button? 
If  don't check complete listing, the number will automatically rise and upload

**Comment by NewNeroC** [comment]
Same here.

**Comment by anonmous232** [comment]
I resolved this issue by increasing the sleep in line 441 to 15 seconds (instead of 10).

            wait_css_selector("button[type='submit']")
            listing = driver.find_element(By.CSS_SELECTOR, "button[type='submit']")
            driver.execute_script("arguments[0].click();", listing)
            time.sleep(15)
