### ISSUE TITLE
buster captcha solver error

### ISSUE THREAD

**Issue by weefk** [infotrex/bulk-upload-to-opensea#113]
When i submit the captcha i get an error and idk how to fix, i tried different methods. HELP
![Снимок экрана 2022-03-12 212135](https://user-images.githubusercontent.com/101012281/158024016-ba882ba0-ff88-4522-968a-773b6444ac1d.jpg)
![Снимок экрана 2022-03-12 212435](https://user-images.githubusercontent.com/101012281/158024136-c18e5cd9-aef2-4561-9567-ed5b53ff5594.jpg)

**Comment by infotrex** [comment]
This "try again later" i also don't know how to solve for it
