### ISSUE TITLE
''Add Item'' Error Pls Help me

### ISSUE THREAD

**Issue by CyberPixelCrpto** [infotrex/bulk-upload-to-opensea#116]
Hello
The "Add item" button does not work in Python either, I think there is an error in the code software I have to do it manually every time.
![Ekran görüntüsü 2022-03-15 224324](https://user-images.githubusercontent.com/99931416/158458674-face17a1-1454-4d22-b68e-7da04a40fb35.png)

**Comment by infotrex** [comment]
@CyberPixelCrpto 
do your opensea collection input link url end with "assets/create"?
