### ISSUE TITLE
Selling issue

### ISSUE THREAD

**Issue by D3NIS4O** [infotrex/bulk-upload-to-opensea#117]
Hello
I have an issue with the selling of the NFTs. The script doesn't autoclick sign on the sell page and I have to do it by myself. Is there a way to fix?

**Comment by Capi666** [comment]
Have you click the checkbox "Complete Listing" ?

**Comment by damith48** [comment]
me too come this error plese fix this

**Comment by infotrex** [comment]
@D3NIS4O
remember select check " polygon blockchain" if you using polygon
