### ISSUE TITLE
Seling Issue after 1st image

### ISSUE THREAD

**Issue by neohopebr** [infotrex/bulk-upload-to-opensea#122]
- already click complete listing
- already click polygon
so after complete first image, second image not go to selling page
so i have to close the bot , and rerun the second image, so 1 image 1 bot run

issue with bot not click " i'm human too " have to click manual - already install  I'm not robot captcha clicker extension
issue with bot can't not run voice challenge more than two times - already install Buster: Captcha Solver for Humans

- already use compatible chrome from chromedriver

hope you can solve the issue
thanks

**Comment by infotrex** [comment]
@neohopebr 
hi, do your put in your API key into buster Options there?

**Comment by Capi666** [comment]
Hi,

I have the same problem... exactly the same. I am using the file "upload_captcha.py" and I tried with the new version with the same problem.

I have the API key filled in "Wit.ai".
Any idea? 

Thanks and regards,

**Comment by sule9na** [comment]
Same here, the weird thing is that it did work once and it did 5 images in a row (but I had to manually click on the audio captcha every time). Now it seems to be showing me the nft created screen and never moving onto the next one. I'm still manually clicking the audio captcha icon every time but I'm fiddling with the script trying to fix that problem. I'm concerned that even if I do it just doesn't seem to move onto the next image any more and therefore I'll have to manually sit with it to start again for every image thousands of times.
