### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by aashilp** [infotrex/bulk-upload-to-opensea#123]
Start creating NFT aa #2
number  2
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\aashi\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__     
    return self.func(*args)
  File "C:\Users\aashi\Downloads\bulk-upload-to-opensea-main\bulk-upload-to-opensea-main\upload18.py", line 258, in main_program_loop
    wait_xpath('//*[@id="media"]')
  File "C:\Users\aashi\Downloads\bulk-upload-to-opensea-main\bulk-upload-to-opensea-main\upload18.py", line 244, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Users\aashi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)   
selenium.common.exceptions.TimeoutException: Message:     
Stacktrace:
Backtrace:
        Ordinal0 [0x00919943+2595139]
        Ordinal0 [0x008AC9F1+2148849]
        Ordinal0 [0x007A4528+1066280]
        Ordinal0 [0x007D0FD4+1249236]
        Ordinal0 [0x007D11CB+1249739]
        Ordinal0 [0x007FD812+1431570]
        Ordinal0 [0x007EBA34+1358388]
        Ordinal0 [0x007FBAF2+1424114]
        Ordinal0 [0x007EB806+1357830]
        Ordinal0 [0x007C6086+1204358]
        Ordinal0 [0x007C6F96+1208214]
        GetHandleVerifier [0x00ABB232+1658114]
        GetHandleVerifier [0x00B7312C+2411516]
        GetHandleVerifier [0x009AF261+560433]
        GetHandleVerifier [0x009AE366+556598]
        Ordinal0 [0x008B286B+2173035]
        Ordinal0 [0x008B75F8+2192888]
        Ordinal0 [0x008B76E5+2193125]
        Ordinal0 [0x008C11FC+2232828]
        BaseThreadInitThunk [0x768E6739+25]
        RtlGetFullPathName_UEx [0x77DB8E7F+1215]
        RtlGetFullPathName_UEx [0x77DB8E4D+1165]

**Comment by infotrex** [comment]
@aashilp 
do you select collect "src" folder?
that error show your nft image missing

**Comment by nftje** [comment]
It happend to me as well. I was able to fix by listening to the instruction carefully. So the solution was just type the correct OpenSea Collection link in the program. basically the complete link has to be: Opensea collection link: https://opensea.io/collection/kick-skull/assets/create. the missing last part of the link was creating the problem.
