### ISSUE TITLE
how to speed up a process?

### ISSUE THREAD

**Issue by Dantuzzu** [infotrex/bulk-upload-to-opensea#126]
On average I upload at a rate of 1 minute and 30 seconds. everything fast except selling, after solving the captcha the screen freezes for 40-50 seconds, is there a way to speed up this step?

**Comment by infotrex** [comment]
@Dantuzzu
i not sure, maybe your internet speed or other issue to slow down your upload.

**Comment by debiannet** [comment]
Have same issue, after create NFT freezes for 40-50 seconds then start create new one, im doing this without " complete listings ". My internet connection is very good and also laptop fast, is there any sleep time in the code before create new one ?
