### ISSUE TITLE
automated query error in captcha

### ISSUE THREAD

**Issue by junichiro-watanabe** [infotrex/bulk-upload-to-opensea#127]
When captcha, the following error occurs

```
Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page.
```

How can I resolve this?

**Comment by infotrex** [comment]
@junichiro-watanabe 
Sometimes i also have this issue.
i will manual solve my captcha puzzle few time and waiting google captcha release my IP address
or i restart my modem.

TQ

**Comment by junichiro-watanabe** [comment]
@infotrex 
Thank you for your answer. I got it.
