### ISSUE TITLE
'#' not filling in title

### ISSUE THREAD

**Issue by LinTh13** [infotrex/bulk-upload-to-opensea#129]
When i run the upload_captcha.py file i see the # in the console which is made by this:

print("Start creating NFT " +  loop_title + str(start_numformat)) #275 line

But on opensea its skipped.
If i try to concatenate it in the line 287 like this:

name.send_keys(loop_title + "-#-" + str(start_numformat))
it still doesnt show the # on opensea (but i see the '--' tho)

The name(title) has a # mark in the json and in the program also (thats why the print shows it in console)

Any idea why its happening? I'm not on EN keyboard layout but that shouldn't make much difference cause its the same AltGr + X for me also.

**Comment by Revmagi** [comment]
Hello,  We are currently using the upload18 or upload_captcha.py    I hope this helps you.

**Comment by LinTh13** [comment]
> Hello, We are currently using the upload18 or upload_captcha.py I hope this helps you.

Huh? You mean for you it both python file work? Can you tell me more about your configuration cause i don't think its code related.

**Comment by infotrex** [comment]
@LinTh13 
Are you using mac or windows run this script?
at the moment don't have any user feedback about this issue.

**Comment by LinTh13** [comment]
@infotrex 
Windows 10 Pro

**Comment by infotrex** [comment]
@LinTh13
This issue i still cannot figure how to solve it.
can you try manually upload 1 NFt to opensea, see any problem.

**Comment by LinTh13** [comment]
@infotrex 
There is nothing wrong when i do it manually (if I tpye a '#' it appears in the title), the problem of course is I'm not gonna do it manually with this item count :D

**Comment by LinTh13** [comment]
The problem is still present, but already started the uploading without the # so it doesn't matter now
