### ISSUE TITLE
Is it possible to remove the batch size limit?

### ISSUE THREAD

**Issue by kevindeepitm** [infotrex/bulk-upload-to-opensea#13]
Currently it only allows uploading up to 1000 NFTs.
If there is good reason for such a cap, may I suggest to allow leading 0's (001, 002, ... 999)?
That way, the users can just add a '1' to the title for items from 1001 - 1999, and so on.

**Comment by infotrex** [comment]
current version allow to upload 9999 NFTs.
good idea for you suggestion, maybe put into next enhancement version.
TQ

**Comment by kevindeepitm** [comment]
> current version allow to upload 9999 NFTs. good idea for you suggestion, maybe put into next enhancement version. TQ

Hi, I pulled the latest version and the upper bound is 999 (not 9999).
Please see the screenshot: https://i.imgur.com/99iOCma.png
Thanks

**Comment by infotrex** [comment]
> > current version allow to upload 9999 NFTs. good idea for you suggestion, maybe put into next enhancement version. TQ
> 
> Hi, I pulled the latest version and the upper bound is 999 (not 9999). Please see the screenshot: https://i.imgur.com/99iOCma.png Thanks

which file you are using?

**Comment by kevindeepitm** [comment]
> > > current version allow to upload 9999 NFTs. good idea for you suggestion, maybe put into next enhancement version. TQ
> > 
> > 
> > Hi, I pulled the latest version and the upper bound is 999 (not 9999). Please see the screenshot: https://i.imgur.com/99iOCma.png Thanks
> 
> which file you are using?

upload.py and upload-sign.py

**Comment by infotrex** [comment]
> > > > current version allow to upload 9999 NFTs. good idea for you suggestion, maybe put into next enhancement version. TQ
> > > 
> > > 
> > > Hi, I pulled the latest version and the upper bound is 999 (not 9999). Please see the screenshot: https://i.imgur.com/99iOCma.png Thanks
> > 
> > 
> > which file you are using?
> 
> upload.py and upload-sign.py

download the latest file upload-sign.py, i just upload.

**Comment by kevindeepitm** [comment]
> 

It works now. Thank you.
