### ISSUE TITLE
The program does not want to pick 6 months

### ISSUE THREAD

**Issue by calvinvalerian** [infotrex/bulk-upload-to-opensea#130]
https://youtu.be/Uztystu6Vlk

**Comment by infotrex** [comment]
@calvinvalerian 
please download the latest upload_captcha.py thx.

**Comment by calvinvalerian** [comment]
the latest upload_captcha.py cannot solve captcha

send me upload-captcha-buster.py

instead

**Comment by calvinvalerian** [comment]
sorry I accidentally ran upload18.py

the upload-captcha-buster.py is working perfectly you are awesome man

**Comment by infotrex** [comment]
@calvinvalerian 
Pls download  upload_captcha.py this file
