### ISSUE TITLE
Buster Extention Error

### ISSUE THREAD

**Issue by damith48** [infotrex/bulk-upload-to-opensea#137]
![Capture](https://user-images.githubusercontent.com/3250801/160349330-27070907-3c89-46a6-8f40-87170dd829ed.PNG)

my uploading start 2-3 NFT File uploading after buster Extention cruising how to fix this please give advice

**Comment by Revmagi** [comment]
This is not an issue with the script, this is an issue with Buster as the banner states and does happen from time to time. Buster can not solve this audio or some times there is more than one way to answer. with this, it will stop unless you manually click the refresh and the Buster Icon again.
