### ISSUE TITLE
Recaptcha is closed by script action before completion

### ISSUE THREAD

**Issue by sule9na** [infotrex/bulk-upload-to-opensea#138]
I've been tracing this issue for a while and I think I know the exact place it's happening now.

On line 393 in the script the captcha box is located and the I'm not a Robot checkbox within it is clicked to start the process.
After this selenium must walk back up the Dom so it can then find the next iframe to click the solver/audio buttons.

At this point
`driver.switch_to.default_content()`
Is used to make selenium back out of the current iframe. However, this seems to simulate a click on the left side of the browser window, thus clicking outside of the captcha modal and closing it. At this point the script can't find anything it's looking for and bails out.

I've tried fixing this by uncommenting the optional iframe(-1) option, which doesn't work and I also tried
`driver.switch_to.parent_frame()`
but it causes the same click on the left side of the browser window.

**Comment by TW88SEO** [comment]
I have the same issue, can you tell me detail to solve this problem?

**Comment by sule9na** [comment]
Finally figured the issue out by printing every step one-by-one to powershell as it ran and realised the issue was occurring inside buster itself and not in this script.
You have to disable "Simulate User Interactions" in the buster options otherwise Buster will (for some crazy reason) click outside the captcha box and screw itself over. Once you disable that the interactions are less natural but it doesn't step on it's own toes any more.
