### ISSUE TITLE
Nothing happened. 

### ISSUE THREAD

**Issue by jin8864** [infotrex/bulk-upload-to-opensea#139]
I've followed the instruction and clicked the Start button, but nothing happened. It was frozen for a while and came back without any error message. No items were uploaded on Opensea. 
It's definitely the latest version with the two CAPTCHA extensions. 
Has anyone had the same issue and got a solution?

**Comment by PsyCongroe** [comment]
yeah i do have the same problem, apparently i havent found any solution to it.

**Comment by infotrex** [comment]
@jin8864 
do you press "open chrome browser" before "start" button?

**Comment by SJFAFA** [comment]
@jin8864 
Chrome driver version difference.
https://chromedriver.chromium.org/downloads
Go to the link above to get your browser version or install the latest version.
Overwrite the chrome driver in the existing folder with the new file.
And try again.
Good luck.

**Comment by jin8864** [comment]
I solved the issue. As a portable apps fan for many years, I'm also using Chrome portable and was trying to use it. 
Since I used the install version, it works. 
However, Opensea blocked the bulk upload recently. Thus, it's pontless.
