### ISSUE TITLE
Can u add the duration time ? Very important !!!!

### ISSUE THREAD

**Issue by ChrisBomBom** [infotrex/bulk-upload-to-opensea#14]

**Comment by infotrex** [comment]
Do u mean select 1 day, 3 days & 7 days? this 3 duration?
this is a quite complex for doing that.

**Comment by ChrisBomBom** [comment]
Why? Its going to be amazing.  Try it!!!!

**Comment by infotrex** [comment]
> Why? Its going to be amazing. Try it!!!!

will consider, but not at the moment :)
