### ISSUE TITLE
ERROR: Can not upload NFT image

### ISSUE THREAD

**Issue by YingyiDai** [infotrex/bulk-upload-to-opensea#143]
<img width="516" alt="Screen 2022-03-31 120229" src="https://user-images.githubusercontent.com/2421018/160974548-70e9d460-8412-4158-a438-f20cfc2f8315.png">
The NFT could not be created successfully because the uploaded image crashed. Other things seem to be fine, the name, description, and captcha can be automatically filled in.

**Comment by infotrex** [comment]
@YingyiDai 
Please select your correct "src" folder
inside "src" folder should have "images" & "json" this 2 folders.
Tq
