### ISSUE TITLE
Not recognising image src folder?

### ISSUE THREAD

**Issue by SQwilliams1976** [infotrex/bulk-upload-to-opensea#15]
Hi, great code, current issue is that when running the programme, it doesn't recognised the image src folder?  Also when trying to save the form warning sign pops up saying description required even thought I have added this?  I look forward to hearing from you soon.

KR
Susie

**Comment by infotrex** [comment]
please select "src" folder
and description must put in some content.

**Comment by villiumptch** [comment]
Now working like a dream since updates THANK YOU!
