### ISSUE TITLE
Properties not being propagated in Upload Captcha 2

### ISSUE THREAD

**Issue by Revmagi** [infotrex/bulk-upload-to-opensea#150]
Hello, 

         I noticed after uploading 160 NFTs that they were not being configured with the Properties. I checked all the settings and went back to the previous and it is definitely this script not processing the properties from the json file. Everything else is getting picked up ok.

**Comment by Juchuhsu** [comment]
Yes. The new update file has some indentation problems, but still it cannot configure with the Properties

**Comment by infotrex** [comment]
Im also using the latest script upload my nft, don't have any issue.
can you should me your json file structure? thx

**Comment by Juchuhsu** [comment]
> Im also using the latest script upload my nft, don't have any issue. can you should me your json file structure? thx

My json is very simple in below, thanks!
The speed seems a little bit slow to fill image, title and description(which not provided by json) than before using, and it directly sent to create. No error msg occurred. 

`{
  "name": "ABCDEFG #2",
  "description": "ABCDEFG",
  "attributes": [
    {
      "trait_type": "BirthDay",
      "value": "2-Jan"
    },
    {
      "trait_type": "Background",
      "value": "Essential"
    },
    {
      "trait_type": "Hair Color",
      "value": "Purple"
    },
    {
      "trait_type": "Skin Tone",
      "value": "White"
    },
    {
      "trait_type": "Expression",
      "value": "Loving"
    },
    {
      "trait_type": "Hat",
      "value": "None"
    },
    {
      "trait_type": "Accessories",
      "value": "Skull"
    }
  ],
  "compiler": "ABCDEFG"
}`

**Comment by Revmagi** [comment]
If I go back to any of the previous scripts, they all work fine, but for some reason the new ones are not picking up the properties. And yes, it is much slower. I will not complain about the speed at all because it does slow it down and with the new 2captcha it was working for 160 NFTs before I realized the properties were missing. 

 "properties": [
    {
      "type": "Background",
      "name": "Pea"
    },
    {
      "type": "Hats",
      "name": "Large Hat Purple"
    },
    {
      "type": "Skin",
      "name": "Light"
    },
    {
      "type": "Faces",
      "name": "Style B Pinky"
    },
    {
      "type": "Mouths",
      "name": "Style C Plum"
    },
    {
      "type": "Nose",
      "name": "Style D Yellow"
    },
    {
      "type": "Eyes",
      "name": "Style A Green"
    },
    {
      "type": "Hair",
      "name": "Short L Part Red"
    },
    {
      "type": "Accessories",
      "name": "Corona C"
    }
  ],

**Comment by infotrex** [comment]
@Revmagi 
yes..line 303 issue
I forgot to remove the .json1 extension. :(
sorry
