### ISSUE TITLE
2captcha -  code error line 38 import requests

### ISSUE THREAD

**Issue by villiumptch** [infotrex/bulk-upload-to-opensea#152]
Hi, 2captcha - line 38 import requests, I have error message stating “Import “requests” could not be resolved from source” how can I fix this please?

**Comment by Revmagi** [comment]
You need to install requests via pip so it can be used by python.

**Comment by Many2050** [comment]
File "c:\Users\Master\Downloads\bulk-upload-to-opensea-main (1)\bulk-upload-to-opensea-main\upload_2captcha.py", line 38, in <module>

    import requests

ModuleNotFoundError: No module named 'requests'

PS C:\Users\Master\Downloads\bulk-upload-to-opensea-main (1)>

**Comment by Revmagi** [comment]
Hello,

   You need to install this via pip.


Regards

**Comment by infotrex** [comment]
i removed the "import request"
please re-download the "upload_2captcha.py" file.

**Comment by Many2050** [comment]
thanks, the captchas are already working fine, it stopped 3 times but I keep checking how it goes, thanks master

**Comment by babeape** [comment]
please provide 2captcha verification step by step process.
my opensea account do not work 2 captcha automatically.

**Comment by Revmagi** [comment]
The instructions are in the readme. You install the Chrome extension, You register and fund your account, put the API into the chrome extension and turn it on. Selecting the recaptcha v2 in the list of the extensions settings. Then you start the upload. It works great. It is not something you  configured with OpenSea.io directly.
