### ISSUE TITLE
Change prices bulky on Minted NFTs

### ISSUE THREAD

**Issue by maduranga001** [infotrex/bulk-upload-to-opensea#155]
Hi

I have minted 9999 items using your program. I want to change the price again on all to one price. How can I do this? Do I have to do it manually or are there any other ways to do this? If we do it manually, it will take a very long time.

Please, can you advise how to do this? If any of you know this, please, reply.

Thank you!

**Comment by karakule3dfx** [comment]
You can try the latest version. a few changes may be required.
