### ISSUE TITLE
sometimes can't catch the solved text 

### ISSUE THREAD

**Issue by karakule3dfx** [infotrex/bulk-upload-to-opensea#157]
sometimes it can't catch the solved text and even though the text has passed and the created text is output, it waits for WebDriverWait(driver, 300).until(ExpectedConditions.presence_of_element_located((By.XPATH, "//*[@data-state='solved']"))) and it gives an error because it can't find it at the end. How can i solve this. and soo sorry for my english is realy bad. i am using google translate.

And 2captcha.com addon sometimes gives error too. "If error happens, repeat Delay" option. how should i set it up

**Comment by mitirapa** [comment]
Hi, for me, i changed in the 2captcha extension "if error 10 times" and "delay 10"
and in the script WebDriverWait(driver, 300) to WebDriverWait(driver, 1400)

**Comment by karakule3dfx** [comment]
thanks mitirapa i set "2captcha extension" like you said now but The "solved" text is running too fast, so wait.until cannot catch the xpath. After the solved text is gone, wait.until continues to wait "solved" xpath and gives an error because it could not find it at the end of the time.

**Comment by karakule3dfx** [comment]
#Is it okay if we change the code like this?
`#WebDriverWait(driver, 300).until(ExpectedConditions.presence_of_element_located((By.XPATH, "//*[@data-state='solved']")))
                #print("solved")
            
            else:
                pass
        else:
            print("no captcha")
            
        try:
            delay()                                 #old value 60
            cross = WebDriverWait(driver, 360).until(ExpectedConditions.presence_of_element_located((By.XPATH, '/html/body/div[6]/div/div/div/div[2]/button/i')))
            cross.click()
            time.sleep(sleeptime)
        except:
            delay()                                # old value 60
            cross = WebDriverWait(driver, 360).until(ExpectedConditions.presence_of_element_located((By.XPATH, '/html/body/div[5]/div/div/div/div[2]/button/i')))
            driver.execute_script("arguments[0].click();", cross)
            time.sleep(sleeptime)`

**Comment by Capi666** [comment]
Hi,

But the 2captcha extension is a new addon (2captcha solver) and **t is not free**, right?

Regards,

**Comment by mitirapa** [comment]
correct, it's not free, but cheap maybe $2 per 1000

**Comment by infotrex** [comment]
> #Is it okay if we change the code like this? `#WebDriverWait(driver, 300).until(ExpectedConditions.presence_of_element_located((By.XPATH, "//*[@data-state='solved']"))) #print("solved") else: pass else: print("no captcha")
> 
> ```
>     try:
>         delay()                                 #old value 60
>         cross = WebDriverWait(driver, 360).until(ExpectedConditions.presence_of_element_located((By.XPATH, '/html/body/div[6]/div/div/div/div[2]/button/i')))
>         cross.click()
>         time.sleep(sleeptime)
>     except:
>         delay()                                # old value 60
>         cross = WebDriverWait(driver, 360).until(ExpectedConditions.presence_of_element_located((By.XPATH, '/html/body/div[5]/div/div/div/div[2]/button/i')))
>         driver.execute_script("arguments[0].click();", cross)
>         time.sleep(sleeptime)`
> ```

yes..ok.
