### ISSUE TITLE
Oops, something went wrong (Opensea crash)

### ISSUE THREAD

**Issue by mitirapa** [infotrex/bulk-upload-to-opensea#159]
Hi,
Sometimes opensea can crash and stop the script with a page

_Oops, something went wrong
Yikes, looks like something went wrong on our end. If the issue persists, please shoot us a note so we can help out._

in the while loop, can we add a simple function :
after submit page, if "Oops" in text, so wait 2 seconds and repeat the loop with the same or next number depending on the case)
and maybe after complete listing too (but with continue the loop for the next number)

I tried without success (in 3 days, only 600/9999 uploads because opensea crashes)

-And thank you for the script :-)

**Comment by xeddyx** [comment]
yeah i have same crash with u bro 
now opensea is blocking the automatic program, and I think that's the result
I don't think there's a new version of it at the moment :(
will be a new update to fix it after few weeks

also are you using it with 2captcha?

+the last time  signed with metamask,
the length of the Wyvern Exchange Contract is getting longer, so I can't press the signature automatically

don't you have a problem with this part?

**Comment by Capi666** [comment]
Hi,

I have the same problem... have you solved it?

Thanks and regards,

**Comment by pyorolong** [comment]
i have same problem

**Comment by cristiane13091991** [comment]
Hi,

I have the same problem... have you solved it?

Thanks and regards,

**Comment by mitirapa** [comment]
for me it's maybe the same problem as https://github.com/infotrex/bulk-upload-to-opensea/issues/157
the script click but the page is not completely loaded for opensea and crash

another script is https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale
but maybe compare the code for fix the infotrex version ?

**Comment by cristiane13091991** [comment]
@mitirapa 

> for me it's maybe the same problem as #157 the script click but the page is not completely loaded for opensea and crash
> 
> another script is https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale but maybe compare the code for fix the infotrex version ?

where is the video to see how this program is executed?

**Comment by karakule3dfx** [comment]
i have a chrome extension for this problem but i dont know how can i share . my english is really bad

manifest.json
`{
   "background": {
    "service_worker": "eventPage.js"
   },
   "content_scripts": [ {
      "all_frames": true,
      "css": [ "content.css" ],
      "js": [ "jquery-3.5.0.min.js", "content.js" ],
      "matches": [ "https://*.opensea.io/*"],
      "run_at": "document_idle"
   } ],
   "description": "Opensea: fixes the Oops, something went wrong ",
   "icons": {
      "128": "onay-128.png",
      "16": "onay-16.png",
      "48": "onay-48.png"
   },
   "manifest_version": 3,
   "name": "Opensea ops sory kontrol",
   "permissions": [ "tabs", "storage", "notifications", "contextMenus", "webNavigation","scripting" ],
   "host_permissions": [
		"https://testnets.opensea.io/*" ,
		"https://*.opensea.io/*"
	],
   "version": "1.0"
}
`
eventPage.js
`
chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
	
   if (  tab.active==true && tab.url.indexOf("opensea") != -1 && tab.url.indexOf("create") == -1 )
   {	
		chrome.tabs.sendMessage(tabId, {page_updated: true, chinfo:changeInfo.status, tb:tab.status, chUrl:changeInfo.url, tbUrl:tab.url, tabim:tab});
   }
}); `

content.js
`var girdi = false;
// Başlangıç
chrome.runtime.onMessage.addListener(
  function(request, sender) {
	if(request.page_updated === true && request.tbUrl != null)
	{
		if(girdi == false)
		{  	
			girdi= true;
			let timerId = setInterval(() => testim(), 5000);
			function testim()
			 {
				const targetNode = getElementByXpath('//h1[text()="Oops, something went wrong"]');
				if(targetNode != null){
					clearInterval(timerId); clearTimeout(myTimeout); girdi= false; 
					
					setTimeout(() => {window.history.back();}, 2000);
				}
			 }
			const myTimeout = setTimeout(() => { clearInterval(timerId); girdi= false;}, 120000);
		}
	}
  }
);
// Başlangıç 
function getElementByXpath(path) {
  return document.evaluate(path, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
}
//
`

**Comment by xeddyx** [comment]
> 이 문제에 대한 크롬 확장 프로그램이 있지만 어떻게 공유할 수 있는지 모르겠습니다. 내 영어는 정말 나쁘다
> 
> 코딩에 대해 아는 것이 거의 없습니다. 틀리거나 누락되었거나 추가 사항이 있으면 수정할 수 있습니다. 그것은 나를 위해 작동합니다. 오류 메시지가 표시되면 자동으로 돌아가므로 프로그램은 문제 없이 중단된 부분부터 계속할 수 있습니다. 그리고 감사합니다 구글 번역 :)
> 
> ```
> manifest.json
> {
>    "background": {
>     "service_worker": "eventPage.js"
>    },
>    "content_scripts": [ {
>       "all_frames": true,
>       "css": [ "content.css" ],
>       "js": [ "jquery-3.5.0.min.js", "content.js" ],
>       "matches": [ "https://*.opensea.io/*"],
>       "run_at": "document_idle"
>    } ],
>    "description": "Opensea: fixes the Oops, something went wrong ",
>    "icons": {
>       "128": "onay-128.png",
>       "16": "onay-16.png",
>       "48": "onay-48.png"
>    },
>    "manifest_version": 3,
>    "name": "Opensea ops sory kontrol",
>    "permissions": [ "tabs", "storage", "notifications", "contextMenus", "webNavigation","scripting" ],
>    "host_permissions": [
> 		"https://testnets.opensea.io/*" ,
> 		"https://*.opensea.io/*"
> 	],
>    "version": "1.0"
> }
> 
> eventPage.js
> 
> chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
> 	
>    if (  tab.active==true && tab.url.indexOf("opensea") != -1 && tab.url.indexOf("create") == -1 )
>    {	
> 		chrome.tabs.sendMessage(tabId, {page_updated: true, chinfo:changeInfo.status, tb:tab.status, chUrl:changeInfo.url, tbUrl:tab.url, tabim:tab});
>    }
> }); 
> 
> content.js
> var girdi = false;
> // Başlangıç
> chrome.runtime.onMessage.addListener(
>   function(request, sender) {
> 	if(request.page_updated === true && request.tbUrl != null)
> 	{
> 		if(girdi == false)
> 		{  	
> 			girdi= true;
> 			let timerId = setInterval(() => testim(), 5000);
> 			function testim()
> 			 {
> 				const targetNode = getElementByXpath('//h1[text()="Oops, something went wrong"]');
> 				if(targetNode != null){
> 					clearInterval(timerId); clearTimeout(myTimeout); girdi= false; 
> 					
> 					setTimeout(() => {window.history.back();}, 2000);
> 				}
> 			 }
> 			const myTimeout = setTimeout(() => { clearInterval(timerId); girdi= false;}, 120000);
> 		}
> 	}
>   }
> );
> // Başlangıç 
> function getElementByXpath(path) {
>   return document.evaluate(path, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
> }
> //
> ```

thank you for your good advice !
but could you tell me more details ?
do I have to change this sauce  in upload_2captcha.py??

**Comment by Capi666** [comment]
> i have a chrome extension for this problem but i dont know how can i share . my english is really bad
> 
> I know very little about coding. If there is a wrong, missing or extra, you can edit it. it works for me. When it sees the error message, it automatically goes back, so the program can continue from where it left off without any problems. and thanks google translate :)
> 
> ```
> manifest.json
> {
>    "background": {
>     "service_worker": "eventPage.js"
>    },
>    "content_scripts": [ {
>       "all_frames": true,
>       "css": [ "content.css" ],
>       "js": [ "jquery-3.5.0.min.js", "content.js" ],
>       "matches": [ "https://*.opensea.io/*"],
>       "run_at": "document_idle"
>    } ],
>    "description": "Opensea: fixes the Oops, something went wrong ",
>    "icons": {
>       "128": "onay-128.png",
>       "16": "onay-16.png",
>       "48": "onay-48.png"
>    },
>    "manifest_version": 3,
>    "name": "Opensea ops sory kontrol",
>    "permissions": [ "tabs", "storage", "notifications", "contextMenus", "webNavigation","scripting" ],
>    "host_permissions": [
> 		"https://testnets.opensea.io/*" ,
> 		"https://*.opensea.io/*"
> 	],
>    "version": "1.0"
> }
> 
> eventPage.js
> 
> chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
> 	
>    if (  tab.active==true && tab.url.indexOf("opensea") != -1 && tab.url.indexOf("create") == -1 )
>    {	
> 		chrome.tabs.sendMessage(tabId, {page_updated: true, chinfo:changeInfo.status, tb:tab.status, chUrl:changeInfo.url, tbUrl:tab.url, tabim:tab});
>    }
> }); 
> 
> content.js
> var girdi = false;
> // Başlangıç
> chrome.runtime.onMessage.addListener(
>   function(request, sender) {
> 	if(request.page_updated === true && request.tbUrl != null)
> 	{
> 		if(girdi == false)
> 		{  	
> 			girdi= true;
> 			let timerId = setInterval(() => testim(), 5000);
> 			function testim()
> 			 {
> 				const targetNode = getElementByXpath('//h1[text()="Oops, something went wrong"]');
> 				if(targetNode != null){
> 					clearInterval(timerId); clearTimeout(myTimeout); girdi= false; 
> 					
> 					setTimeout(() => {window.history.back();}, 2000);
> 				}
> 			 }
> 			const myTimeout = setTimeout(() => { clearInterval(timerId); girdi= false;}, 120000);
> 		}
> 	}
>   }
> );
> // Başlangıç 
> function getElementByXpath(path) {
>   return document.evaluate(path, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
> }
> //
> ```

Same doubt... where I have to put that code?

Thanks and regards,

**Comment by karakule3dfx** [comment]
you need to create 3 file. manifest.json -- eventPage.js -- content.js and you need to put the codes in these files. then you need to put these 3 files in a folder and switch the chrome extension page in developer mode and select this folder as the unpacked item.

i thing this links help you
https://www.freecodecamp.org/news/building-chrome-extension/

https://www.youtube.com/watch?v=uV4L-wcnK3Y

**Comment by infotrex** [comment]
> karakule3dfx

Thank you @karakule3dfx

**Comment by Many2050** [comment]
thanks i tried it but still the same error keeps happening to me the script stops it is difficult to upload the 10k if it stops so much

**Comment by karakule3dfx** [comment]
for TimeoutException error

```
try:
            delay()              #new value 360
            cross = WebDriverWait(driver, 60).until(ExpectedConditions.presence_of_element_located((By.XPATH, '/html/body/div[6]/div/div/div/div[2]/button/i')))
            cross.click()
            time.sleep(sleeptime)
        except:
            delay()              #new value 360
            cross = WebDriverWait(driver, 60).until(ExpectedConditions.presence_of_element_located((By.XPATH, '/html/body/div[5]/div/div/div/div[2]/button/i')))
            driver.execute_script("arguments[0].click();", cross)
            time.sleep(sleeptime)
```

change the duration from 60 to 360 in these lines of code

```
try:
            delay()              #old value 60
            cross = WebDriverWait(driver, 360).until(ExpectedConditions.presence_of_element_located((By.XPATH, '/html/body/div[6]/div/div/div/div[2]/button/i')))
            cross.click()
            time.sleep(sleeptime)
        except:
            delay()              #old value 60
            cross = WebDriverWait(driver, 360).until(ExpectedConditions.presence_of_element_located((By.XPATH, '/html/body/div[5]/div/div/div/div[2]/button/i')))
            driver.execute_script("arguments[0].click();", cross)
            time.sleep(sleeptime)
```

**Comment by infotrex** [comment]
@karakule3dfx 
Thank you karaku3dfx, i updated the wait "360" into the script.

**Comment by Emiraliucar** [comment]
@karakule3dfx thank you bro your code works perfect

**Comment by thevileo** [comment]
This still seems to be occuring for me with the 360 value.
