### ISSUE TITLE
It won't add new lines for properties

### ISSUE THREAD

**Issue by kevindeepitm** [infotrex/bulk-upload-to-opensea#16]
This is very weird that I've uploaded 100+ NFTs today with no problem. But suddenly it stopped populating the properties properly.
Screenshot: https://imgur.com/2T8vTxK
I have multiple property fields: background, skin, hat, eye, ......
But as you can see, no new lines were added and the new property keys and values are just being appended to the previous ones.
This shouldn't be problems with my JSON file as:
1. I can see that it's appending new properties one at a time to the same text box
2. I tried the ones uploaded successfully but they are having the same issue this time

I tried upload.py, upload-sign.py and upload-only.py. Same problem

**Comment by infotrex** [comment]
try download the latest file, upload.py
this issue i believe is internet connection slow...

**Comment by kevindeepitm** [comment]
I pulled the latest version, which worked in the morning fine until the same problem happened again in the afternoon...
My fix: delete everything in the chrome_profile folder, then re-copy them from the Chrome folder.

**Comment by infotrex** [comment]
pls video my latest video, more clear instruction without copy chrome profile
https://www.youtube.com/watch?v=j0WguSodGf8&t=37s
