### ISSUE TITLE
exception in tkinter callback error

### ISSUE THREAD

**Issue by patrickhiro** [infotrex/bulk-upload-to-opensea#161]
Everytime I use bulk upload this kind  of error message appears
How to solve?? 

C:\Users\Patrick\Desktop\bulk-upload-to-opensea-main\upload_captcha.py:415: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  capt_btn = driver.find_element_by_xpath("//button[@id='solver-button']")
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Patrick\Desktop\bulk-upload-to-opensea-main\upload_captcha.py", line 409, in main_program_loop
    wait_xpath('/html/body/div[1]/div/div[3]/div[2]/div[1]/div[1]/div[4]')
  File "C:\Users\Patrick\Desktop\bulk-upload-to-opensea-main\upload_captcha.py", line 254, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Users\Patrick\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x00887413+2389011]
        Ordinal0 [0x00819F61+1941345]
        Ordinal0 [0x0070C658+837208]
        Ordinal0 [0x007391DD+1020381]
        Ordinal0 [0x0073949B+1021083]
        Ordinal0 [0x00766032+1204274]
        Ordinal0 [0x00754194+1130900]
        Ordinal0 [0x00764302+1196802]
        Ordinal0 [0x00753F66+1130342]
        Ordinal0 [0x0072E546+976198]
        Ordinal0 [0x0072F456+980054]
        GetHandleVerifier [0x00A39632+1727522]
        GetHandleVerifier [0x00AEBA4D+2457661]
        GetHandleVerifier [0x0091EB81+569713]
        GetHandleVerifier [0x0091DD76+566118]
        Ordinal0 [0x00820B2B+1968939]
        Ordinal0 [0x00825988+1989000]
        Ordinal0 [0x00825A75+1989237]
        Ordinal0 [0x0082ECB1+2026673]
        BaseThreadInitThunk [0x7692FA29+25]
        RtlGetAppContainerNamedObjectPath [0x76F17A9E+286]
        RtlGetAppContainerNamedObjectPath [0x76F17A6E+238]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Patrick\Desktop\bulk-upload-to-opensea-main\upload_captcha.py", line 415, in main_program_loop
    capt_btn = driver.find_element_by_xpath("//button[@id='solver-button']")
  File "C:\Users\Patrick\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 514, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Patrick\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Patrick\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Patrick\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[@id='solver-button']"}
  (Session info: chrome=100.0.4896.75)
Stacktrace:
Backtrace:
        Ordinal0 [0x00887413+2389011]
        Ordinal0 [0x00819F61+1941345]
        Ordinal0 [0x0070C658+837208]
        Ordinal0 [0x007391DD+1020381]
        Ordinal0 [0x0073949B+1021083]
        Ordinal0 [0x00766032+1204274]
        Ordinal0 [0x00754194+1130900]
        Ordinal0 [0x00764302+1196802]
        Ordinal0 [0x00753F66+1130342]
        Ordinal0 [0x0072E546+976198]
        Ordinal0 [0x0072F456+980054]
        GetHandleVerifier [0x00A39632+1727522]
        GetHandleVerifier [0x00AEBA4D+2457661]
        GetHandleVerifier [0x0091EB81+569713]
        GetHandleVerifier [0x0091DD76+566118]
        Ordinal0 [0x00820B2B+1968939]
        Ordinal0 [0x00825988+1989000]
        Ordinal0 [0x00825A75+1989237]
        Ordinal0 [0x0082ECB1+2026673]
        BaseThreadInitThunk [0x7692FA29+25]
        RtlGetAppContainerNamedObjectPath [0x76F17A9E+286]
        RtlGetAppContainerNamedObjectPath [0x76F17A6E+238]

**Comment by denomparkour** [comment]
+1

**Comment by infotrex** [comment]
@patrickhiro
do you install any buster solver extesion?

**Comment by nftje** [comment]
It happend to me as well. I was able to fix by listening to the instruction carefully. So the solution was just type the correct OpenSea Collection link in the program. basically the complete link has to be: Opensea collection link: https://opensea.io/collection/kick-skull/assets/create. the missing last part of the link was creating the problem. hope it helps.
