### ISSUE TITLE
They stop constantly

### ISSUE THREAD

**Issue by Many2050** [infotrex/bulk-upload-to-opensea#164]
Greetings, it goes from 1 to 5 nft and the script stops, an error appears on the opensea page, what can I do?  thank you

note and only 1 uploads me none

**Comment by Many2050** [comment]
![Captura de pantalla (1)](https://user-images.githubusercontent.com/101189664/163429725-56f0ed6f-deb7-4d1f-9c2e-2acb04705233.png)

**Comment by Many2050** [comment]
![Captura de pantalla (1)](https://user-images.githubusercontent.com/101189664/163429896-48cbb886-48c5-46fe-8a85-96cbd4c7cc2a.png)

**Comment by infotrex** [comment]
@Many2050 
this may something wrong about the opensea website.

**Comment by Many2050** [comment]
I understand that mistake but the most common is this

**Comment by Many2050** [comment]
![Captura de pantalla (5)](https://user-images.githubusercontent.com/101189664/163684549-9b3ce3f3-6df9-4b78-b09b-8d64986969cb.png)

**Comment by karakule3dfx** [comment]
you can follow this link 
https://github.com/infotrex/bulk-upload-to-opensea/issues/159

The reason for the error in the displayed picture; Stuck at the "Oops, something went wrong" screen
