### ISSUE TITLE
Problem  'RtlGetAppContainerNamedObjectPath'

### ISSUE THREAD

**Issue by Frapuch** [infotrex/bulk-upload-to-opensea#166]
Hello! I can't fix this problem. I think it's common and someone can help. Thank you very much in advance!

         self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="__next"]/div[1]/main/div/div/section/div[2]/form/div/div[1]/span/button"}
  (Session info: chrome=100.0.4896.88)
Stacktrace:
Backtrace:
        Ordinal0 [0x00D17413+2389011]
        Ordinal0 [0x00CA9F61+1941345]
        Ordinal0 [0x00B9C658+837208]
        Ordinal0 [0x00BC91DD+1020381]
        Ordinal0 [0x00BC949B+1021083]
        Ordinal0 [0x00BF6032+1204274]
        Ordinal0 [0x00BE4194+1130900]
        Ordinal0 [0x00BF4302+1196802]
        Ordinal0 [0x00BE3F66+1130342]
        Ordinal0 [0x00BBE546+976198]
        Ordinal0 [0x00BBF456+980054]
        GetHandleVerifier [0x00EC9632+1727522]
        GetHandleVerifier [0x00F7BA4D+2457661]
        GetHandleVerifier [0x00DAEB81+569713]
        GetHandleVerifier [0x00DADD76+566118]
        Ordinal0 [0x00CB0B2B+1968939]
        Ordinal0 [0x00CB5988+1989000]
        Ordinal0 [0x00CB5A75+1989237]
        Ordinal0 [0x00CBECB1+2026673]
        BaseThreadInitThunk [0x75D20419+25]
        RtlGetAppContainerNamedObjectPath [0x77E472FD+237]
        RtlGetAppContainerNamedObjectPath [0x77E472CD+189]

**Comment by infotrex** [comment]
@Frapuch 
might be some field you not fill in correctly,
that why the "create" button not visible.
run the script again to solve that issue

**Comment by Frapuch** [comment]
@infotrex the program is reset during SOLVING is in  Process. 
polygon
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Administrator\Desktop\bulk-upload-to-opensea-main-2\upload_2captcha.py", line 391, in main_program_loop
    solved_info = WebDriverWait(driver, 20).until(ExpectedConditions.presence_of_element_located((By.XPATH, "//*[@class='captcha-solver-info']" )))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x00C57413+2389011]
        Ordinal0 [0x00BE9F61+1941345]
        Ordinal0 [0x00ADC658+837208]
        Ordinal0 [0x00B091DD+1020381]
        Ordinal0 [0x00B0949B+1021083]
        Ordinal0 [0x00B36032+1204274]
        Ordinal0 [0x00B24194+1130900]
        Ordinal0 [0x00B34302+1196802]
        Ordinal0 [0x00B23F66+1130342]
        Ordinal0 [0x00AFE546+976198]
        Ordinal0 [0x00AFF456+980054]
        GetHandleVerifier [0x00E09632+1727522]
        GetHandleVerifier [0x00EBBA4D+2457661]
        GetHandleVerifier [0x00CEEB81+569713]
        GetHandleVerifier [0x00CEDD76+566118]
        Ordinal0 [0x00BF0B2B+1968939]
        Ordinal0 [0x00BF5988+1989000]
        Ordinal0 [0x00BF5A75+1989237]
        Ordinal0 [0x00BFECB1+2026673]
        BaseThreadInitThunk [0x757C0419+25]
        RtlGetAppContainerNamedObjectPath [0x76F272FD+237]
        RtlGetAppContainerNamedObjectPath [0x76F272CD+189]

**Comment by Frapuch** [comment]
dear @infotrex i hope you can help me. I have tried all options. my telegram @dilindreev

**Comment by karakule3dfx** [comment]
i cant understand but sometimes there is no data entry in the name box, so the create button cannot be activated.
and for solved_info = WebDriverWait(driver, 20)  you can write solved_info = WebDriverWait(driver, 150)

I added some code and changed some things and it seems that there is no problem for now but my tests continue.

@infotrex How to send the codes to you so that you can review

**Comment by Frapuch** [comment]
@karakule3dfx thx u so match, but it doesn't work. And it does not advance to list it and put it up for sale. 
don't take it as impudence, but do you have the opportunity to share your code with me?

**Comment by infotrex** [comment]
> i cant understand but sometimes there is no data entry in the name box, so the create button cannot be activated. and for solved_info = WebDriverWait(driver, 20) you can write solved_info = WebDriverWait(driver, 150)
> 
> I added some code and changed some things and it seems that there is no problem for now but my tests continue.
> 
> @infotrex How to send the codes to you so that you can review

hi, you can email to me kelvintss@gmail.com
and mention which line you want to amend. :)

**Comment by karakule3dfx** [comment]
@infotrex i send mail to you with karakule3dfx title

**Comment by Frapuch** [comment]
all is good
