### ISSUE TITLE
unlock selling functionally

### ISSUE THREAD

**Issue by sskr369** [infotrex/bulk-upload-to-opensea#167]
![Screenshot (4)](https://user-images.githubusercontent.com/103888131/163716578-bb3d241c-aec2-4a5c-884a-967e5914d86a.png)

**Comment by sskr369** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/103888131/163716630-ecc1fa7d-ceaa-4e88-8e31-9163ee6779e3.png)

**Comment by Frapuch** [comment]
The first unlock you have to do yourself

**Comment by Frapuch** [comment]
please close Issue
