### ISSUE TITLE
No progress after creating the NFT

### ISSUE THREAD

**Issue by Zoelekko** [infotrex/bulk-upload-to-opensea#169]
I did the test with the default configuration, using my URL, but after placing the image, the metadata and doing the Captcha, it freezes, as seen in image 1.

![1](https://user-images.githubusercontent.com/96668644/163884945-bc827ca9-9c23-43b5-9ed8-6ebd4e9def6e.png)

And it does not advance to list it and put it up for sale.

![2](https://user-images.githubusercontent.com/96668644/163884947-d4108341-c6d1-4869-9efb-446745702169.png)

**Comment by Chanuth01** [comment]
This because chrome new update
To fix that just install compatible chromedriver
you can download chrome driver here : https://chromedriver.chromium.org/downloads

**Comment by Chanuth01** [comment]
I you don't know how to install chromedriver this video will helps : https://www.youtube.com/watch?v=dz59GsdvUF8

**Comment by Chanuth01** [comment]
To check your chrome version ,
Open the browser and click the ⋮ button in the top right. Go to Help-->About Google Chrome.

**Comment by sskr369** [comment]
same problem

**Comment by sskr369** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/103888131/165160827-5bb80ea0-d27e-43e1-8fcf-0edff281f239.png)

**Comment by sabalmyeon** [comment]
> If you don't know how to install chromedriver this video will helps : https://www.youtube.com/watch?v=dz59GsdvUF8

Which chrome driver version should I download?

**Comment by Chanuth01** [comment]
> 

What is your chrome version?
To check your chrome version,
Open the browser and click the ⋮ button in the top right. Go to Help-->About Google Chrome.
