### ISSUE TITLE
I can't sell automatically

### ISSUE THREAD

**Issue by ZaryImortal** [infotrex/bulk-upload-to-opensea#17]
![image](https://user-images.githubusercontent.com/57652636/149024965-540d7bc4-938c-440a-968d-c4936c130acb.png)
![image](https://user-images.githubusercontent.com/57652636/149025006-1a409edf-1fa6-423b-b037-4dcbb49b6488.png)
![image](https://user-images.githubusercontent.com/57652636/149025040-c9300b9f-fbee-4bdd-992f-c5d66514c212.png)

command> python upload.py

**Comment by infotrex** [comment]
pls check "polygon blockchain" if you using polygon

**Comment by ZaryImortal** [comment]
the code breaks by itself after a while.
![image](https://user-images.githubusercontent.com/57652636/149246182-5c80cc2e-7e5a-453f-a199-59f9f37b141c.png)

**Comment by infotrex** [comment]
@ZaryImortal might be your internet slow or opensea website issue.
