### ISSUE TITLE
Stop in wallet metamask

### ISSUE THREAD

**Issue by Many2050** [infotrex/bulk-upload-to-opensea#171]
I downloaded the latest update but the wallet process stops, thanks

**Comment by infotrex** [comment]
do you login in the wallet before start running the process?

**Comment by Many2050** [comment]
> do you login in the wallet before start running the process?

Greetings, if you do, upload the ntf metadata, everything is fine when you go to sign the ntf wallet, it gets stuck, thanks for answering

**Comment by Many2050** [comment]
> do you login in the wallet before start running the process?

![Captura de pantalla (8)](https://user-images.githubusercontent.com/101189664/164229222-9938411e-a80b-4ddd-896a-7ca3712f5a48.png)

**Comment by Many2050** [comment]
> > do you login in the wallet before start running the process?
> 
> Greetings, if you do, upload the ntf metadata, everything is fine when you go to sign the ntf wallet, it gets stuck, thanks for answering

![Uploading Captura de pantalla (9).png…]()

**Comment by karakule3dfx** [comment]
Try upload_2captcha V2.py
