### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by VilleVessla** [infotrex/bulk-upload-to-opensea#175]
Nothing happens when I push the button. It gets grayed out for a few seconds but then returns to normal again. Can it have something to do with the operating system's language or Windows firewall?

**Comment by karakule3dfx** [comment]
if you can be more descriptive or have a short screen video. I can try to help.

**Comment by VilleVessla** [comment]
I have it working now, but it stops right after one NFT is created.
![1](https://user-images.githubusercontent.com/104421394/165376174-f4d05f9a-59d0-4a20-94b2-786501b9e0de.jpg)
![No2](https://user-images.githubusercontent.com/104421394/165376195-1adaf976-ff2f-4cc2-9a5f-11f3fc61e146.jpg)

**Comment by karakule3dfx** [comment]
I can't think of any reason for this to happen. if it happens too often, please send a short video. This way we can understand more clearly. Or you can try increasing the value from 360 to 720.

It may be useful to send the browser image when the error occurs.
I don't know why, but everyone has different errors.

**Comment by karakule3dfx** [comment]
Try upload_2captcha V2.py please. I hope this will help
