### ISSUE TITLE
just upload one

### ISSUE THREAD

**Issue by Je0917** [infotrex/bulk-upload-to-opensea#176]
upload the first one, ask for captcha review, then permissions in metamask and when it says that it is listed it does nothing else @ZacharyAkers @infotrex

**Comment by Je0917** [comment]
i add the captcha solver but now is metamask with protocol signature, please help

**Comment by Many2050** [comment]
Not work

**Comment by karakule3dfx** [comment]
Try upload_2captcha V2.py please. I hope this will help
