### ISSUE TITLE
Opensea asking for ''I'm not a Robot'' verification before uploading NFT

### ISSUE THREAD

**Issue by Priyarajsinh** [infotrex/bulk-upload-to-opensea#177]
![Screenshot (1)](https://user-images.githubusercontent.com/100425716/166105735-d9f94e0e-75b4-4966-b73a-da7c459bdd64.png)
please help me with this problem.

**Comment by Je0917** [comment]
hey, we got the same problem i just can add one by one nft, i read something of captcha solver extension but i don't understand about a key.

**Comment by u3533791** [comment]
same issue

**Comment by Priyarajsinh** [comment]
> hey, we got the same problem i just can add one by one nft, i read something of captcha solver extension but i don't understand about a key.

hey if you have captcha solver then please give me

**Comment by Je0917** [comment]
They add different versions i use this but then the problem is metamask

Version 1.8.8 (upload_captcha.py)
Add chrome extesion: Buster: Captcha Solver for Humans
https://chrome.google.com/webstore/detail/buster-captcha-solver-for/mpbjkejclgfgadiemmefgebjfooflfhl?hl=en
extension settings: Select any "speech service" and put in API key

**Comment by Je0917** [comment]
I think We got problems, please somebody can do something?? 🥺😪

https://youtu.be/DOKfMYasw98

**Comment by Priyarajsinh** [comment]
> I think We got problems, please somebody can do something?? 🥺😪
> 
> https://youtu.be/DOKfMYasw98

I found new method , i tried half of it till metamask connected to opensea , it has captcha solver also , but files are too big . I thinks that's our last hope 
https://youtu.be/sM-YncZmZzc

**Comment by Priyarajsinh** [comment]
https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale

**Comment by Priyarajsinh** [comment]
> I think We got problems, please somebody can do something?? 🥺😪
> 
> https://youtu.be/DOKfMYasw98

https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale

try this out , it's our only hope

**Comment by Je0917** [comment]
we need to pay this?

Paid service: $2.99 per 1000 reCAPTCHAs.

**Comment by Priyarajsinh** [comment]
> we need to pay this?
> 
> Paid service: $2.99 per 1000 reCAPTCHAs.

No bro it's free i guess , but where did you find this 3$ thing?

**Comment by Priyarajsinh** [comment]
> we need to pay this?
> 
> Paid service: $2.99 per 1000 reCAPTCHAs.

i saw just now , i think if we sign up to that thing then only we have to give 3$ otherwise not

**Comment by geokomplo** [comment]
> same issue



> > we need to pay this?
> > Paid service: $2.99 per 1000 reCAPTCHAs.
> 
> i saw just now , i think if we sign up to that thing then only we have to give 3$ otherwise not

https://youtu.be/2KFkmBE-RWA
