### ISSUE TITLE
Add Item not working

### ISSUE THREAD

**Issue by misterkayr** [infotrex/bulk-upload-to-opensea#180]
I am using 2Captcha and have Credit in the account
I have the latest chrome browser and chrome driver installed Version 101.0.4951.41 (Official Build) (64-bit)
Everything works perfect and does the SELL

Then when it completes the NFT and set the sell, it goes back to the collection page as usual

Thats when it stops and I have to manually click "Add Item"

Its as if the Add Item code is not working
Any fixes for this?

**Comment by karakule3dfx** [comment]
Try upload_2captcha V2.py please. I hope this will help
