### ISSUE TITLE
DOES NOT SIGN IN OM METAMASK

### ISSUE THREAD

**Issue by littlebopeep** [infotrex/bulk-upload-to-opensea#181]
Hi.
I've never had an upload as fast as it has today. Creating an item and going past the captcha was no problem at all.
The code works great. The issue I think is with Metamask and it stops when creating a listing. It does not go past the step of signing in on Metamask. 
The problem with Metamask now is that on the SIGNATURE REQUEST, the SIGN button is not clickable unless an arrow is clicked to show that the whole message is read. It was never like this before. 
I don't know if I'm explaining this right. I hope someone gets it..

**Comment by misterkayr** [comment]
Just try one of the other "upload" scripts as your issue was solved ages ago
I personally use this one upload_2captcha.py

**Comment by arinze01** [comment]
If can't edit the code delete the code and download again ifotrex update this issue days ago

**Comment by misterkayr** [comment]
> If can't edit the code delete the code and download again ifotrex update this issue days ago

You dont have to code anything...
Just go to [https://github.com/infotrex/bulk-upload-to-opensea](https://github.com/infotrex/bulk-upload-to-opensea) and click the GREEN Code Button and Download the ZIP file....

**Comment by karakule3dfx** [comment]
Try upload_2captcha V2.py please. I hope this will help
