### ISSUE TITLE
Bulk uploading

### ISSUE THREAD

**Issue by gilh1221** [infotrex/bulk-upload-to-opensea#182]
Hey everyone,

Has anyone been able to upload lately? Please let me know if v. 1.8.2 or 1.9 has a solution. I have to solve a captcha every time an item is uploaded.

**Comment by gilh1221** [comment]
Does it work well if you pay a few dollars?

**Comment by Je0917** [comment]
> I have no issues and I use the latest versions I use the 2Captcha version... Sometimes, paying a few dollars to get Captcha done, makes things easier

you dont have problems with your wallet? (if its metamask)

**Comment by gilh1221** [comment]
Thanks

**Comment by gilh1221** [comment]
Want to be sure that it works after a few dollars are paid to use 2Captcha solver

**Comment by misterkayr** [comment]
yes
