### ISSUE TITLE
anyone can upload?

### ISSUE THREAD

**Issue by Je0917** [infotrex/bulk-upload-to-opensea#183]
I'm still having problems, i don't know what I'm doing bad, the first NFT upload but metamask don't recommend the upload because it was RPC Polygon and don't recognize.

**Comment by dogebi2** [comment]
no ,that display the not found chromedriver. ,  in Mac OS

**Comment by Devjohn12** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.
