### ISSUE TITLE
Loop Upload not Working. It stops uploading after listing 1 nft need to start manually by entering next nft start number

### ISSUE THREAD

**Issue by jdmakwana555** [infotrex/bulk-upload-to-opensea#184]

**Comment by mclombaard** [comment]
yes same issue here. Using the 2captcha.py. Most I got was 3 in a row then it stops at random places. Takes me more time to restart than to rather create myself 1 by 1

**Comment by jdmakwana555** [comment]
What is 2captcha.py

**Comment by jdmakwana555** [comment]
> stopped working for me as well

Was it working before?

**Comment by sabalmyeon** [comment]
I Implemented upload_captcha2.py, It didn't link creat in opensea. So, I clicked "creat" then it worked. But, it didn't loop upload. And just it filled out to description. It didn't change the "blockchain"(ethereum->polygon) although I checked "polygon blockchain" in program.

**Comment by moeeenkhan1215** [comment]
OpenSea made some updates that's why the loop is not working.

**Comment by karakule3dfx** [comment]
Try upload_2captcha V2.py please. I hope this will help

**Comment by moeeenkhan1215** [comment]
I tried  but its not working man  after uploading 1 nft loop is not working

**Comment by karakule3dfx** [comment]
Which line does the error occur on?

**Comment by moeeenkhan1215** [comment]
not showing any error man lop stop after uploading 1 nxt then you have to add the 
next number of nft and start again it will after uploading 1 nft

**Comment by karakule3dfx** [comment]
if you don't get an error
wait at least 5 minutes and it will give an error.
so we can see exactly on which line the problem.

If you post a picture of the problem line, I can take a closer look.

So you have to wait until it fails.
 If it doesn't send you to the main page of opensea,
 it means that the codes continue to work.

If you add a picture of the adjusted state of the program, I can make a healthier review.
The more information I have about the error, the better results we can get.
