### ISSUE TITLE
The nft 1 remains displayed and does not pass to the next one

### ISSUE THREAD

**Issue by Jordantazi** [infotrex/bulk-upload-to-opensea#188]
Hello everyone, I have a problem. I managed to put 1000nft online but the next day I had a problem the script freezes at the end of the creation and the page does not want to switch to the other nft. I have a Web driver problem in the code that I didn't have yesterday. However even by changing the version of chrome and web drive I still have the same problem can you help me? Thank you.

**Comment by karakule3dfx** [comment]
Try upload_2captcha V2.py please. I hope this will help
