### ISSUE TITLE
listing stoped

### ISSUE THREAD

**Issue by Pedrosilva1197** [infotrex/bulk-upload-to-opensea#191]
Hello,
i have been using this system for some time now with no problems but since a couple of days ago it stops after creating the nft and doesn't do the listing can someone help me please
![Capture](https://user-images.githubusercontent.com/106240355/170241656-a4d29ce3-0c80-47c8-a4cf-79f651ad4a40.PNG)
.

**Comment by pigxls** [comment]
I am experiencing the exact same issue as you. 

It uploads the NFT perfectly passing the captcha but as soon as it's listed the box does not close and the application hangs until it provided these error messages.
![Issues with upload](https://user-images.githubusercontent.com/106412821/170801262-bb0da258-b1dd-4d5f-9c90-85391e2a32d0.PNG)

**Comment by maarcek** [comment]
> I am experiencing the exact same issue as you.
> 
> It uploads the NFT perfectly passing the captcha but as soon as it's listed the box does not close and the application hangs until it provided these error messages. ![Issues with upload](https://user-images.githubusercontent.com/106412821/170801262-bb0da258-b1dd-4d5f-9c90-85391e2a32d0.PNG)

Yeah, same here... hope the dev will fix it soon.

**Comment by karakule3dfx** [comment]
Try upload_2captcha V2.py please. I hope this will help
