### ISSUE TITLE
Session hangs once listing the NFT

### ISSUE THREAD

**Issue by pigxls** [infotrex/bulk-upload-to-opensea#192]
Hi, 

When running the script to upload the NFT to Opensea (python upload_captcha.py) it successfully uploads the NFT and processes the Captcha which pops up on the screen. 

Then the application hangs and until it's become response it's fails and does not progress any further. Here is the code it presents once failing. 

The problem here is that you have to wait for the application to become responsive before you can consider listing the next NFT.
![Issues with upload](https://user-images.githubusercontent.com/106412821/170801438-4445833a-774f-4560-8c6e-88c75de4889f.PNG)

**Comment by karakule3dfx** [comment]
Try upload_2captcha V2.py please. I hope this will help
