### ISSUE TITLE
Loop doesn't work. infotrex save me 

### ISSUE THREAD

**Issue by maarcek** [infotrex/bulk-upload-to-opensea#194]
For me everything worked (entering data, captcha etc.) except looping the process. The program after 1 upload just stops. @infotrex , Could you make some update when the program after successful process, closes chrome window and opens new one where it repeats the process? Please, save my ass, Im begging you.

EDIT: I didn't know people had same problem before i posted this ticket... i hope it doesnt bother anybody
2nd EDIT: Just found out that the problem is that opensea has new UI design so @infotrex's script doesnt know exactly what to do or where to click

**Comment by maarcek** [comment]
Forgot to say that it doesnt even finish listing (adding price) ... it just stays at this window and program says : 
"Ordinal0 [0x0115ECB1+2026673]
        BaseThreadInitThunk [0x759BFA29+25]
        RtlGetAppContainerNamedObjectPath [0x778F7A7E+286]
        RtlGetAppContainerNamedObjectPath [0x778F7A4E+238]"
![image](https://user-images.githubusercontent.com/106628236/171381344-11e18adc-8583-4a71-9b08-ca5d1135b6e7.png)

**Comment by karakule3dfx** [comment]
I'll try when I'm available. i hope i can make it.

**Comment by karakule3dfx** [comment]
Try upload_2captcha V2.py please. I hope this will help

**Comment by jdmakwana555** [comment]
while opening upload_2captcha V2.py having following error...

self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\jdmak\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__       
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\jdmak\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
PS C:\Users\jdmak\Downloads\bulk-upload-to-opensea-main (2)\bulk-upload-to-opensea-main> python upload_2captcha V2.py
C:\Users\jdmak\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'C:\\Users\\jdmak\\Downloads\\bulk-upload-to-opensea-main (2)\\bulk-upload-to-opensea-main\\upload_2captcha': [Errno 2] No such file or directory
PS C:\Users\jdmak\Downloads\bulk-upload-to-opensea-main (2)\bulk-upload-to-opensea-main>

**Comment by karakule3dfx** [comment]
Hi @jdmakwana555  

What is your operating system and version?

**Comment by jdmakwana555** [comment]
@karakule3dfx 
windows 11 home
Version: 21H2
OS BUILD: 22000.675
Windows Feature Experience Pack 1000.22000.675.0

**Comment by karakule3dfx** [comment]
i don't have a solution. but you can control this

https://www.youtube.com/watch?v=BqqLKuxtTa4

https://www.youtube.com/watch?v=bCY4D9n3Pew

Have you tried with any code whether python is working or not?
