### ISSUE TITLE
needs update for new opensea algorthym

### ISSUE THREAD

**Issue by hamhocks** [infotrex/bulk-upload-to-opensea#195]
the software needs updating for the new algorthym at opensea to work well. It's better than nothing but not as good as it was.

**Comment by maarcek** [comment]
bump,... i tried to contact the dev through twitter but so far no luck

**Comment by geokomplo** [comment]
> the software needs updating for the new algorthym at opensea to work well. It's better than nothing but not as good as it was.



> bump,... i tried to contact the dev through twitter but so far no luck

https://youtu.be/2KFkmBE-RWA

**Comment by karakule3dfx** [comment]
Try upload_2captcha V2.py please. I hope this will help
