### ISSUE TITLE
Open Chrome Browser Error

### ISSUE THREAD

**Issue by bizimburak** [infotrex/bulk-upload-to-opensea#2]
When I click the Open Chrome Browser button, it gives an error. chorome not found.

**Comment by bizimburak** [comment]
Executable Path | C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Profile Path | C:\Users\RoyaLy\AppData\Local\Google\Chrome\User

PLSSSS

**Comment by infotrex** [comment]
Copy Chrome profile into Chrome profile that come with the repo in this folder
search "%LOCALAPPDATA%\Google\Chrome\User Data\" copy chrome profile.
https://www.howtogeek.com/255653/how-to-find-your-chrome-profile-folder-on-windows-mac-and-linux/

**Comment by bizimburak** [comment]
I don't understand what you mean exactly, can you add a picture or video?

**Comment by bizimburak** [comment]
In chrome_profile there is only Copy_chrome_profile_to_here.txt "couldn't find repo file"

**Comment by hamzaoub** [comment]
same prob i have mac device

**Comment by infotrex** [comment]
> Executable Path | C:\Program Files (x86)\Google\Chrome\Application\chrome.exe Profile Path | C:\Users\RoyaLy\AppData\Local\Google\Chrome\User Data\Profile 1
> 
> PLSSSS

copy your "Profile 1" file into "chrome_profile.

**Comment by infotrex** [comment]
> same prob i have mac device

i don't have mac device, i not sure how to copy the the chrome profile.

**Comment by bizimburak** [comment]
ERROR https://i.hizliresim.com/82uxox8.png

I don't understand where is the problem

PLS!!!!!!!!!!!!!!!!!!!!!!!!
