### ISSUE TITLE
Is it possible to post in polygon network? 

### ISSUE THREAD

**Issue by euginepj** [infotrex/bulk-upload-to-opensea#20]
Sir, The plugin is working well. But I am stuck at the point the payment is called. Is it possible to post items as in Polygon network. 
I have checked the Polygon Blockchain but still it is not working.

**Comment by infotrex** [comment]
@euginepj 
Your default collection is ETH?
While uploading your want auto select the dropdown to "polygon"?

**Comment by Intelligencybar** [comment]
yes

**Comment by p4rnicke** [comment]
Same issue here. The collection already exists with items in it.
But the default blockchain can not be altered on OpenSea for some reason.
The input name="chain" is holding the selected blockchain on the create item page.
