### ISSUE TITLE
Issue at signing metamask

### ISSUE THREAD

**Issue by gallant1357** [infotrex/bulk-upload-to-opensea#201]
because now you need to scroll down to read the whole text before you are able to sign on metamask when listing, it got stuck on that.

**Comment by karakule3dfx** [comment]
If you can explain, I will try to help. which version are you using

**Comment by gallant1357** [comment]
> If you can explain, I will try to help. which version are you using

When you are at the steps to listen for a price, you will need to sign on the MetaMask window to confirm, it has been updated that you have to scroll thru the entire detail on that window (like Reading TOS before install) before you can confirm signing, otherwise the sign button is greyed out, thus stuck on that part.


Also for people who said clicking the start button doesn’t do anything, make sure the google chrome web driver version matches your normal google chrome.

**Comment by karakule3dfx** [comment]
The codes are working fine for me. I am using upload_2captcha V2.py. and it works fine in the ethereum network.
Which file and network are you using?

**Comment by gallant1357** [comment]
> The codes are working fine for me. I am using upload_2captcha V2.py. and it works fine in the ethereum network.
> Which file and network are you using?

I’m using the same version as you did. It’s just the final part where you have to sign on MetaMask got stuck

**Comment by karakule3dfx** [comment]
what error do you get. 
if you don't get an error
wait at least 5 minutes and it will give an error.
so we can see exactly on which line the problem.

If you post a picture of the problem line, I can take a closer look.

I try again and again, but there is no problem for me.

**Comment by gallant1357** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\NFT Bulk\bulk-upload-to-opensea-main\upload_2captchaV2.py", line 659, in main_program_loop
    WebDriverWait(driver, 60).until(ExpectedConditions.presence_of_element_located((By.XPATH, "//button[text()='Sign']")))#HKN
  File "C:\Users\galla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x00EDD953+2414931]
        Ordinal0 [0x00E6F5E1+1963489]
        Ordinal0 [0x00D5C6B8+837304]
        Ordinal0 [0x00D89500+1021184]
        Ordinal0 [0x00D8979B+1021851]
        Ordinal0 [0x00DB6502+1205506]
        Ordinal0 [0x00DA44E4+1131748]
        Ordinal0 [0x00DB4812+1198098]
        Ordinal0 [0x00DA42B6+1131190]
        Ordinal0 [0x00D7E860+976992]
        Ordinal0 [0x00D7F756+980822]
        GetHandleVerifier [0x0114CC62+2510274]
        GetHandleVerifier [0x0113F760+2455744]
        GetHandleVerifier [0x00F6EABA+551962]
        GetHandleVerifier [0x00F6D916+547446]
        Ordinal0 [0x00E75F3B+1990459]
        Ordinal0 [0x00E7A898+2009240]
        Ordinal0 [0x00E7A985+2009477]
        Ordinal0 [0x00E83AD1+2046673]
        BaseThreadInitThunk [0x75B3FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77657A7E+286]
        RtlGetAppContainerNamedObjectPath [0x77657A4E+238]

> what error do you get. if you don't get an error wait at least 5 minutes and it will give an error. so we can see exactly on which line the problem.
> 
> If you post a picture of the problem line, I can take a closer look.
> 
> I try again and again, but there is no problem for me.

**Comment by gallant1357** [comment]
![Capture](https://user-images.githubusercontent.com/26252836/172097128-2195b997-d2f4-457a-bfa2-c05186fff9c1.PNG)
What happened is i have to scroll down on the metamask and read all the details before the sign button turns blue, thus stuck on that part

**Comment by karakule3dfx** [comment]
I understand now. I use Eth but you use polygon.  As far as I understand, a change has been made for the polygon. today i try to find changes for polygon. Thanks for comment. And sorry my english is not good

**Comment by gallant1357** [comment]
its ok, thanks for looking into the problem

**Comment by karakule3dfx** [comment]
I think the problem is fixed. please try and feedback. and https://chromedriver.chromium.org/ use Latest stable release

**Comment by gallant1357** [comment]
Can confirm, issue has been resolved

**Comment by karakule3dfx** [comment]
Thanks @gallant1357
