### ISSUE TITLE
error while listing

### ISSUE THREAD

**Issue by besttomodachiclub** [infotrex/bulk-upload-to-opensea#206]
network is polygon. i used python upload_captcha.py.
![Screenshot (31)_LI](https://user-images.githubusercontent.com/106145449/172884927-faac7ec5-b525-486b-ad64-909881737061.jpg)
![Screenshot (30)](https://user-images.githubusercontent.com/106145449/172885005-aa264f82-4c4e-4be4-83da-d4bc3c4641a7.png)

**Comment by besttomodachiclub** [comment]
full error code- G:\bulk-upload-to-opensea-main\upload_captcha.py:238: DeprecationWarning: executable_path has been deprecated, please pass in a 
Service object
  driver = webdriver.Chrome(executable_path=project_path + "/chromedriver.exe",options=opt)
Start creating NFT Best Tomodachi #366
number  366
Polygon
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "G:\bulk-upload-to-opensea-main\upload_captcha.py", line 502, in main_program_loop
    driver.find_element(By.XPATH, '//button[text()="Sign"]').click()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[text()="Sign"]"}
  (Session info: chrome=102.0.5005.63)
Stacktrace:
Backtrace:
        Ordinal0 [0x00D4D953+2414931]
        Ordinal0 [0x00CDF5E1+1963489]
        Ordinal0 [0x00BCC6B8+837304]
        Ordinal0 [0x00BF9500+1021184]
        Ordinal0 [0x00BF979B+1021851]
        Ordinal0 [0x00C26502+1205506]
        Ordinal0 [0x00C144E4+1131748]
        Ordinal0 [0x00C24812+1198098]
        Ordinal0 [0x00C142B6+1131190]
        Ordinal0 [0x00BEE860+976992]
        Ordinal0 [0x00BEF756+980822]
        GetHandleVerifier [0x00FBCC62+2510274]
        GetHandleVerifier [0x00FAF760+2455744]
        GetHandleVerifier [0x00DDEABA+551962]
        GetHandleVerifier [0x00DDD916+547446]
        Ordinal0 [0x00CE5F3B+1990459]
        Ordinal0 [0x00CEA898+2009240]
        Ordinal0 [0x00CEA985+2009477]
        Ordinal0 [0x00CF3AD1+2046673]
        BaseThreadInitThunk [0x74A86359+25]
        RtlGetAppContainerNamedObjectPath [0x771A7B74+228]
        RtlGetAppContainerNamedObjectPath [0x771A7B44+180]

**Comment by karakule3dfx** [comment]
Find these line and

```
if is_polygon.get():
                driver.find_element(By.XPATH, '//button[text()="Sign"]').click()
                time.sleep(sleeptime)
```
change like this

```
#if is_polygon.get():
                #driver.find_element(By.XPATH, '//button[text()="Sign"]').click()
                #time.sleep(sleeptime)
```

so add # at the beginning of the line 

OR

use new version "upload_2captcha V2.py"
