### ISSUE TITLE
The chrome version is different, how can I solve it?

### ISSUE THREAD

**Issue by khaki12** [infotrex/bulk-upload-to-opensea#207]
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at localhost:8989
from session not created: This version of ChromeDriver only supports Chrome version 100
Current browser version is 102.0.5005.115
That's what it says
The version is higher, what should I do?

**Comment by karakule3dfx** [comment]
https://chromedriver.chromium.org/
 download Latest stable release chromedriver.exe and replace with old file
