### ISSUE TITLE
Sadden stop Uploading.. Any help please 

### ISSUE THREAD

**Issue by ramidalloul** [infotrex/bulk-upload-to-opensea#209]
It was working great with captcha.py but stopped uploading.. although it passed captcha test.. it's only doing one upload and no listing 

here is the error 

  Start creating NFT My Zombie #406
number  406
Polygon
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\new downloads\nft\to upload\bulk-upload-to-opensea-main\upload_captcha.py", line 439, in main_program_loop
    wait_xpath('/html/body/div[6]/div/div/div/div[2]/button/i')
  File "D:\new downloads\nft\to upload\bulk-upload-to-opensea-main\upload_captcha.py", line 254, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Users\RAMI\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x004ED953+2414931]
        Ordinal0 [0x0047F5E1+1963489]
        Ordinal0 [0x0036C6B8+837304]
        Ordinal0 [0x00399500+1021184]
        Ordinal0 [0x0039979B+1021851]
        Ordinal0 [0x003C6502+1205506]
        Ordinal0 [0x003B44E4+1131748]
        Ordinal0 [0x003C4812+1198098]
        Ordinal0 [0x003B42B6+1131190]
        Ordinal0 [0x0038E860+976992]
        Ordinal0 [0x0038F756+980822]
        GetHandleVerifier [0x0075CC62+2510274]
        GetHandleVerifier [0x0074F760+2455744]
        GetHandleVerifier [0x0057EABA+551962]
        GetHandleVerifier [0x0057D916+547446]
        Ordinal0 [0x00485F3B+1990459]
        Ordinal0 [0x0048A898+2009240]
        Ordinal0 [0x0048A985+2009477]
        Ordinal0 [0x00493AD1+2046673]
        BaseThreadInitThunk [0x7776FA29+25]
        RtlGetAppContainerNamedObjectPath [0x778B7A7E+286]
        RtlGetAppContainerNamedObjectPath [0x778B7A4E+238]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\new downloads\nft\to upload\bulk-upload-to-opensea-main\upload_captcha.py", line 444, in main_program_loop
    wait_xpath('/html/body/div[5]/div/div/div/div[2]/button/i')
  File "D:\new downloads\nft\to upload\bulk-upload-to-opensea-main\upload_captcha.py", line 254, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Users\RAMI\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x004ED953+2414931]
        Ordinal0 [0x0047F5E1+1963489]
        Ordinal0 [0x0036C6B8+837304]
        Ordinal0 [0x00399500+1021184]
        Ordinal0 [0x0039979B+1021851]
        Ordinal0 [0x003C6502+1205506]
        Ordinal0 [0x003B44E4+1131748]
        Ordinal0 [0x003C4812+1198098]
        Ordinal0 [0x003B42B6+1131190]
        Ordinal0 [0x0038E860+976992]
        Ordinal0 [0x0038F756+980822]
        GetHandleVerifier [0x0075CC62+2510274]
        GetHandleVerifier [0x0074F760+2455744]
        GetHandleVerifier [0x0057EABA+551962]
        GetHandleVerifier [0x0057D916+547446]
        Ordinal0 [0x00485F3B+1990459]
        Ordinal0 [0x0048A898+2009240]
        Ordinal0 [0x0048A985+2009477]
        Ordinal0 [0x00493AD1+2046673]
        BaseThreadInitThunk [0x7776FA29+25]
        RtlGetAppContainerNamedObjectPath [0x778B7A7E+286]
        RtlGetAppContainerNamedObjectPath [0x778B7A4E+238]

**Comment by karakule3dfx** [comment]
please use upload_2captcha V2.py and Don't forget to install the chrome extension. Please use current versions

**Comment by ramidalloul** [comment]
Thanks a lot for the reply.. it's the same error... any other solutions please ?

**Comment by ramidalloul** [comment]
> please use upload_2captcha V2.py and Don't forget to install the chrome extension. Please use current versions

you're awesome man,, now it's working.. the problem was with chrome extension.. I appreciate your kind support

**Comment by karakule3dfx** [comment]
I'm trying to help as much as I can. no problem
