### ISSUE TITLE
Sign lag

### ISSUE THREAD

**Issue by yepyep3** [infotrex/bulk-upload-to-opensea#21]
Awesome fix to the sign issue - thx!  But there is about a 10 second lag at the first sign screen - is there a place to shorten that time?

Thx for the help.

**Comment by infotrex** [comment]
this is min, if i put less than 10 second, the page cannot catch the "sign" button.
mean you cannot complete the listing.

**Comment by yepyep3** [comment]
> this is min, if i put less than 10 second, the page cannot catch the "sign" button.
> mean you cannot complete the listing.

I understand - can you tell me where the variable is where I could try a shorter time because the page is just sitting there for many seconds waiting for a click.  Thanks for your help!

**Comment by infotrex** [comment]
@yepyep3
maybe your internet speed are faster to display the sign page,
you might be use 5 sec to get the page, but other user 6 sec, or 7 sec, 8 sec
so what is is the best number i should put?

**Comment by yepyep3** [comment]
> @yepyep3
> maybe your internet speed are faster to display the sign page,
> you might be use 5 sec to get the page, but other user 6 sec, or 7 sec, 8 sec
> so what is is the best number i should put?

It seems to pop right up for me - can you tell me where it is in the code - I could change the variable & report back what works best.  Thx

**Comment by infotrex** [comment]
contact me if you want to customize this code dedicated for you.
at the moment just free to use version.

**Comment by yepyep3** [comment]
> contact me if you want to customize this code dedicated for you. at the moment just free to use version.

Where is the best place to get in touch

**Comment by infotrex** [comment]
twitter @klvntss

**Comment by stackzwolle** [comment]
hi
first filling data in external link it fill then suddenly it goes typing to fill it again then the description i found it slow have to wait for few seconds. 

and also im still having trouble with complete listing it stop from there . . . ..  here my screen shot

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "<string>", line 351, in main_program_loop
UnboundLocalError: local variable 'login_page' referenced before assignment

thanks a lot

**Comment by infotrex** [comment]
> hi first filling data in external link it fill then suddenly it goes typing to fill it again then the description i found it slow have to wait for few seconds.
> 
> and also im still having trouble with complete listing it stop from there . . . .. here my screen shot
> 
> Traceback (most recent call last): File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\tkinter__init__.py", line 1921, in **call** return self.func(*args) File "", line 351, in main_program_loop UnboundLocalError: local variable 'login_page' referenced before assignment
> 
> thanks a lot

@stackzwolle 
maximize your chrome browser and stop move your mouse while it process running.

**Comment by stackzwolle** [comment]
> > hi first filling data in external link it fill then suddenly it goes typing to fill it again then the description i found it slow have to wait for few seconds.
> > and also im still having trouble with complete listing it stop from there . . . .. here my screen shot
> > Traceback (most recent call last): File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\tkinter__init__.py", line 1921, in **call** return self.func(*args) File "", line 351, in main_program_loop UnboundLocalError: local variable 'login_page' referenced before assignment
> > thanks a lot
> 
> @stackzwolle maximize your chrome browser and stop move your mouse while it process running.

i did everything you say.
after clicking the start button i didnt move anything at all and still did not pass signing and start button back to green.

ps.
i dont have any problem with the old file you called "upload2.py" but doing the properties very slow. maybe u can only edit properties to make fast nothing else :)

thanks a lot

**Comment by infotrex** [comment]
@stackzwolle
Pls select "polygon blockchain" checkbox, if you collection are using polygon.
this will pass the signed.

Prev files i was deleted, just focus one file will easy for my maintenance. :)
TQ

**Comment by stackzwolle** [comment]
> @stackzwolle Pls select "polygon blockchain" checkbox, if you collection are using polygon. this will pass the signed.
> 
> Prev files i was deleted, just focus one file will easy for my maintenance. :) TQ

oh my goodness i usually dont select that 
thank you so much for great help

ps: will you do some option freezing data? :)

**Comment by infotrex** [comment]
@stackzwolle may i know what purpose for freezing data? :)
i cannot get you about your idea.

**Comment by stackzwolle** [comment]
> @stackzwolle may i know what purpose for freezing data? :) i cannot get you about your idea.

oh sorry.
its about the metadata freeze :)

**Comment by yepyep3** [comment]
Hi - is there anyway to reduce the time variable - still sitting on Sign page for almost 10 seconds - thanks!

**Comment by infotrex** [comment]
@yepyep3 after 10s did the program press the sign button? :)

**Comment by yepyep3** [comment]
It did - but that 10 seconds adds hours on a large collection - about 33% longer.  Any way to shorten?  Or for us to change time variable?

Thanks!

**Comment by infotrex** [comment]
support any my nft, i help you change the timer., because that is stable version. :)
but after reduce the timer it will cause to other issue and i won't do any support for that.

**Comment by infotrex** [comment]
twitter me @klvntss

**Comment by yepyep3** [comment]
Done

**Comment by GTavoxD** [comment]
still wondering, how to short the sign time?
