### ISSUE TITLE
i am not able to upload my NFTs after following all the steps :(

### ISSUE THREAD

**Issue by itsrub** [infotrex/bulk-upload-to-opensea#210]
Hi,
I'm Trying to upload my nft collection to opensea but i've reached this result
when i enter (PS F:\bulk-upload-to-opensea-main> python upload_2captcha V2.py)
Saddely this is the result (C:\Users\rehab\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'F:\\bulk-upload-to-opensea-main\\upload_2captcha': [Errno 2] No such file or directory).
What can i do please?
Thanks
![error](https://user-images.githubusercontent.com/107307443/173188057-c0ef00ae-bd28-4bc1-b5d1-2e11de1e89de.png)

**Comment by karakule3dfx** [comment]
you can try this
https://www.youtube.com/watch?v=BqqLKuxtTa4

**Comment by itsrub** [comment]
Hi..
![e1](https://user-images.githubusercontent.com/107307443/173203962-761eba03-aeed-44a5-afd9-54b0a8b37d7c.png)
![e2](https://user-images.githubusercontent.com/107307443/173203964-f52a1559-4a55-43c2-8db0-8ac99bf832c5.png)
 thanks for your support but after uploading the first nft, opensea gave me"Error adding your item: Failed to fetch".

**Comment by karakule3dfx** [comment]
You must manually confirm the first nft
 And still opensea can give this error.
If you download and install the new version chrome extension, it can be a solution to this problem.
[eklenti](https://github.com/infotrex/bulk-upload-to-opensea/tree/main/chrome_extension)

i use google translate, so i hope i can explain correctly

**Comment by Miko950** [comment]
After updating Google to 102.0.50 and updating upload_2captcha_V2, it stopped loading nft and marking properties. The process stops at the fact that it is impossible to create nft without a loaded image
![Снимок экрана 2022-06-12 170203](https://user-images.githubusercontent.com/107356166/173237254-2c04ae9f-cc1d-49dd-8c74-d985645513a8.png)
![Снимок экрана 2022-06-12 170124](https://user-images.githubusercontent.com/107356166/173237259-4c60bb5b-fb8e-4b39-b823-15baef54d2ec.png)
.

**Comment by karakule3dfx** [comment]
This problem usually occurs when the json and image files are not placed or selected correctly.
please read this-> https://github.com/infotrex/bulk-upload-to-opensea/issues/168#issuecomment-1107438310

if everything is correct and it still doesn't work,
please reset the settings in the program interface
