### ISSUE TITLE
Could not upload NFTs

### ISSUE THREAD

**Issue by artnftlab** [infotrex/bulk-upload-to-opensea#211]
Hello, I was following all steps to upload nft. But, upload not started automatically. Please help.

PS C:\Users\tapanjyoti\Desktop\bulk-upload-to-opensea-main> python upload.py
Start creating NFT Crazy_Ants #1
number  1
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\tapanjyoti\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\tapanjyoti\Desktop\bulk-upload-to-opensea-main\upload.py", line 258, in main_program_loop
    wait_xpath('//*[@id="media"]')
  File "C:\Users\tapanjyoti\Desktop\bulk-upload-to-opensea-main\upload.py", line 244, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Users\tapanjyoti\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x0034D953+2414931]
        Ordinal0 [0x002DF5E1+1963489]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

![nfts not upload](https://user-images.githubusercontent.com/107474708/173559020-9bb36e76-6621-4699-a051-3996c64c4d61.jpg)

**Comment by karakule3dfx** [comment]
please use [upload_2captcha_V2.py](https://github.com/infotrex/bulk-upload-to-opensea/blob/main/upload_2captcha_V2.py)

And

If you can take a screenshot of the program with the settings , I can examine it in more detail.

**Comment by artnftlab** [comment]
Thanks for your assistance. 

I already used upload_2captcha_V2.py. But, NFTs are not able to upload, Just collection page got refreshed. I attached screenshots of the program.
![1](https://user-images.githubusercontent.com/107474708/173808811-4cf0c6fc-3353-4a01-86f6-dcebe708feab.png)
![2](https://user-images.githubusercontent.com/107474708/173808842-297b2ff9-7c0a-455f-9ac4-6784f9fa61f4.png)

**Comment by karakule3dfx** [comment]
@vermavenu11 Please Read This #203 

A problem can have multiple causes and I can't offer the right solution without knowing your problem.

**Comment by artnftlab** [comment]
@karakule3dfx Now, previous error has been solved. But, when I pressed start button, got unlimited refresh. NFTs are not uploading, just page got refresh again and again.
 
I changed the following line number 20 to 30. But same error was coming.

WebDriverWait(driver, 30).until(ExpectedConditions.presence_of_element_located((By.CSS_SELECTOR, "button[aria-label='Add properties']" )))
![unlimited refresh](https://user-images.githubusercontent.com/107474708/174158012-61ecf285-37d7-4843-81af-a15e812b1ca3.jpg)

**Comment by artnftlab** [comment]
I changed the previous code of  "upload.py" and paste new codes from [upload_2captcha_V2.py](https://github.com/infotrex/bulk-upload-to-opensea/blob/main/upload_2captcha_V2.py)

only page got refresh multiple times.

![1](https://user-images.githubusercontent.com/107474708/174271919-32f32948-aeb8-4b6d-8cbc-57ab8230ae29.JPG)
![2](https://user-images.githubusercontent.com/107474708/174271933-4f40dffe-1328-4b02-8f92-aea91bb001ce.png)

**Comment by karakule3dfx** [comment]
if crazy-ants-1 is the name of your collection please use this link

https://opensea.io/collection/crazy-ants-1/assets/create

The link you wrote should be exactly the link that opens the nft addition screen to your collection
![2022-06-17_14-42-01](https://user-images.githubusercontent.com/103366046/174292007-7f9b853d-8610-4195-8c8d-a5db33d30f44.png)
.

**Comment by artnftlab** [comment]
Thank you so much for you support. My problem has been solved. You are life saver.

Thanks again.
