### ISSUE TITLE
unable to sell

### ISSUE THREAD

**Issue by hamhocks** [infotrex/bulk-upload-to-opensea#212]
The first part works fine but I get error when listing to sell and everything goes manual. Here is the error:
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:mycomputer\Desktop\bulk-upload-to-opensea-main\upload_captcha.py", line 439, in main_program_loop
    wait_xpath('/html/body/div[6]/div/div/div/div[2]/button/i')
  File "C:mycomputer\Desktop\bulk-upload-to-opensea-main\upload_captcha.py", line 254, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x0030D953+2414931]
        Ordinal0 [0x0029F5E1+1963489]
        Ordinal0 [0x0018C6B8+837304]
        Ordinal0 [0x001B9500+1021184]
        Ordinal0 [0x001B979B+1021851]
        Ordinal0 [0x001E6502+1205506]
        Ordinal0 [0x001D44E4+1131748]
        Ordinal0 [0x001E4812+1198098]
        Ordinal0 [0x001D42B6+1131190]
        Ordinal0 [0x001AE860+976992]
        Ordinal0 [0x001AF756+980822]
        GetHandleVerifier [0x0057CC62+2510274]
        GetHandleVerifier [0x0056F760+2455744]
        GetHandleVerifier [0x0039EABA+551962]
        GetHandleVerifier [0x0039D916+547446]
        Ordinal0 [0x002A5F3B+1990459]
        Ordinal0 [0x002AA898+2009240]
        Ordinal0 [0x002AA985+2009477]
        Ordinal0 [0x002B3AD1+2046673]
        BaseThreadInitThunk [0x76F66739+25]
        RtlGetFullPathName_UEx [0x77A78FEF+1215]
        RtlGetFullPathName_UEx [0x77A78FBD+1165]
        (No symbol) [0x00000000]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:mycomputer\Desktop\bulk-upload-to-opensea-main\upload_captcha.py", line 444, in main_program_loop
    wait_xpath('/html/body/div[5]/div/div/div/div[2]/button/i')
  File "C:mycomputer\Desktop\bulk-upload-to-opensea-main\upload_captcha.py", line 254, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x0030D953+2414931]
        Ordinal0 [0x0029F5E1+1963489]
        Ordinal0 [0x0018C6B8+837304]
        Ordinal0 [0x001B9500+1021184]
        Ordinal0 [0x001B979B+1021851]
        Ordinal0 [0x001E6502+1205506]
        Ordinal0 [0x001D44E4+1131748]
        Ordinal0 [0x001E4812+1198098]
        Ordinal0 [0x001D42B6+1131190]
        Ordinal0 [0x001AE860+976992]
        Ordinal0 [0x001AF756+980822]
        GetHandleVerifier [0x0057CC62+2510274]
        GetHandleVerifier [0x0056F760+2455744]
        GetHandleVerifier [0x0039EABA+551962]
        GetHandleVerifier [0x0039D916+547446]
        Ordinal0 [0x002A5F3B+1990459]
        Ordinal0 [0x002AA898+2009240]
        Ordinal0 [0x002AA985+2009477]
        Ordinal0 [0x002B3AD1+2046673]
        BaseThreadInitThunk [0x76F66739+25]
        RtlGetFullPathName_UEx [0x77A78FEF+1215]
        RtlGetFullPathName_UEx [0x77A78FBD+1165]
        (No symbol) [0x00000000]

**Comment by karakule3dfx** [comment]
please use recent version [upload_2captcha_V2.py](https://github.com/infotrex/bulk-upload-to-opensea/blob/main/upload_2captcha_V2.py)

**Comment by hamhocks** [comment]
Success, working again thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by karakule3dfx** [comment]
I'm trying to help as much as I can. no problem

**Comment by secreth123** [comment]
Hello I have a problem with nft mint. After passing the captcha stage, the operation stops. what must I do

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\bulk-upload-to-opensea-main\upload_captcha.py", line 439, in main_program_loop
    wait_xpath('/html/body/div[6]/div/div/div/div[2]/button/i')
  File "C:\Users\Administrator\Downloads\bulk-upload-to-opensea-main\upload_captcha.py", line 254, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 87, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x015ED953+2414931]
        Ordinal0 [0x0157F5E1+1963489]
        Ordinal0 [0x0146C6B8+837304]
        Ordinal0 [0x01499500+1021184]
        Ordinal0 [0x0149979B+1021851]
        Ordinal0 [0x014C6502+1205506]
        Ordinal0 [0x014B44E4+1131748]
        Ordinal0 [0x014C4812+1198098]
        Ordinal0 [0x014B42B6+1131190]
        Ordinal0 [0x0148E860+976992]
        Ordinal0 [0x0148F756+980822]
        GetHandleVerifier [0x0185CC62+2510274]
        GetHandleVerifier [0x0184F760+2455744]
        GetHandleVerifier [0x0167EABA+551962]
        GetHandleVerifier [0x0167D916+547446]
        Ordinal0 [0x01585F3B+1990459]
        Ordinal0 [0x0158A898+2009240]
        Ordinal0 [0x0158A985+2009477]
        Ordinal0 [0x01593AD1+2046673]
        BaseThreadInitThunk [0x771262C4+36]
        RtlSubscribeWnfStateChangeNotification [0x778D0609+1081]
        RtlSubscribeWnfStateChangeNotification [0x778D05D4+1028]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Administrator\Downloads\bulk-upload-to-opensea-main\upload_captcha.py", line 444, in main_program_loop
    wait_xpath('/html/body/div[5]/div/div/div/div[2]/button/i')
  File "C:\Users\Administrator\Downloads\bulk-upload-to-opensea-main\upload_captcha.py", line 254, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 87, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x015ED953+2414931]
        Ordinal0 [0x0157F5E1+1963489]
        Ordinal0 [0x0146C6B8+837304]
        Ordinal0 [0x01499500+1021184]
        Ordinal0 [0x0149979B+1021851]
        Ordinal0 [0x014C6502+1205506]
        Ordinal0 [0x014B44E4+1131748]
        Ordinal0 [0x014C4812+1198098]
        Ordinal0 [0x014B42B6+1131190]
        Ordinal0 [0x0148E860+976992]
        Ordinal0 [0x0148F756+980822]
        GetHandleVerifier [0x0185CC62+2510274]
        GetHandleVerifier [0x0184F760+2455744]
        GetHandleVerifier [0x0167EABA+551962]
        GetHandleVerifier [0x0167D916+547446]
        Ordinal0 [0x01585F3B+1990459]
        Ordinal0 [0x0158A898+2009240]
        Ordinal0 [0x0158A985+2009477]
        Ordinal0 [0x01593AD1+2046673]
        BaseThreadInitThunk [0x771262C4+36]
        RtlSubscribeWnfStateChangeNotification [0x778D0609+1081]
        RtlSubscribeWnfStateChangeNotification [0x778D05D4+1028]
