### ISSUE TITLE
Unlimited refresh

### ISSUE THREAD

**Issue by zerozin-kang** [infotrex/bulk-upload-to-opensea#213]
![image](https://user-images.githubusercontent.com/67829322/173962688-b9df7531-7120-49bb-b4f8-a41e401efb97.png)

I have a question.
When I press the start button using upload_2captcha_V2.py, infinite refresh is executed.
Of course, NFT items are not uploaded.
What's the problem?
--
number  6
Refresh
Refresh
Refresh
Refresh
Refresh
Refresh
Refresh
Refresh
Refresh
Refresh
Refresh

**Comment by karakule3dfx** [comment]
It detects that the add properties button does not allow interaction, so it refreshes the page.

you can find thsi line
`WebDriverWait(driver, 20).until(ExpectedConditions.presence_of_element_located((By.CSS_SELECTOR, "button[aria-label='Add properties']" )))`

and You could try replacing 20 with a higher number. so you will give the button more time to wait

**Comment by TalhaElaine** [comment]
@karakule3dfx  i replaced 20 with 60 but still i face  same issue
