### ISSUE TITLE
only refreshing browser

### ISSUE THREAD

**Issue by TalhaElaine** [infotrex/bulk-upload-to-opensea#214]
![Screenshot (1)](https://user-images.githubusercontent.com/107635833/174107082-7cda5c6c-c4d7-4187-b927-858bc6ac3080.png)

**Comment by karakule3dfx** [comment]
you typed the collection link wrong ...

collection link should be like this
https://www.opensea.io/collection/yourcollectionsname/assets/create

please fix and try again

**Comment by karakule3dfx** [comment]
please take a screenshot and send it again

**Comment by zerozin-kang** [comment]
My issue is the same. It only refreshes.

**Comment by karakule3dfx** [comment]
@zerozin-kang @TalhaElaine please take a screenshot of the program and send it

**Comment by karakule3dfx** [comment]
@zerozin-kang
are you using the link like this please provide feedback
https://opensea.io/collection/your-collections-name/assets/create

**Comment by zerozin-kang** [comment]
> 

I solved it. Thank you.!!!
