### ISSUE TITLE
new chromedriver not compatible

### ISSUE THREAD

**Issue by hamhocks** [infotrex/bulk-upload-to-opensea#216]
Hi the new chromedriver update isn't working with the current version in the program. I updated to the new driver but it's not working.
py:527: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  capt_btn = driver.find_element_by_xpath("//button[@id='solver-button']")     
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\slots\OneDrive\Desktop\bulk-upload-to-opensea-main\upload_2captcha_V2.py", line 521, in main_program_loop
    wait_xpath('/html/body/div[1]/div/div[3]/div[2]/div[1]/div[1]/div[4]')     
  File "C:\Users\slots\OneDrive\Desktop\bulk-upload-to-opensea-main\upload_2captcha_V2.py", line 265, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x010B6463+2188387]
        Ordinal0 [0x0104E461+1762401]
        Ordinal0 [0x00F63D78+802168]
        Ordinal0 [0x00F91880+989312]
        Ordinal0 [0x00F91B1B+989979]
        Ordinal0 [0x00FBE912+1173778]
        Ordinal0 [0x00FAC824+1099812]
        Ordinal0 [0x00FBCC22+1166370]
        Ordinal0 [0x00FAC5F6+1099254]
        Ordinal0 [0x00F86BE0+945120]
        Ordinal0 [0x00F87AD6+948950]
        GetHandleVerifier [0x013571F2+2712546]
        GetHandleVerifier [0x0134886D+2652765]
        GetHandleVerifier [0x0114002A+520730]
        GetHandleVerifier [0x0113EE06+516086]
        Ordinal0 [0x0105468B+1787531]
        Ordinal0 [0x01058E88+1805960]
        Ordinal0 [0x01058F75+1806197]
        Ordinal0 [0x01061DF1+1842673]
        BaseThreadInitThunk [0x758E6739+25]
        RtlGetFullPathName_UEx [0x77738FEF+1215]
        RtlGetFullPathName_UEx [0x77738FBD+1165]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\slots\OneDrive\Desktop\bulk-upload-to-opensea-main\upload_2captcha_V2.py", line 527, in main_program_loop
    capt_btn = driver.find_element_by_xpath("//button[@id='solver-button']")   
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 514, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[@id='solver-button']"}
  (Session info: chrome=103.0.5060.53)
Stacktrace:
Backtrace:
        Ordinal0 [0x010B6463+2188387]
        Ordinal0 [0x0104E461+1762401]
        Ordinal0 [0x00F63D78+802168]
        Ordinal0 [0x00F91880+989312]
        Ordinal0 [0x00F91B1B+989979]
        Ordinal0 [0x00FBE912+1173778]
        Ordinal0 [0x00FAC824+1099812]
        Ordinal0 [0x00FBCC22+1166370]
        Ordinal0 [0x00FAC5F6+1099254]
        Ordinal0 [0x00F86BE0+945120]
        Ordinal0 [0x00F87AD6+948950]
        GetHandleVerifier [0x013571F2+2712546]
        GetHandleVerifier [0x0134886D+2652765]
        GetHandleVerifier [0x0114002A+520730]
        GetHandleVerifier [0x0113EE06+516086]
        Ordinal0 [0x0105468B+1787531]
        Ordinal0 [0x01058E88+1805960]
        Ordinal0 [0x01058F75+1806197]
        Ordinal0 [0x01061DF1+1842673]
        BaseThreadInitThunk [0x758E6739+25]
        RtlGetFullPathName_UEx [0x77738FEF+1215]
        RtlGetFullPathName_UEx [0x77738FBD+1165]

**Comment by karakule3dfx** [comment]
Can't find button created by "Buster Captcha" plugin.
Is the plugin installed and active?

**Comment by hamhocks** [comment]
It is installed but when I go to click it nothing happens.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by hamhocks** [comment]
It’s working now.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
