### ISSUE TITLE
New bug?

### ISSUE THREAD

**Issue by voidheart2** [infotrex/bulk-upload-to-opensea#222]
code stops at the time when information is being taken from the JSONs. Found it on eth version. Thank you!
![image](https://user-images.githubusercontent.com/108201894/175794946-5eb58b13-8604-42b4-b95e-96f62873cb96.png)

**Comment by levianlp** [comment]
have a some problem here

**Comment by levianlp** [comment]
for me, this bug is showing when auto inputing properties, try it about 15 times, still the same

**Comment by karakule3dfx** [comment]
please read this #203

**Comment by levianlp** [comment]
I'll try it again today, and if i encounter the same problem i will make proper issues, thank you @karakule3dfx
