### ISSUE TITLE
Stops In The Middle (Tried Everything)

### ISSUE THREAD

**Issue by ElnarC** [infotrex/bulk-upload-to-opensea#228]
![image](https://user-images.githubusercontent.com/106318748/176510348-9c1299b2-bfc0-42aa-adfa-78ca862f166c.png)

Alrighty, let me tell a little backstory ... 

Pretty much I spent hours trying and fixing it, with my friends, by myself, changing code, and many other things... But all the time it goes thru characteristics, and stops, and after that, program stops running the script and says the following: 

"selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="__next"]/div[1]/main/div/div/section/div[2]/form/div/div[1]/span/button"}
  (Session info: chrome=102.0.5005.63)"

Is there any fix to that?

Thank you,

Sincerely Elnar

**Comment by karakule3dfx** [comment]
@SMARTYBOIIII I guess you gave the wrong address to the program. 
I can help if you can take a screenshot of the program interface with your settings made.

**Comment by ElnarC** [comment]
Hello

> @SMARTYBOIIII I guess you gave the wrong address to the program. I can help if you can take a screenshot of the program interface with your settings made.

Sorry for late response, here: 
![image](https://user-images.githubusercontent.com/106318748/176969967-569cee1a-2942-44c5-b49d-855b33b1536b.png)

**Comment by karakule3dfx** [comment]
opensea collection link : https://www.opensea.io/collection/**yourcollectionsname**/assets/create

where is your "yourcollectionsname" ?

**Comment by ElnarC** [comment]
For some reason when i did put it, it didnt find collection at all...

**Comment by ElnarC** [comment]
I will try again though... thanks a lot! But i am not going to close conversation for now, just in case it is not works...

**Comment by SMARTYBOIIII** [comment]
> opensea collection link : https://www.opensea.io/collection/**yourcollectionsname**/assets/create
> 
> where is your "yourcollectionsname" ?

So, here I tested what you were saying, 
![image](https://user-images.githubusercontent.com/106318748/177014423-56d42698-1c01-4a4a-ac5e-c9872a0933dc.png)


Here is what happens, and yes, I did put collection name right, here is link to check: https://opensea.io/collection/foodydonuty

**Comment by ElnarC** [comment]
Oh my god, for such a small mistake, I spent so much time, thank you a LOT!
