### ISSUE TITLE
Error while filling properties 

### ISSUE THREAD

**Issue by simtechnos** [infotrex/bulk-upload-to-opensea#23]
<string>:244: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:249: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:253: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:257: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:268: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "<string>", line 277, in main_program_loop
KeyError: 'attributes'

**Comment by infotrex** [comment]
@simtechnos 
do your .json file include "attributes" this key value?
pls refer my repo json folder file structure.

**Comment by simtechnos** [comment]
no mine one says properties, so shall I replace it to be attributes ?

**Comment by infotrex** [comment]
@simtechnos 
yes, replace your own properties attributes.

**Comment by simtechnos** [comment]
thanks got it.
