### ISSUE TITLE
It worked fine when loading on eth but this is the error when i try to do it on polygon

### ISSUE THREAD

**Issue by Arno-rgb** [infotrex/bulk-upload-to-opensea#230]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\arnom\Downloads\bulk-upload-to-opensea-main\upload_2captcha_V2.py", line 459, in main_program_loop
    create = driver.find_element(By.XPATH, '//*[@id="__next"]/div[1]/main/div/div/section/div[2]/form/div/div[1]/span/button')
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 857, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="__next"]/div[1]/main/div/div/section/div[2]/form/div/div[1]/span/button"}
  (Session info: chrome=103.0.5060.66)
Stacktrace:
Backtrace:
        Ordinal0 [0x0106D953+2414931]
        Ordinal0 [0x00FFF5E1+1963489]
        Ordinal0 [0x00EEC6B8+837304]
        Ordinal0 [0x00F19500+1021184]
        Ordinal0 [0x00F1979B+1021851]
        Ordinal0 [0x00F46502+1205506]
        Ordinal0 [0x00F344E4+1131748]
        Ordinal0 [0x00F44812+1198098]
        Ordinal0 [0x00F342B6+1131190]
        Ordinal0 [0x00F0E860+976992]
        Ordinal0 [0x00F0F756+980822]
        GetHandleVerifier [0x012DCC62+2510274]
        GetHandleVerifier [0x012CF760+2455744]
        GetHandleVerifier [0x010FEABA+551962]
        GetHandleVerifier [0x010FD916+547446]
        Ordinal0 [0x01005F3B+1990459]
        Ordinal0 [0x0100A898+2009240]
        Ordinal0 [0x0100A985+2009477]
        Ordinal0 [0x01013AD1+2046673]
        BaseThreadInitThunk [0x7651FA29+25]
        RtlGetAppContainerNamedObjectPath [0x770B7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x770B7A6E+238]

**Comment by karakule3dfx** [comment]
This problem occurs because of the chrome version. you can try to downgrade or use the upper beta version.

You can take a screenshot of the program interface and we can check your settings.
