### ISSUE TITLE
Metadata .json files are not being recognized.

### ISSUE THREAD

**Issue by Kivyster** [infotrex/bulk-upload-to-opensea#232]
I'm doing the step by step as in the video, but the command does not recognize the .json folder in "src". I'm stuck on this part right now, could anyone help me?

**Comment by karakule3dfx** [comment]
please read this #203 . I will try to help as much as I can

**Comment by Kivyster** [comment]
my error is simple, in the test phase the .json files were being recognized, in the posting phase it was no longer, did you update something in the code?

**Comment by karakule3dfx** [comment]
You can see when the files are updated from the code screen on github.
#203 have you read this?
