### ISSUE TITLE
DOES NOT WORK

### ISSUE THREAD

**Issue by MatHatter** [infotrex/bulk-upload-to-opensea#233]
First of all, you should answer people's questions on here and on Youtube instead of asking everyone for coffee money. Second, this does not bypass the recaptcha part.

**Comment by karakule3dfx** [comment]
@MatHatter  Please read this #203 
what is your problem?

**Comment by MatHatter** [comment]
Sorry, I was frustrated, because the instructions are not clear (what in the world in scraping?) and tbh the Recaptcha part does not work, but the Buster part does, but the user has to download both and pick Buster and it does not save the form when Buster is selected. Due to my appreciation, I actually might buy you coffee, but tbh it also frustrates me when I see tons of unanswered questions.
