### ISSUE TITLE
I don't know why it didn't work

### ISSUE THREAD

**Issue by lsy0202** [infotrex/bulk-upload-to-opensea#242]
![image](https://user-images.githubusercontent.com/111872411/186585937-b776c738-e106-4244-8be9-75ff5b000ed7.png)
![image](https://user-images.githubusercontent.com/111872411/186587033-4844bcb7-a183-419f-a141-79ca72043fff.png)

I think I followed all the instructions well. I I pressed the start button, but it didn't work. Plz help

**Comment by Youn-sik** [comment]
I think we have same error.
My error log is
"selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at localhost:8989
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 104.0.5112.102"

**Comment by lsy0202** [comment]
Yes. I solved the problem by downloading new Chrome version. Thanks!!
