### ISSUE TITLE
Problem With The Amount Of Nft Uploaded

### ISSUE THREAD

**Issue by Berseck20** [infotrex/bulk-upload-to-opensea#25]
Hello, I would like to know how many nfts can be uploaded at once?

The problem I am having is that I want to upload 10k nfts but I upload 30 - 50 at a time and then I get this in opensea:
![Sin título](https://user-images.githubusercontent.com/95880481/149678722-8daf0a9f-3924-45fa-b344-4ec585144990.png)

**Comment by infotrex** [comment]
i believe that is opensea website issue.
if you can upload continuously that mean the tool are working.

**Comment by ZaryImortal** [comment]
I disabled "complete listing"

**Comment by Berseck20** [comment]
it could be, but then I have to hand sell 9000 nfts, it doesn't make much sense.

**Comment by infotrex** [comment]
:)
you upload 9999 using my tool.
the last piece nft you manually upload it.
total is 10k
