### ISSUE TITLE
It stops working in Floor price

### ISSUE THREAD

**Issue by LucassToledo** [infotrex/bulk-upload-to-opensea#257]
It stops working (I think) because it changed the buttons where the price was.

Before there were two buttons and now only floor price appears. At that point it gets stuck and does not go beyond placing the price.

**Comment by LucassToledo** [comment]
Terminal:
Exception in Tkinter callback
Traceback (most recent call last):
File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\tkinter_init_.py", line 1921, in call
return self.func(args)
File "C:\Users\Usuario\Desktop\Generador de NFT\NFTs-Upload-to-OpenSea-main\bulk-upload-to-opensea-main\upload_2captcha_V2.py", line 616, in main_program_loop
wait_xpath('//[https://github.com/ROLE="dialog"]/div[1]/div[1]/div/input')
File "C:\Users\Usuario\Desktop\Generador de NFT\NFTs-Upload-to-OpenSea-main\bulk-upload-to-opensea-main\upload_2captcha_V2.py", line 265, in wait_xpath
wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
Ordinal0 [0x004FACD3+2075859]
Ordinal0 [0x0048EE61+1633889]
Ordinal0 [0x0038B7BD+571325]
Ordinal0 [0x003BAC2F+764975]
Ordinal0 [0x003BAE1B+765467]
Ordinal0 [0x003ED0F2+970994]
Ordinal0 [0x003D7364+881508]
Ordinal0 [0x003EB56A+963946]
Ordinal0 [0x003D7136+880950]
Ordinal0 [0x003AFEFD+720637]
Ordinal0 [0x003B0F3F+724799]
GetHandleVerifier [0x007AEED2+2769538]
GetHandleVerifier [0x007A0D95+2711877]
GetHandleVerifier [0x0058A03A+521194]
GetHandleVerifier [0x00588DA0+516432]
Ordinal0 [0x0049682C+1665068]
Ordinal0 [0x0049B128+1683752]
Ordinal0 [0x0049B215+1683989]
Ordinal0 [0x004A6484+1729668]
BaseThreadInitThunk [0x7613FEF9+25]
RtlGetAppContainerNamedObjectPath [0x77127BBE+286]
RtlGetAppContainerNamedObjectPath [0x77127B8E+238]

**Comment by Friday12322** [comment]
https://github.com/infotrex/bulk-upload-to-opensea/issues/245#issuecomment-1298027954 Look here

As well as https://github.com/infotrex/bulk-upload-to-opensea/issues/245#issuecomment-1299448574

After that, the script worked for me, but recently for some reason it stopped working when I select set duration
I only know that the error is somewhere in the 616 line of code

If it works, please write how you could fix the error

**Comment by LucassToledo** [comment]
I was reviewing the problem and I noticed that the error does not come from the price selection but from pressing the drop-down button for the months.

If I touch it manually, the program continues to run.
I am studying a bit of selenium to understand how or why the button is not being clicked.

When I solve it I'll comment.

**Comment by Friday12322** [comment]
> Я просматривал проблему и заметил, что ошибка возникает не из-за выбора цены, а из-за нажатия раскрывающейся кнопки для месяцев.
> 
> Если я коснусь его вручную, программа продолжит работу. Я немного изучаю селен, чтобы понять, как и почему кнопка не нажимается.
> 
> Когда решу, отпишусь.


I will be very grateful

**Comment by pythonboi11** [comment]
> I was reviewing the problem and I noticed that the error does not come from the price selection but from pressing the drop-down button for the months.
> 
> If I touch it manually, the program continues to run. I am studying a bit of selenium to understand how or why the button is not being clicked.
> 
> When I solve it I'll comment.

Please do!

**Comment by LucassToledo** [comment]
I was able to solve it by adding this code before line 616
```
oprimirDesplegable = driver.find_element(By.ID, "duration")
oprimirDesplegable.click()
```

What it does is press the drop-down button for the months that was not being pressed, it worked perfectly afterwards.

**Comment by pythonboi11** [comment]
Thank you very much for helping us out!
