### ISSUE TITLE
Stop short at the complete listing button with error

### ISSUE THREAD

**Issue by adityabanka93** [infotrex/bulk-upload-to-opensea#26]
It gives this error
</button> is not clickable at point (239, 713). Other element would receive the click:

I worked well till about 450 uploads and then this happened

**Comment by infotrex** [comment]
just restart the tool.
sometimes the opensea or internet cause unpredictable issue.

**Comment by adityabanka93** [comment]
Done that multiple times, deleted the entire script, and put it in again, still the same error.
Actually point 239,713 ... it has actually become unclickable. How can we change it to say 239, 719?

**Comment by infotrex** [comment]
i not get any feedback from other users about this issue "point 239,713".
you try to maximize chrome browser while running and don't moving your mouse.
if this still not resolve your issue than i not sure what is the problem behind.

TQ

**Comment by adityabanka93** [comment]
Look at this pic, It's actually not clickable here
![Untitled](https://user-images.githubusercontent.com/97869539/149717063-b9779352-1e20-4d84-be0d-28811d4419c3.png)

I removed the bookmark bar from chrome the error point changed to 239, 729

**Comment by infotrex** [comment]
in my script don't have any "729" this kind of point or script, all depend the xpath and id to click.
are  you using gaming mouse or laser mouse?
can try to disabled it.

**Comment by adityabanka93** [comment]
Its a normal laser mouse, DIsconnected it as u suggested
Still the same error

**Comment by infotrex** [comment]
or try set your windows display resolution to below 1600px

**Comment by adityabanka93** [comment]
This made it work, thank you.
