### ISSUE TITLE
Changing listing duration?

### ISSUE THREAD

**Issue by paymon23** [infotrex/bulk-upload-to-opensea#28]
Firstly I want to start off by saying thank you for making an incredible tool! 

I was wondering if it's possible to change the listing duration and would it be possible to have a feature that would also bulk/automatic relisting of everything that's left unsold? 

I'm thinking this will be a desirable feature for a lot of people.

Thanks again!!

**Comment by infotrex** [comment]
if change nft duration before create will possible.
for existing nft want to change duration or any update it was complicated.

**Comment by paymon23** [comment]
What do I change to tweak the duration? :)

**Comment by infotrex** [comment]
might be the next new version
but not at the moment.
