### ISSUE TITLE
[Question] Trust Wallet

### ISSUE THREAD

**Issue by Drjacky** [infotrex/bulk-upload-to-opensea#3]
Does it work with TrustWallet?

**Comment by infotrex** [comment]
hi,
current the application tested on MetaMask.
i not sure it can run TrustWallet or not.
TQ

**Comment by Drjacky** [comment]
Any chance to add Trust Wallet?

**Comment by infotrex** [comment]
Now we more focus to majority user at the moment.
We will add your idea in my list.

TQ
