### ISSUE TITLE
Getting SSL_CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by abhijeetdesai14** [infotrex/bulk-upload-to-opensea#30]
Trying this on windows getting certifcate has expired. pip install requirements have passed successfully and verified that certfi folder is present in site-packages. 
Is there any additional step to be done?
Should we add anything int cacert.pem file?

**Comment by infotrex** [comment]
try to use this file
upload_fixedSSL.py

**Comment by abhijeetdesai14** [comment]
It is working perfectly fine. Thank you!
