### ISSUE TITLE
Image Not Loading

### ISSUE THREAD

**Issue by Arpitxoxoo** [infotrex/bulk-upload-to-opensea#32]
Hello there , my image is not loading on opensea some blob error coming there... please help me  out i mreally thankful of yours ! 
<img width="265" alt="Screenshot 2022-01-21 011515" src="https://user-images.githubusercontent.com/98122795/150411173-87decac1-a953-45ac-b570-8d41e7e520d3.png">

**Comment by infotrex** [comment]
@Arpitxoxoo 
if image not load, possible not found the file / invalid filename / wrong "scr" folder.

**Comment by Arpitxoxoo** [comment]
I followed your video  step by step but still i got this error ! can you please give me some solution regarding this its really helpful 😔

**Comment by infotrex** [comment]
can you screenshot tool setting.
and what is your file format and filename.?

**Comment by infotrex** [comment]
@Arpitxoxoo twitter me @klvntss

**Comment by Arpitxoxoo** [comment]
okh !

**Comment by hunekune** [comment]
How did you fix this problem? I have the same issue.

**Comment by infotrex** [comment]
@hunekune
if the image cannot select, mostly is invalid folder path, or image filename format.
