### ISSUE TITLE
Set this item as explicit and sensitive content 

### ISSUE THREAD

**Issue by goodoffer** [infotrex/bulk-upload-to-opensea#33]
Please add the ability to tick this moment when uploading the NFTs

Explicit & Sensitive Content (YES)
Set this item as explicit and sensitive content 
<img width="832" alt="Screenshot 2022-01-21 at 1 21 34 pm" src="https://user-images.githubusercontent.com/95210401/150510861-45ea71ab-806c-49eb-a1a4-6d3de60716aa.png">

**Comment by infotrex** [comment]
@goodoffer will consider that.
but not at the moment.
