### ISSUE TITLE
Stop working after uploading some NFTs

### ISSUE THREAD

**Issue by HiimNaruto** [infotrex/bulk-upload-to-opensea#34]
Hi, I was trying to upload 500 NFTs. the process stopped after uploading 11 NFTs. then it stopped at 44. meta mask open and it will not continue the process. I need to click on sign in manually. after that Need to start uploading again. can you please tell me how to fix it? 
Kind regards

**Comment by jrcmadushanka** [comment]
Same for me 😶

**Comment by infotrex** [comment]
@HiimNaruto @jrcmadushanka 
sometimes will be like that due to unexpected issue like opensea or metamask slow.
