### ISSUE TITLE
cant find chrome

### ISSUE THREAD

**Issue by varando89** [infotrex/bulk-upload-to-opensea#35]
when I press "open in chrome browser" it writes that can't find chrome, check the name and repeat. how can I fix it? please help
I work on windows 7 and replaced the chromedriver file but it still doesn't work

**Comment by infotrex** [comment]
@varando89 you try to use original chromedriver.ex  from my github.

**Comment by varando89** [comment]
> @varando89 you try to use original chromedriver.ex from my github.

my chrome version is 98.0.4758.81  but there is no this version on chromium.org. where to find it?

**Comment by varando89** [comment]
@infotrex  my chrome version is 98.0.4758.81 but there is no this version on chromium.org. where to find it?

**Comment by infotrex** [comment]
@varando89  try download similar version
[ust ](https://chromedriver.storage.googleapis.com/index.html?path=98.0.4758.80/)
