### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by maduranga001** [infotrex/bulk-upload-to-opensea#38]
Hi

I am getting this error when I am trying to run the code.

<string>:211: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
<string>:211: DeprecationWarning: use options instead of chrome_options

How can I fix this?Please, help.

Thank you!

**Comment by infotrex** [comment]
try move that folder to another directory.
might be folder permission issue.

**Comment by maduranga001** [comment]
Thank you for the reply.

That folder means, which folder?

I moved your Python project to the main D:\ Directory and gave full read-write permission. Still, I am having the same issue.

Please, can you help me?
(I am using your latest version package with upload18.py)

PS D:\bulknew> py upload18.py
<string>:230: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
<string>:230: DeprecationWarning: use options instead of chrome_options

The browser is opening. But It stops here.

Then I am getting this error set and then stops the program.

Start creating NFT Digital #1
number  1
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "<string>", line 262, in main_program_loop
  File "<string>", line 248, in wait_xpath
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x01586903+2517251]
        Ordinal0 [0x0151F8E1+2095329]
        Ordinal0 [0x01422848+1058888]
        Ordinal0 [0x0144D448+1233992]
        Ordinal0 [0x0144D63B+1234491]
        Ordinal0 [0x01477812+1406994]
        Ordinal0 [0x0146650A+1336586]
        Ordinal0 [0x01475BBF+1399743]
        Ordinal0 [0x0146639B+1336219]
        Ordinal0 [0x014427A7+1189799]
        Ordinal0 [0x01443609+1193481]
        GetHandleVerifier [0x01715904+1577972]
        GetHandleVerifier [0x017C0B97+2279047]
        GetHandleVerifier [0x01616D09+534521]
        GetHandleVerifier [0x01615DB9+530601]
        Ordinal0 [0x01524FF9+2117625]
        Ordinal0 [0x015298A8+2136232]
        Ordinal0 [0x015299E2+2136546]
        Ordinal0 [0x01533541+2176321]
        BaseThreadInitThunk [0x7556344D+18]
        RtlInitializeExceptionChain [0x77609802+99]
        RtlInitializeExceptionChain [0x776097D5+54]


Please, help.
Thank you!

**Comment by infotrex** [comment]
@maduranga001  contact me twitter @klvntss

**Comment by maduranga001** [comment]
I added you to Twitter. But it is not allowing me to send messages to you.
