### ISSUE TITLE
Hangs on "create asset" page & Timeout before creating first NFT. Photo is also "Broken" Image.

### ISSUE THREAD

**Issue by JBDsolutions** [infotrex/bulk-upload-to-opensea#40]
1. Extremely long load times in the chrome instance that the program opens. 
2. Will not create the NFT, program stops after entering "Description" field 

ERRORS: 
```
<string>:255: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead

 File "C:\...Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "<string>", line 314, in main_program_loop
  File "<string>", line 227, in wait_xpath
  File "C:\...\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until    
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

```

**Comment by infotrex** [comment]
@JBDsolutions 
Pls check your field input. all string collect, and select "src" folder.

**Comment by Amalsaju** [comment]
Same issue for me! :(

**Comment by Amalsaju** [comment]
> check your field input. all string collect, and select "src" folder.

Did not understand this.

The thing is the program worked flawlessly for me for some time. Then today it isn't working. I upload about 1500 nfts every night. And only change the start and end numbers each day. Now it just crashes when trying to create an nft. Don't understand why. :(

**Comment by Amalsaju** [comment]
Sorry, its issue with Opensea. They are not allowing to add more nfts to the collection.

**Comment by infotrex** [comment]
> Sorry, its issue with Opensea. They are not allowing to add more nfts to the collection.

yes.
