### ISSUE TITLE
6 months instead of 1 month PLEASE

### ISSUE THREAD

**Issue by goodoffer** [infotrex/bulk-upload-to-opensea#41]
In your script NFTs load with Date Range 1 month, but before clicking on "Complete listing", you can set 6 months in the "Ending" (calendar) 

Make it possible to set 6 months instead of 1, please
<img width="627" alt="Screenshot 2022-01-27 at 11 38 33 am" src="https://user-images.githubusercontent.com/95210401/151361996-c087e477-e2d9-4b22-8f3d-d4d1793948c5.png">

**Comment by infotrex** [comment]
@goodoffer 
the feature i was updated to file upload18.py
https://www.youtube.com/watch?v=bqhM4r1aOqE
thx

**Comment by Amalsaju** [comment]
Its issue with Opensea. They reduced the time to 1 month from 6 months.
