### ISSUE TITLE
Exception in tkinter callback due to selenium webdriver timeout

### ISSUE THREAD

**Issue by mk9876** [infotrex/bulk-upload-to-opensea#42]
Any help to solve this issue as only one file is uploaded at one time. The automation doesn't even list the item for sale before the exception message comes in the command prompt

**Comment by infotrex** [comment]
pls check your opensea link input field, should end with "assets/create"

**Comment by ZacharyAkers** [comment]
I am guessing this is same issue I had, it isn't fact that input field is wrong, its a xpath issue. The xpath on line 313-314 you had was `/html/body/div[5]/div/div/div/div[2]/button/i` but for me it was `/html/body/div[6]/div/div/div/div[2]/button/i`. This causes it to timeout once the item is created without closing the modal, to lead into listing the item.

**Comment by infotrex** [comment]
maximize you browser and zoom size 100% while its running.
windows resolutions set to 1600px or below.
thx

**Comment by ZacharyAkers** [comment]
@infotrex it was maximized and at 100%.
