### ISSUE TITLE
Please HELP

### ISSUE THREAD

**Issue by Intelligencybar** [infotrex/bulk-upload-to-opensea#43]
<img width="404" alt="Снимок экрана 2022-01-30 071532" src="https://user-images.githubusercontent.com/75547234/151686380-f0556144-4016-4245-bb5b-0c940e469a4c.png">

I don't understand what the problem is. It just stops at the metadata tab and doesn't fill them in.

**Comment by Intelligencybar** [comment]
I have already tried "attributes" and "trait_type"

**Comment by Intelligencybar** [comment]
![Снимок экрана 2022-01-30 084101](https://user-images.githubusercontent.com/75547234/151688157-fffb51b8-678b-4fb1-b966-6adeb8367a89.png)

**Comment by infotrex** [comment]
json date structure should look like this.
{
  "name": "FCN #1",
  "description": "Forture Cat Neko",
  "image": "ipfs://Qmb7skA43kEUQwVTaAepNmU9sk4rpHQn4feB4M5ibpdYZx/2650.png",
  "dna": "5b882fd9b472c8696ca514e34a91b32e36ff48f4",
  "edition": 1,
  "date": 1637558552616,
  "attributes": [
    {
      "trait_type": "BACKGROUND",
      "value": "Gold Yellow"
    },
    {
      "trait_type": "BODY",
      "value": "Orange Left Hand"
    },
    {
      "trait_type": "CLOTHES",
      "value": "Bow Tie"
    },
    {
      "trait_type": "EAR",
      "value": "Red"
    },
    {
      "trait_type": "EYE",
      "value": "Freak"
    },
    {
      "trait_type": "HAT",
      "value": "Top Hat"
    },
    {
      "trait_type": "MOUTH",
      "value": "Smile"
    },
    {
      "trait_type": "WEAR",
      "value": "Mustache"
    }
  ],
  "compiler": "HashLips Art Engine"
}

**Comment by Intelligencybar** [comment]
I replaced "properties" with "attributes" and "type" with "trait_type" but it just stops by highlighting the cross on properties type selection

**Comment by Intelligencybar** [comment]
![Screenshot_20220130-142011_Chrome](https://user-images.githubusercontent.com/75547234/151697500-a974f1d4-2b46-405d-a3f8-510745024e0a.jpg)
There must be indents here, I suppose?

**Comment by Intelligencybar** [comment]
It feels like he misses.  I changed the screen resolution, the browser is open at 100%

**Comment by infotrex** [comment]
@Intelligencybar 
pls validate your json file
https://jsonlint.com

**Comment by infotrex** [comment]
@Intelligencybar 
Please set your PC date to MM/dd/yyyy, it will temporary resolved that date issue :)

**Comment by Intelligencybar** [comment]
I'm sorry that I could not answer you and send you a file, as I undermined my health trying to find the problem.  And apparently I found it!  The penultimate bracket "]" should look like this "]," followed by a comma.  Tell me is there a problem?  I love you man!  Thank you for your hard work!

**Comment by Intelligencybar** [comment]
no
