### ISSUE TITLE
6 months listing option doesn't work

### ISSUE THREAD

**Issue by openmonkeysnft** [infotrex/bulk-upload-to-opensea#44]
The script doesn't set the listing duration to 6 months. Instead of adjusting the end month, it adjusts the end date before moving the cursor to the "month". 
![github](https://user-images.githubusercontent.com/98688274/151695313-8d200529-5390-44da-b57a-9b9797f6a947.png)

**Comment by infotrex** [comment]
@openmonkeysnft 
checking this issue

**Comment by infotrex** [comment]
@openmonkeysnft 
Please set your PC date to MM/dd/yyyy, it will temporary resolved that date issue :)
