### ISSUE TITLE
What is it bro? Help please

### ISSUE THREAD

**Issue by goodoffer** [infotrex/bulk-upload-to-opensea#45]
After clicking on the "create" button, this error appears. What's wrong?

<img width="1400" alt="Screenshot 2022-01-30 at 5 15 18 pm" src="https://user-images.githubusercontent.com/95210401/151703542-a06b00d5-6439-4ccc-a536-7551d1dc3bd6.png">

**Comment by infotrex** [comment]
@goodoffer 
not sure what error.
do you signed before start running?

**Comment by goodoffer** [comment]
I signed before start running of course :)

**Comment by goodoffer** [comment]
I laucnhed upload.py (not upload18.py). Is it ok?

**Comment by infotrex** [comment]
yes, you can use upload.py.
i not sure what the problem a cause for that issue.
