### ISSUE TITLE
error on last step, sign to metamask wallet to complete listing

### ISSUE THREAD

**Issue by MyAntree** [infotrex/bulk-upload-to-opensea#46]
![Untitled-1](https://user-images.githubusercontent.com/44626700/151720528-85bb2751-4f57-48a5-82d1-45d72f8f49f0.jpg)
all the process is done until complete listing on "sign to metamask"

**Comment by MyAntree** [comment]
![image](https://user-images.githubusercontent.com/44626700/151725594-e68a15aa-21ba-4a6b-b5a9-d13cf9643fb6.png)

**Comment by atomiccrazzy** [comment]
im getting the same issue

**Comment by infotrex** [comment]
maximize your browser and zoom size 100% while its running,
and set display resolution to below 1600px.
if still not work, i not sure what is that problem.

**Comment by infotrex** [comment]
> 

@atomiccrazzy @MyAntree 
do you try that method?

**Comment by MyAntree** [comment]
> > maximize your browser and zoom size 100% while its running,
> > and set display resolution to below 1600px.
> > if still not work, i not sure what is that problem.
> 
> @atomiccrazzy @MyAntree do you try that method?

it's working
