### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by HexyeDEV** [infotrex/bulk-upload-to-opensea#47]
Could you also make a version working with chrome driver for linux?

**Comment by infotrex** [comment]
i still try in other mac version.
but linux version i not sure i can make it or not

**Comment by HexyeDEV** [comment]
I do know how you could do it, there is a thing for at least some linux os called vinehq which makes you open windows executable files, so you could make one file for linux same as the other but when you use os to just execute "chromedriver.exe" you will need to execute "wine chromedriver.exe" I don't know if there will be other changes needded

**Comment by infotrex** [comment]
@HexyeDEV you have twitter? can i contact you?

**Comment by HexyeDEV** [comment]
Yes, @HexyeIsPurple

**Comment by HexyeDEV** [comment]
Did you dm me?

**Comment by infotrex** [comment]
your twitter i cannot message you.
i was email to your gmail, pls check.
pls contact me twitter @ klvntss

**Comment by jonglae** [comment]
im test linux
90 line 

def open_chrome_profile():
    subprocess.Popen(
        [
            #  "start",
            "chrome --remote-debugging-port=8989",
            # "--remote-debugging-port=8989",
            # "--user-data-dir=" + main_directory + "chrome://version",
        ],
        shell=True,
    )


    opt.add_experimental_option("debuggerAddress", "localhost:8989")
    driver = webdriver.Chrome( service=Service("/usr/bin/chromedriver"), options=opt, )

and os path \\ -> / change please

linux complete work
