### ISSUE TITLE
Item name's number padding

### ISSUE THREAD

**Issue by Joonel** [infotrex/bulk-upload-to-opensea#48]
Hi could you please add an option to pad numbers in item name? 
Like:
"Item №001"
"Item №023"
"Item №124"
And the ability to change symbol "#" is also much needed. 
I publish NFTs like [this](https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/40863056196872349998224766138776821696089018009211381394374664794024995454977) one (yup, it is yours).

**Comment by Joonel** [comment]
So, there is still no padding. 
And all my NFT files have their own number in the name which have to be used for item's name generation. 
As you closed your code I can't make this little modification so I have to write my own script from zero 😒

**Comment by infotrex** [comment]
@Joonel do you have twitter?

**Comment by Joonel** [comment]
@infotrex @JiLoop3

**Comment by p4rnicke** [comment]
Hi @infotrex,
I would like to carry out similar change to the code (zero padding) but as it is obfuscated it is not that simple.
I started following you on Twitter as @KardosNicke, but cannot send you a message there.
Can you share the source for at least upload18.py?
Also not clear the DNA field meaning. And the date could have been filled automatically etc.

**Comment by infotrex** [comment]
@p4rnicke 
now you can download the original source file upload18.py.
