### ISSUE TITLE
Code obfuscated

### ISSUE THREAD

**Issue by MassimoTambu** [infotrex/bulk-upload-to-opensea#49]
Hi,

Why the code is obfuscated?

**Comment by tmitchellgcio** [comment]
Too scary to use in my opinion. I would not trust it. Remember it accesses your metamask

**Comment by infotrex** [comment]
@tmitchellgcio what do you mean?

**Comment by tmitchellgcio** [comment]
Open source code, that works with a security wallet like metamask and the code is obfuscated feels scary to trust. Don't get me wrong you probably have no intentions of stealing wallets, but we can't know that without verifying the code doesn't send session tokens to you in some way. It's a lot of trust.

**Comment by infotrex** [comment]
@tmitchellgcio @MassimoTambu 
code obfuscated just avoid to resell it nothing else.
my intentions just for my part of my NFTs marketing strategy and youtube channel :)
stealing wallets are not valuable for my project and image, am i correct?

**Comment by MassimoTambu** [comment]
> code obfuscated just avoid to resell it nothing else

Sorry, I probably didn't understand. Did you obfuscate the code just to avoid the someone else could copy and sell your code?

**Comment by tmitchellgcio** [comment]
Technically stealing wallets can be quite valuable, but even so. It's fair enough, but I won't use it myself because of this. It makes it feel like there is code you are hiding. I agree though it's not good for your channel and NFTs or your github, but those things can be replaced technically. I don't trust any open source software that's obfuscated like this. I can't guarantee what it does

**Comment by infotrex** [comment]
> > code obfuscated just avoid to resell it nothing else
> 
> Sorry, I probably didn't understand. Did you obfuscate the code just to avoid the someone else could copy and sell your code?

you go fiverr.com you will found that.

**Comment by stackzwolle** [comment]
hi
would it be ok to send me the code for changing the date to six months? :)
thanks

**Comment by infotrex** [comment]
@stackzwolle use the upload18.py for the duration 6 months

**Comment by stackzwolle** [comment]
> @stackzwolle use the upload18.py for the duration 6 months

yes im using it but i am trying to re-code something would really love to have the code duration part only

**Comment by stackzwolle** [comment]
please help im doing it for mac just that line for duration for 6 months.
im using yours in mac parallel desktop and my mac getting really slow.
thanks

**Comment by infotrex** [comment]
@infotrex 
i try doing in mac version, but it not working :(

**Comment by infotrex** [comment]
@tmitchellgcio
i release the original source code - upload18.py
you can check for it.
thx

**Comment by stackzwolle** [comment]
oh wow thanks for the code.
what i did with someone code is change the "chromedriver.exe" (windows) to "chromedriver 2" (mac)
and it work just fine will try to yours 

cheers

**Comment by stackzwolle** [comment]
omg it works

**Comment by infotrex** [comment]
@stackzwolle
if your new code can work with MacOs, 
pls share with me, i want put into my repo :).

TQ

**Comment by stackzwolle** [comment]
@infotrex 
ofcourse if i can and i will ask someone also :)

take care
