### ISSUE TITLE
Selenium version not supported for chrome version 98

### ISSUE THREAD

**Issue by tahaimran** [infotrex/bulk-upload-to-opensea#50]
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at localhost:8989
from session not created: This version of ChromeDriver only supports Chrome version 96
Current browser version is 98.0.4758.81

**Comment by infotrex** [comment]
pls download chrome 98.0.. here
https://chromedriver.storage.googleapis.com/index.html?path=98.0.4758.48/

**Comment by tahaimran** [comment]
Done, Thanks
