### ISSUE TITLE
Nothing Happens when you press start.

### ISSUE THREAD

**Issue by Merc616** [infotrex/bulk-upload-to-opensea#52]
Nothing happens when pressing start. Followed every step to a T. Been trying for hours, tried deleting all files and restarting as well. Doesn't seem to work. Made sure to use the src path that i copied the meta data and pngs into. No idea where the problem is occurring. Im sitting on the add item page when i press start, maybe because I'm utilizing polygon block chain? Press start goes gray for a second or two then back to green.

**Comment by Merc616** [comment]
Im using latest version of chrome but been reading about chrome 96 is needed not sure if that is correct and maybe thats the issue.

**Comment by infotrex** [comment]
Pls download your compatible chrome version here and replace my chromedriver.exe file
https://chromedriver.chromium.org/downloads

thx
