### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by Bakhshi007** [infotrex/bulk-upload-to-opensea#53]
<string>:263: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:268: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:272: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:276: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:327: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
Exception in Tkinter callback
Traceback (most recent call last):

**Comment by infotrex** [comment]
pls check all your input field information are valid string.
