### ISSUE TITLE
<string>:230: DeprecationWarning: executable_path has been deprecated, please pass in a Service object <string>:230: DeprecationWarning: use options instead of chrome_options

### ISSUE THREAD

**Issue by Sidnerm** [infotrex/bulk-upload-to-opensea#54]
After launching the openci website opens, but that's all
Chrome 98, chromedriver 98
Running the upload18 version

**Comment by ZacharyAkers** [comment]
@Sidnerm easy fix you edit code slightly on line 24 and 25 of upload18.py if you put
`from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service`
Then on line 226-229 replace what is put with 
`driver = webdriver.Chrome(
        service=Service(project_path + "/chromedriver.exe"),
        options=opt,
    )`

**Comment by abhiram-ms** [comment]
code is obfuscated

**Comment by abhiram-ms** [comment]
could you please explain it

**Comment by infotrex** [comment]
@ZacharyAkers do you have twitter bro?
can we chat at twitter @klvntss
