### ISSUE TITLE
It stops at Adding  Properties

### ISSUE THREAD

**Issue by Bakhshi007** [infotrex/bulk-upload-to-opensea#55]
number  1
<string>:242: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:247: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:251: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:255: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:266: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "<string>", line 274, in main_program_loop
UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 215: illegal multibyte sequence

**Comment by Bakhshi007** [comment]
@infotrex 
Please Need your help here.

Thanks

**Comment by Intelligencybar** [comment]
same problem

**Comment by infotrex** [comment]
@Intelligencybar @Bakhshi007 
show me your json file, pls
i notice new Hashlips json file structure are not fit into my script.
thx

**Comment by Bakhshi007** [comment]
@infotrex 

{
  "file_path": "D:/CV/generate-nfts-main/generate-nfts-main/build/images/1.png",
  "nft_name": "..........................",
  "external_link": "",
  "description": ".................................................................................",
  "collection": "......................................",
  "properties": [
    {
      "type": "Background",
      "name": "Hot Pink"
    },
    {
      "type": "Clothes",
      "name": "Tuxedo"
    },
    {
      "type": "Face",
      "name": "Earths Moon"
    },
    {
      "type": "Hat",
      "name": "Cooking Cap"
    },
    {
      "type": "Expression",
      "name": "Scary Devil"
    }
  ],
  "levels": [],
  "stats": [],
  "unlockable_content": [],
  "explicit_and_sensitive_content": false,
  "supply": 1,
  "blockchain": "Polygon",
  "price": 0.005,
  "quantity": 1,
  "dna": "599b9e81c767b5f23a6cadbd606cad6f41338169",
  "edition": 1,
  "date": 1644225517344,
  "compiler": "HashLips Art Engine"
}

**Comment by infotrex** [comment]
@Bakhshi007 
This is new HashLips art engine,
the json structure not compatible with my bulk upload script.

you still use the bulk upload script if you know modify this script to extract your json attributes

**Comment by Bakhshi007** [comment]
Dear @infotrex  
Could you please tell me which  version of Hashlipgenerater you have used for the bulk upload so I can regenerate my collection using that version.

Thanks 
Regards 
FB

**Comment by Bakhshi007** [comment]
@infotrex 
I couldn't find the Json structure on the  bulk upload script so that I can modify it. Could you please tell me where can I find it on script.

Thanks

**Comment by infotrex** [comment]
you need to modify this script
https://github.com/infotrex/bulk-upload-to-opensea/blob/main/upload18.py

**Comment by infotrex** [comment]
> @infotrex I couldn't find the Json structure on the bulk upload script so that I can modify it. Could you please tell me where can I find it on script.
> 
> Thanks

try this
https://github.com/HashLips/hashlips_art_engine

**Comment by Bakhshi007** [comment]
@infotrex 
I have Regenerated my collection with the mentioned Json File.
is it ok Now ?
Thanks 

{
  "name": "....................................................",
  "description": ".....................................................................................................................",
  "image": "D:/CV/generate-nfts-main/hashlips_art_engine-main/build/images/1.png",
  "dna": "c68347b9d25b0101d98e13a922b9f20665678f91",
  "edition": 1,
  "date": 1644313027176,
  "attributes": [
    {
      "trait_type": "Background",
      "value": "Deep Sky"
    },
    {
      "trait_type": "Clothes",
      "value": "White_Shirt"
    },
    {
      "trait_type": "Face",
      "value": "Ceres"
    },
    {
      "trait_type": "Hat",
      "value": "White Hat"
    },
    {
      "trait_type": "Expression",
      "value": "Joy"
    }
  ],
  "compiler": "HashLips Art Engine"
}

**Comment by infotrex** [comment]
> @infotrex I have Regenerated my collection with the mentioned Json File. is it ok Now ? Thanks
> 
> { "name": "....................................................", "description": ".....................................................................................................................", "image": "D:/CV/generate-nfts-main/hashlips_art_engine-main/build/images/1.png", "dna": "c68347b9d25b0101d98e13a922b9f20665678f91", "edition": 1, "date": 1644313027176, "attributes": [ { "trait_type": "Background", "value": "Deep Sky" }, { "trait_type": "Clothes", "value": "White_Shirt" }, { "trait_type": "Face", "value": "Ceres" }, { "trait_type": "Hat", "value": "White Hat" }, { "trait_type": "Expression", "value": "Joy" } ], "compiler": "HashLips Art Engine" }

yes..correct

**Comment by Intelligencybar** [comment]
I tried different screen resolutions but the script stops on loading attributes

**Comment by Bakhshi007** [comment]
@infotrex 
even after regenerating the json file , still gets this error:
<string>:209: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
<string>:209: DeprecationWarning: use options instead of chrome_options
Start creating NFT The Planet Club#1
number  1
<string>:242: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:247: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:251: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:255: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:266: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "<string>", line 274, in main_program_loop
UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 107: illegal multibyte sequence

**Comment by infotrex** [comment]
do you select correct "src" folder?

**Comment by infotrex** [comment]
> I tried different screen resolutions but the script stops on loading attributes

stop at which screen?

**Comment by Intelligencybar** [comment]
Stops at the screen with attributes

**Comment by Bakhshi007** [comment]
@infotrex 
Yes I have copied my collection with json to src folder and selected src.
but still get the same error.

**Comment by Intelligencybar** [comment]
What module does it depend on?  Can you tell me so that I understand what to focus on

**Comment by infotrex** [comment]
@

> 
json file are depend this keys attributes - trait_type and value
"attributes": [ { "trait_type": "Background", "value": "Deep Sky" }, { "trait_type": "Clothes", "value": "White_Shirt" }, { "trait_type": "Face", "value": "Ceres" }, { "trait_type": "Hat", "value": "White Hat" }, { "trait_type": "Expression", "value": "Joy" } ]

**Comment by infotrex** [comment]
> @infotrex Yes I have copied my collection with json to src folder and selected src. but still get the same error.

this need further check only can give you answer.

**Comment by Intelligencybar** [comment]
In the new version of HashLips, attribute generation looks like this

**Comment by Intelligencybar** [comment]
If you find a solution guys let me know

**Comment by Ghofit** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Ghofit\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "upload18.py", line 286, in main_program_loop
    jsonData = json.loads(open(file_path + "\\json\\"+ str(start_numformat) + ".json").read())
  File "C:\Users\Ghofit\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 103: character maps to <undefined>

stop at atribute with this eror, anyone can help me
