### ISSUE TITLE
Please HELP #43

### ISSUE THREAD

**Issue by Intelligencybar** [infotrex/bulk-upload-to-opensea#56]
ATTRIBUTES

**Comment by Intelligencybar** [comment]
![Снимок экрана 2022-02-08 005021](https://user-images.githubusercontent.com/75547234/152877984-2a5a347d-93a9-45a1-ae92-acedfafd2727.png)

it just stop

**Comment by infotrex** [comment]
the json file have slightly different structure for latest Hashlips generator.
you need to modify my upload18.py script in order to fit in your json file.

**Comment by Intelligencybar** [comment]
check Discord

**Comment by Intelligencybar** [comment]
![Снимок экрана 2022-02-08 055922](https://user-images.githubusercontent.com/75547234/152909829-95e42754-f5e4-4924-acfe-9f4809cd774d.png)
perfect structure
