### ISSUE TITLE
1 month listing not working

### ISSUE THREAD

**Issue by HiimNaruto** [infotrex/bulk-upload-to-opensea#57]
Hi, 
I was trying to list NFTs for 1 month and it's not working. 60 days option is working.

**Comment by infotrex** [comment]
have some issue about 30 days, 
you can use this file upload.py without duration function
*Opensea default date duration is 30 days.

**Comment by misterkayr** [comment]
> have some issue about 30 days, you can use this file upload.py without duration function *Opensea default date duration is 30 days.

The problem is, that if you upload, say 100 NFTs for 7 days as a primary drop, and then follow that up, then using upload.py wont make a difference as it will default to 7 days

**Comment by misterkayr** [comment]
I edited the code and added 14 days to replace the 1 month
Works fine

**Comment by HiimNaruto** [comment]
> d a default change to 1 month in late dece

how did you edit the code ? can you please help me to update that too ?

**Comment by HiimNaruto** [comment]
> have some issue about 30 days, you can use this file upload.py without duration function *Opensea default date duration is 30 days.

default is 7 days :(

**Comment by gilh1221** [comment]
Any way to set default to 1 month?
