### ISSUE TITLE
Unable to upload polygon

### ISSUE THREAD

**Issue by HiimNaruto** [infotrex/bulk-upload-to-opensea#6]
can you please help me to use this with the polygon bloack chain?

**Comment by infotrex** [comment]
try un-tick "polycon blockchain" 
and ref my checklist section.

**Comment by HiimNaruto** [comment]
Hi, 
yes, it's working like that. but it's only working on the ETH blockchain. Unable to upload to the polygon.

**Comment by infotrex** [comment]
this application tested on polygon blockchain,
please check your opensea collection page, should set polygon as default.
i believe your collection currently set to ETH blockchain.

**Comment by HiimNaruto** [comment]
![image](https://user-images.githubusercontent.com/32328206/147316672-b8bb590f-eae6-4cf1-8df7-7247534d5fc2.png)
It's already on polygon blockchain. but after the uploading when it comes to set price, it will work on ETH, not changing to the polygon. 
![image](https://user-images.githubusercontent.com/32328206/147316824-e28445b9-35d3-416f-90ba-b7500237836d.png)

**Comment by infotrex** [comment]
yes, you setting is correct.
My collection also set as polycon, the price also show as ETH at price.
You try to list / sale a file and you know. :)

**Comment by HiimNaruto** [comment]
I think this is not working with free listing. right? :)

**Comment by infotrex** [comment]
i use same method,
that is free listing if you are using polycon.

**Comment by HiimNaruto** [comment]
but when I do listing, I have to pay around 20$. 
didn't you pay any money for the listing. ? can you please help me to do that? I am so confused here.

**Comment by infotrex** [comment]
No,
I didn't pay anything for current collection and listing.  :)
you can refer other video for create new opensea collection.
you may miss out something.
thx

**Comment by HiimNaruto** [comment]
Yeah. I think I missed something too. :( I watched some videos and created my collection. can you recommend a video for me?

**Comment by HiimNaruto** [comment]
Hii.. 
it worked. I had to log again to the meta mask. thank you very much for this program. you are a Genius<3

**Comment by infotrex** [comment]
Great to heard that.
If my project are really helping you and save your time for upload nft to opensea, 
just give a support or  like my Opensea collection. :)
Thank you in advance.

**Comment by HiimNaruto** [comment]
Already done brother! thank you again! you saved a lot of time!
