### ISSUE TITLE
 File "C:\Users\James\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until     raise TimeoutException(message, screen, stacktrace) selenium.common.exceptions.TimeoutException: Message: Stacktrace: Backtrace:

### ISSUE THREAD

**Issue by JamesMailman** [infotrex/bulk-upload-to-opensea#60]
I can't seem to get past the part where it creates the asset, but doesn't put it up for sale, then it just stops working. Any ideas how to solve this? Thank you

**Comment by ZacharyAkers** [comment]
@JamesMailman it creates but stops once it pops up the little modal on screen where it says you can list it right?

**Comment by ZacharyAkers** [comment]
![example](https://user-images.githubusercontent.com/28814416/153137341-ffc0e410-222b-4175-a574-a8c94084433a.png)

**Comment by misterkayr** [comment]
Similar issues...
It creates the NFT fine
when it creates the "Sell" .. everything goes fine
then it asks to verify (via metamask)
everything is fine and it verifies
That is when the errors get thrown up (something to do with an API)

I am not sure if its the app or if the issues is with opensea itself.
If I go back and manually list the product for sale, everything goes fine.. it verifies with metamask, gets approved and lists the item as it should... which then makes me think, its the app

**Comment by JamesMailman** [comment]
> ![example](https://user-images.githubusercontent.com/28814416/153137341-ffc0e410-222b-4175-a574-a8c94084433a.png)
yes, but that's where it stops.

**Comment by JamesMailman** [comment]
> Similar issues... It creates the NFT fine when it creates the "Sell" .. everything goes fine then it asks to verify (via metamask) everything is fine and it verifies That is when the errors get thrown up (something to do with an API)
> 
> I am not sure if its the app or if the issues is with opensea itself. If I go back and manually list the product for sale, everything goes fine.. it verifies with metamask, gets approved and lists the item as it should... which then makes me think, its the app
> 
> The text is cuttoff and this all all I see, for a second or 2 ![Opensea-error](https://user-images.githubusercontent.com/99330334/153198658-fb2d6081-d2db-43fa-9c9b-cb6c57283cff.png)

I don't even get to the sell page, mine stops when it's created.

**Comment by ZacharyAkers** [comment]
make sure you save the code and close upload18.py app and then restart it, should be fixed then

**Comment by ZacharyAkers** [comment]
@misterkayr did you try running it again through upload18.py and still got that issue?

**Comment by ZacharyAkers** [comment]
the error message looks like it is opensea side that is failing, not the app

**Comment by misterkayr** [comment]
> the error message looks like it is opensea side that is failing, not the app

Yes... you are correct... its all working fine now
