### ISSUE TITLE
Chrome Update

### ISSUE THREAD

**Issue by Bosarris** [infotrex/bulk-upload-to-opensea#61]
was all working fine yesterday and all of a sudden I'm getting this error today?

**Comment by Bosarris** [comment]
strange thing was - working fine yesterday

**Comment by Bosarris** [comment]
will there be an update for this tool or am i going to have to downgrade chrome?

**Comment by infotrex** [comment]
@Bosarris 
download your compatible chromedriver.exe version here
https://chromedriver.chromium.org/downloads
