### ISSUE TITLE
Upload18 Last step not working (This error can be fixed easily I think)

### ISSUE THREAD

**Issue by Fyzii** [infotrex/bulk-upload-to-opensea#62]
I know that all these problems bother you and I completely understand but I am sorry to announce that your last update of the program bug

He gives me the price and the dates of the NFT but after opensea asks that we sign from our wallet to confirm the sale except that the program does nothing and remains blocked, which means that for each NFT we have to restart the program, which becomes very boring when you have more than 1000 ^^'

I hope you can solve the problem and I wish you a good day :D

**Comment by ZacharyAkers** [comment]
Are you using polygon @Fyzii it's been going off and on for past couple days

**Comment by Fyzii** [comment]
Yes im using polygon

**Comment by Fyzii** [comment]
I didn't close because the problème is still here

**Comment by ZacharyAkers** [comment]
That should be issue then is polygon network. It keeps doing it for me as well

**Comment by Fyzii** [comment]
OK but you can sell nft with polygon now that not the problem the problem is that the bot didn't click on the sign button when you want to sell it

**Comment by Fyzii** [comment]
![Uploading 16444501308424589991421113704368.jpg…]()
It's stuck here (the bot do nothing and we need to click sell manually)

**Comment by ZacharyAkers** [comment]
does it throw an error up in terminal on your visual studio code when it gets to sign and breaks?

**Comment by Fyzii** [comment]
OMG  WAIT
Well it work now :)
Idk how but that cool lmao
Have a great day or night
