### ISSUE TITLE
Script goes not responding when I click start

### ISSUE THREAD

**Issue by sartika6** [infotrex/bulk-upload-to-opensea#65]
I did everything as instructed in video. I use chrome 98 and chromedriver 98(replaced in project folder), python 3.8.10, added image and json folder in src folder, tried all upload.py upload18.py and upload_fixedSSL.py, clicked open browser, connected and signed metamask. But when I click start browser goes to collection page and freezes(not responding), then after a minute or so I get the following log:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "upload18.py", line 258, in main_program_loop
    wait_xpath('//*[@id="media"]')
  File "upload18.py", line 244, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x01217AC3+2587331]
        Ordinal0 [0x011AADD1+2141649]
        Ordinal0 [0x010A3BB8+1063864]
        Ordinal0 [0x010D01CE+1245646]
        Ordinal0 [0x010D03CB+1246155]
        Ordinal0 [0x010FA612+1418770]
        Ordinal0 [0x010E86D4+1345236]
        Ordinal0 [0x010F8A0A+1411594]
        Ordinal0 [0x010E84A6+1344678]
        Ordinal0 [0x010C53F6+1201142]
        Ordinal0 [0x010C62E6+1204966]
        GetHandleVerifier [0x013BDF22+1680738]
        GetHandleVerifier [0x01470DBC+2413564]
        GetHandleVerifier [0x012AD151+563089]
        GetHandleVerifier [0x012ABF13+558419]
        Ordinal0 [0x011B081E+2164766]
        Ordinal0 [0x011B5508+2184456]
        Ordinal0 [0x011B5650+2184784]
        Ordinal0 [0x011BF5BC+2225596]
        BaseThreadInitThunk [0x76066709+25]
        RtlGetFullPathName_UEx [0x76EE7CCD+173]
        RtlGetFullPathName_UEx [0x76EE7C9B+123]

Can someone please help me out?

**Comment by infotrex** [comment]
@sartika6 
do you select correct "src" folder?
and your image filename look like this 1.png ....?

**Comment by sartika6** [comment]
Yes exactly, I used hashlips.

**Comment by infotrex** [comment]
> do you select correct "src" folder?

do you select correct "src" folder?
your error message stop at image pickup section.

**Comment by sartika6** [comment]
> > do you select correct "src" folder?
> 
> do you select correct "src" folder? your error message stop at image picker section.

Yes, I selected the correct location "C:\Users\Administrator\Desktop\bulk-upload-to-opensea\src"

**Comment by ZacharyAkers** [comment]
@sartika6 what does your json look like out of curiosity

**Comment by infotrex** [comment]
@sartika6 
what is your image filename?
look like this 1.png?

**Comment by sartika6** [comment]
@infotrex Yes exactly 1.png 2.png etc

**Comment by sartika6** [comment]
I forgot to add /assets/create now script works like a charm thank you for support.

**Comment by Moose2022-maker** [comment]
where did you add /assets/create? 

I am having the same problem

**Comment by ZacharyAkers** [comment]
@Moose2022-maker you put it at end of link to your collection so it'll be something like opensea.io/collection/assets/create
