### ISSUE TITLE
Cant launch app 

### ISSUE THREAD

**Issue by Zonum94** [infotrex/bulk-upload-to-opensea#67]
When i put python upload.py its says this:
Traceback (most recent call last):
  File "upload.py", line 11, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 232
    start_numformat = f"{ start_num:04}"
                                       ^
SyntaxError: invalid syntax

and when I put python upload18.py it says this:
File "upload18.py", line 249
    start_numformat = f"{ start_num:04}"
                                       ^
SyntaxError: invalid syntax

please help I literally don't know what to do for the app to appear so I can start uploading my nfts. 
Thank You

**Comment by ZacharyAkers** [comment]
@Zonum94 you ran pip install -r requirements.txt? and have latest version of python installed?

**Comment by ZacharyAkers** [comment]
Also send the line 247-251 might be missing a colon or something on line 248 for odd reason

**Comment by Zonum94** [comment]
Hello,

yes i installed everything and did everything in the video but when I ran
the python upload.py it just doesn't want to work. ill try right now
looking at the lines

**Comment by Zonum94** [comment]
what are the valid end and start number ??

**Comment by Zonum94** [comment]
File "upload18.py", line 247
    start_numformat = f"{ start_num:04}"

is this number correct? do i have to change it ?

**Comment by Zonum94** [comment]
also when i do just the normal python upload.py it says

  File "upload.py", line 11, in <module>

eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 232
    start_numformat = f"{ start_num:04}"
                                       ^
SyntaxError: invalid syntax

**Comment by ZacharyAkers** [comment]
Can you retry installing the upload18.py? You might have accidentally edited the script causing it to throw syntax error.

**Comment by Zonum94** [comment]
Does this affect in anyway?

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621


I reinstalled and still doesn't work for python upload.py 
Traceback (most recent call last):
  File "upload.py", line 11, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 232
    start_numformat = f"{ start_num:04}"

and for python upload18.py 

 File "upload18.py", line 249
    start_numformat = f"{ start_num:04}"
                                       ^
SyntaxError: invalid syntax

**Comment by ZacharyAkers** [comment]
can you go into upload18.py and copy the code from 247 to 251

**Comment by Zonum94** [comment]
while end_num >= start_num:
        if is_numformat.get():
            start_numformat = f"{ start_num:04}"
        else:
             start_numformat = f"{ start_num:01}"

**Comment by infotrex** [comment]
@Zonum94
What is the start number you put in?

**Comment by Zonum94** [comment]
in my images it starts with 1 ... is that what you were talking about?

**Comment by infotrex** [comment]
> in my images it starts with 1 ... is that what you were talking about?

 "start number" input field number

**Comment by ZacharyAkers** [comment]
@Zonum94 I thought it was throwing syntax error because it wouldn't start when you did python upload18.py? you are inputting info in the settings and it won't start when you press start?

**Comment by Zonum94** [comment]
yeah so basically i input pyhton upload.py and python upoad18.py and the app doesn't start

**Comment by infotrex** [comment]
@Zonum94
twitter me pls @klvntss
thx

**Comment by Zonum94** [comment]
<img width="588" alt="Screenshot 2022-02-13 at 21 41 36" src="https://user-images.githubusercontent.com/99564900/153791128-c8b9e7c7-f81c-4142-972d-3789cca07282.png">

**Comment by Zonum94** [comment]
it says i cant message you

**Comment by infotrex** [comment]
> it says i cant message you

your twitter pls

**Comment by Zonum94** [comment]
@wander_souls

**Comment by infotrex** [comment]
@wander_souls
Mac OS not support on this script.
thx

**Comment by Zonum94** [comment]
thanks for the help i will try on PC and if anything happens ill let you guys know
