### ISSUE TITLE
Selling

### ISSUE THREAD

**Issue by emrebaran** [infotrex/bulk-upload-to-opensea#69]
Hey guys!
Its now just creating one and stopping now. He is not continuing and not selling them. The last thing he does is the creation. Any others with that problem?

**Comment by emrebaran** [comment]
![image](https://user-images.githubusercontent.com/98944150/153755793-8ee35385-9d66-4eb5-a52f-bd7c7f39f428.png)

**Comment by emrebaran** [comment]
@infotrex where can i see them? Its a lot, it not fit in a picture.. Or which exactly do you need?

**Comment by ZacharyAkers** [comment]
@emrebaran can you share screenshot of python app inputs you put?

**Comment by emrebaran** [comment]
@infotrex @ZacharyAkers so little update. I Had supersea extension opened, i closed it now and it started working. Thank you both for your quick responds on my issue. :)
