### ISSUE TITLE
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

### ISSUE THREAD

**Issue by CryptoBurnClub** [infotrex/bulk-upload-to-opensea#72]
Hi, Could you help with this? I would love to be in contact but your twitter is not accepting messages.

**Comment by infotrex** [comment]
@CryptoBurnClub 
pls use this file upload18.py
thx

**Comment by CryptoBurnClub** [comment]
Hi, I am not sure what to do in that file , I appreciate your quick
response. I know you must be very busy with all of this. You can check out
our project on twitter @lazydogclub . This is our last step to get our
project out there.

**Comment by infotrex** [comment]
@CryptoBurnClub im DM twitter you.
