### ISSUE TITLE
Google chrome not opening

### ISSUE THREAD

**Issue by stikyscommands** [infotrex/bulk-upload-to-opensea#75]
When I press the "Open Chrome Browser" button, google chrome doesn't open. I'm using windows and I have the correct chromedriver version set up already.

Console error message: "The system cannot find the file chrome"
Program error message: "Windows cannot find 'chrome'. Make sure you typed the name correctly, and then try again."

**Comment by infotrex** [comment]
crosscheck your chromedriver.exe path login.
or any anvirus block it.
seldom see this error message.

**Comment by stikyscommands** [comment]
Tysm! I forgot that I changed my user folder name around 6 months ago, and while I've fixed most of the problems to do with that, some programs still use file paths with the old folder name. 

For anyone else with this problem, I set the path variable manually to my chrome.exe file
