### ISSUE TITLE
Stop Button needed

### ISSUE THREAD

**Issue by misterkayr** [infotrex/bulk-upload-to-opensea#76]
When I manually have to verify the captcha and then manually do the sell, the app sometimes takes off again, doing a SELL on the same item again.

So, perhaps a stop button on the app, so we dont have to "close program" to get the app to stop posting

**Comment by Intelligencybar** [comment]
Try to crash the script when it adds attributes by clicking on an empty area, thus closing the window for adding properties and the program will stop after a minute
