### ISSUE TITLE
Your payout wallet address

### ISSUE THREAD

**Issue by Intelligencybar** [infotrex/bulk-upload-to-opensea#77]
What is "Your payout wallet address" in collection settings?  Can I transfer my collection to a new Metamask account if I think my passwords have been compromised?

**Comment by SupportTech198** [comment]
>  What is "Your payout wallet address" in collection settings?  Can I transfer my collection to a new Metamask account if I think my passwords have been compromised?

Are you still having the issues or as your issues been resolved yet?
