### ISSUE TITLE
captcha 

### ISSUE THREAD

**Issue by Vj106** [infotrex/bulk-upload-to-opensea#78]
Any solution for captcha??

**Comment by infotrex** [comment]
no at the moment.

**Comment by infotrex** [comment]
@nabeelsaleem @nabeelsaleem 
i no plan to update this captcha issue at this moment,
due to opensea keep on updating...:(

**Comment by esmalipo** [comment]
after 5 days captcha came back

actually it should be a way for solving this annoying captcha...

No body know???
