### ISSUE TITLE
Opensea migration of listing

### ISSUE THREAD

**Issue by Inquisitive-Learner** [infotrex/bulk-upload-to-opensea#80]
Now open sea has indicated that we need to migrate our listing to new platform. What do we do if we have thousands of nft?

**Comment by infotrex** [comment]
@Inquisitive-Learner 
this i no idea

**Comment by calvinvalerian** [comment]
go to your Profile page and select Migrate listings tab 

![image](https://user-images.githubusercontent.com/18316781/154798807-050993c9-d54c-4592-88f7-a484d710b7dd.png)

**Comment by Inquisitive-Learner** [comment]
Yes, I am aware of this but there are thousands of nft and can only migrate
one at a time. Or can I bulk migrate?

**Comment by calvinvalerian** [comment]
ask @infotrex [infotrex](https://github.com/infotrex) to make the Bulk Migrate

**Comment by infotrex** [comment]
@calvinvalerian @Inquisitive-Learner 
im don't have any nft need migrate. :)
