### ISSUE TITLE
Almost work don't know where the error

### ISSUE THREAD

**Issue by calvinvalerian** [infotrex/bulk-upload-to-opensea#81]
https://youtu.be/VuYFL0FP2fY

**Comment by infotrex** [comment]
@calvinvalerian 
your should select **"src"**folder , instead of "src/images"

**Comment by calvinvalerian** [comment]
Oh yes it worked but there is one more problem I cannot use upload18.py

https://youtu.be/jJvRFzWC0bo

**Comment by infotrex** [comment]
@calvinvalerian 
open the file, remove line 229 and replace this line new script
driver = webdriver.Chrome(executable_path=project_path + "/chromedriver.exe", chrome_options=opt,)

**Comment by calvinvalerian** [comment]
It stopped after only uploading 1 image

https://youtu.be/fpbkOJJi4SM

**Comment by infotrex** [comment]
your opensea collection link field input should end with "assets/create".

> It stopped after only uploading 1 image
> 
> https://youtu.be/fpbkOJJi4SM

**Comment by calvinvalerian** [comment]
That's exactly what I did let me show you again with new recording https://youtu.be/Ysn6PPWdrD8

**Comment by infotrex** [comment]
Pls maximize your browser while it running.

**Comment by calvinvalerian** [comment]
Still error

https://youtu.be/oQrQi93dOpU

**Comment by infotrex** [comment]
> Still error
> 
> https://youtu.be/oQrQi93dOpU

sorry, i not sure why it stop loop.

**Comment by calvinvalerian** [comment]
Do this happen to you too?

**Comment by infotrex** [comment]
> Do this happen to you too?

nope, it should be loop continuously until to end number

**Comment by calvinvalerian** [comment]
Do you want to borrow my computer for in Team Viewer?

**Comment by calvinvalerian** [comment]
I am from Indonesia I think this will be a very interesting experience for you

**Comment by infotrex** [comment]
@calvinvalerian 
i believe that is new sign process from Opensea.

**Comment by calvinvalerian** [comment]
Can you let me know in this thread when the new version of bulk-upload-to-opensea released?

**Comment by infotrex** [comment]
will take sometimes to figure the issue.
won't' be updated recently.

**Comment by calvinvalerian** [comment]
Can you make Bulk Auction? I need it

**Comment by infotrex** [comment]
@calvinvalerian for any additional feature you request,  i will charge by project basis. :)

**Comment by calvinvalerian** [comment]
How much it cost?

**Comment by infotrex** [comment]
> How much it cost?
1) select type(timed auction) -> sell to highest bidder = USD100
or
2)  select type(timed auction)  -> sell with declining price -> input start and ending price = USD200
either one, depend how many step need to customize.

**Comment by ZacharyAkers** [comment]
@infotrex @calvinvalerian its a issue with the xpath on why it stops after 1 after making one. For some users xpath is 1 div more then others. reference solution i put in #60

**Comment by ZacharyAkers** [comment]
if you aren't sure what to change on line 332-341 replace the code with this should fix the loop issue.
```try:
            time.sleep(10)
            cross = driver.find_element(By.XPATH, '/html/body/div[6]/div/div/div/div[2]/button/i')
            cross.click()
            time.sleep(0.8)
        except:
            wait_xpath('/html/body/div[5]/div/div/div/div[2]/button/i')
            cross = driver.find_element(By.XPATH, '/html/body/div[5]/div/div/div/div[2]/button/i')
            cross.click()
            time.sleep(0.8)```

**Comment by calvinvalerian** [comment]
@infotrex wait until my first NFT is sold I'm low in cash

@ZacharyAkers 
this is the result

[the original version](https://youtu.be/lRRPnyLqyNQ)

**Comment by ZacharyAkers** [comment]
What error does your terminal bring up when you run it?

**Comment by infotrex** [comment]
@calvinvalerian 
that is new metamas sign process for ETH blockchain only)
Pls twitter me your email address, i have a draft script for fix that error.
if you want for test, pls contact me and buy me a coffee smile
TQ

**Comment by calvinvalerian** [comment]
@ZacharyAkers no error message. Your patch code made the program stuck at Item Creation pop up while the original code stops the program at Successful item listing.

`try:
            time.sleep(10)
            cross = driver.find_element(By.XPATH, '/html/body/div[7]/div/div/div/div[2]/button/i')
            cross.click()
            time.sleep(0.8)
        except:
            wait_xpath('/html/body/div[6]/div/div/div/div[2]/button/i')
            cross = driver.find_element(By.XPATH, '/html/body/div[6]/div/div/div/div[2]/button/i')
            cross.click()
            time.sleep(0.8)`

**Comment by calvinvalerian** [comment]
@infotrex my email is calvinvalerian@gmail.com

**Comment by calvinvalerian** [comment]
@ZacharyAkers @infotrex I want to see your opensea NFTs I am confused how much should I sell my NFT for

**Comment by infotrex** [comment]
> @ZacharyAkers @infotrex I want to see your opensea NFTs I am confused how much should I sell my NFT for
My opense nft
https://opensea.io/collection/fortune-cat-neko/
is depend on you and your nft.

**Comment by calvinvalerian** [comment]
C:\Users\calvi\OneDrive\Desktop\bulk-upload-to-opensea\upload18.py:229: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=project_path + "/chromedriver.exe", chrome_options=opt,)
Start creating NFT Crypto Shark #27
number  27
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\calvi\OneDrive\Desktop\bulk-upload-to-opensea\upload18.py", line 465, in main_program_loop
    wait_xpath('//button[text()="Sign"]')
  File "C:\Users\calvi\OneDrive\Desktop\bulk-upload-to-opensea\upload18.py", line 244, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 64, in __call__
    return _find_element(driver, self.locator)
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: window was already closed
  (Session info: chrome=98.0.4758.102)

**Comment by infotrex** [comment]
uncheck "polygon blockchain" if you using ETH blockchain for your collection

**Comment by calvinvalerian** [comment]
Already unchecked and that is the error I get

**Comment by calvinvalerian** [comment]
Do you want to control my computer from here and see it for yourself?

**Comment by infotrex** [comment]
twitter me pls.
@klvntss

**Comment by calvinvalerian** [comment]
what to do with twitter?

**Comment by infotrex** [comment]
email me or give me your teamviewer password here

**Comment by calvinvalerian** [comment]
email

**Comment by infotrex** [comment]
@calvinvalerian 
So all issue resolved right?

**Comment by GiraffeValley** [comment]
> Do this happen to you too?

were you able to solve this problem?

**Comment by calvinvalerian** [comment]
@infotrex yes finally all the problem solved Thanks a lot for the help how much for a Cup of coffee?

**Comment by infotrex** [comment]
@calvinvalerian
this is up to you, is depend how you judge this script and service worth it.

**Comment by GiraffeValley** [comment]
> @infotrex да наконец-то все проблема решена Большое спасибо за помощь сколько за чашечку 

can you tell me how you did it?

**Comment by calvinvalerian** [comment]
Can I buy you Coffee after my NFT is sold. My money is not much right now.

**Comment by infotrex** [comment]
> Can I buy you Coffee after my NFT is sold. My money is not much right now.

ok ok :)

**Comment by infotrex** [comment]
> > @infotrex да наконец-то все проблема решена Большое спасибо за помощь сколько за чашечку
> 
> can you tell me how you did it?

if you using ETH blockchain collection have that new sign issue.
give me your email address

**Comment by GiraffeValley** [comment]
> > > @infotrex да наконец-то все проблема решена Большое спасибо за помощь сколько за чашечку
> > 
> > 
> > можешь рассказать как ты это сделал?
> 
> если вы используете коллекцию блокчейнов ETH, у вас есть эта новая проблема со знаком. дайте мне ваш адрес электронной почты

I create my NFT on Matix Blockchain

**Comment by infotrex** [comment]
> 

polygon no any issue for current upload18.py this file.
show me your error message. thx

**Comment by GiraffeValley** [comment]
> > 
> 
> polygon нет никаких проблем с текущим файлом upload18.py. покажи мне свое сообщение об ошибке или твитни меня. Спасибо

![155004283-d3551e55-e049-4eae-b8ab-27254995b8f0](https://user-images.githubusercontent.com/99540282/155103477-ff633424-3fc7-46ee-b2d8-38caa105c970.png)

**Comment by infotrex** [comment]
pls check your correct path select "SRC" folder and filename should like this, 1.png or 2.png

**Comment by GiraffeValley** [comment]
> Пожалуйста, проверьте правильный путь, выберите папку "SRC" и имя файла должно быть таким, 1.png или 2.png

but, that is, if my picture is called #1.png is this wrong?

**Comment by infotrex** [comment]
filename should look like this 1.png, while program running it want pick the number image.
you can modify the script according you need, if you want #1.png, nothing wrong.

**Comment by GiraffeValley** [comment]
> имя файла должно выглядеть так: 1.png, пока программа запускает его, нужно выбрать числовое изображение. вы можете изменить сценарий в соответствии с вашими потребностями, если вы хотите [# 1](https://github.com/infotrex/bulk-upload-to-opensea/issues/1) .png, ничего плохого.

change the script in the sense of change in the code?

**Comment by infotrex** [comment]
yes

**Comment by GiraffeValley** [comment]
> да

change the script in the sense of change in the code?  in a python18 file?

**Comment by GiraffeValley** [comment]
> да

and if I don't want to change the code, can I just rename the picture?

**Comment by infotrex** [comment]
> and if I don't want to change the code, can I just rename the picture?

yes, rename all the pictures

**Comment by GiraffeValley** [comment]
> > а если я не хочу менять код, могу я просто переименовать картинку?
> 
> да, переименовать все картинки

Thanks you 💗

**Comment by GiraffeValley** [comment]
> > а если я не хочу менять код, я могу просто переименовать картинку?
> 
> да, переименовать все картинки

I try this in 1 hours

**Comment by GiraffeValley** [comment]
> > and if I don't want to change the code, can I just rename the picture?
> 
> yes, rename all the pictures

It`s work, I`m so HAPPY , thank you

**Comment by calvinvalerian** [comment]
@infotrex there is one more problem.

Sometimes while I run the program and Alt+Tab to my everyday chrome browser I will get this error message

> Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\calvi\OneDrive\Desktop\bulk-upload-to-opensea\upload18.py", line 344, in main_program_loop
    cross = driver.find_element(By.XPATH, '/html/body/div[6]/div/div/div/div[2]/button/i')
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[6]/div/div/div/div[2]/button/i"}
  (Session info: chrome=98.0.4758.102)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\calvi\OneDrive\Desktop\bulk-upload-to-opensea\upload18.py", line 348, in main_program_loop
    wait_xpath('/html/body/div[5]/div/div/div/div[2]/button/i')
  File "C:\Users\calvi\OneDrive\Desktop\bulk-upload-to-opensea\upload18.py", line 244, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by calvinvalerian** [comment]
I do not minimize the other opensea tab running the python script. I am just Alt+Tab it

**Comment by infotrex** [comment]
@calvinvalerian 
why " Alt+Tab it? 
you should stop any keyboard and mouse motion. 
thx

**Comment by ZacharyAkers** [comment]
@calvinvalerian I use opera gx to do other things while it runs on webdriver and half screen opera over the webdriver. Never get any errors unless clicking when the selling happens

**Comment by GiraffeValley** [comment]
> @calvinvalerian, почему «Alt + Tab это? Вы должны остановить любое движение клавиатуры и мыши. спасибо

I have a problem again) why my script sometimes stops before the listing stage

**Comment by infotrex** [comment]
@GiraffeValley 
if the script can upload few nft without problem and suddenly stops, it might be internet speed or website issue etc.

**Comment by ZacharyAkers** [comment]
> @ZacharyAkers @infotrex I want to see your opensea NFTs I am confused how much should I sell my NFT for

rei-armada

**Comment by GiraffeValley** [comment]
> @GiraffeValley if the script can upload few nft without problem and suddenly stops, it might be internet speed or website issue etc.

okay, to hell with this stop, auto captcha doesn’t work for me😂, what should I do to make it work

**Comment by calvinvalerian** [comment]
@infotrex sometimes even when I leave Chrome browser running overnight with full window size, the program still return error

> Traceback (most recent call last):
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\calvi\OneDrive\Desktop\bulk-upload-to-opensea\upload18.py", line 447, in main_program_loop
    driver.switch_to.window(login_page)
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\switch_to.py", line 112, in window
    self._w3c_window(window_name)
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\switch_to.py", line 134, in _w3c_window
    raise e
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\switch_to.py", line 123, in _w3c_window
    send_handle(window_name)
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\switch_to.py", line 119, in send_handle
    self._driver.execute(Command.SWITCH_TO_WINDOW, {'handle': h})
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window
  (Session info: chrome=98.0.4758.102)

**Comment by GiraffeValley** [comment]
> @infotrex иногда, даже когда я оставляю браузер Chrome работать на ночь с полным размером окна, программа все еще возвращает ошибку
> 
> > Трассировка (последний последний вызов): 
> > файл «C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\tkinter_ _init_ _.py», строка 1921, при **вызове** 
> > return self.func(*args) 
> > File "C:\Users\calvi\OneDrive\Desktop\bulk-upload-to-opensea\upload18.py", строка 447, в файле 
> > main_program_loop driver.switch_to.window(login_page) 
> > "C:\Users\calvi\AppData\Local \Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\switch_to.py", строка 112, в окне 
> > self._w3c_window(window_name) 
> > File "C:\Users\calvi\AppData\Local\Programs\ Python\Python310\lib\site-packages\selenium\webdriver\remote\switch_to.py", строка 134, в _w3c_window 
> > поднять e
> > Файл "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\switch_to.py", строка 123, в _w3c_window 
> > send_handle(window_name) 
> > Файл "C:\ Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\switch_to.py", строка 119, в send_handle 
> > self._driver.execute(Command.SWITCH_TO_WINDOW, {'handle' : h}) 
> > Файл "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", строка 321, при выполнении 
> > self.error_handler.check_response (ответ) 
> > Файл "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", строка 242, в check_response
> > поднять exception_class (сообщение, экран, трассировка стека) 
> > selenium.common.exceptions.NoSuchWindowException: Сообщение: нет такого окна 
> > (информация о сеансе: chrome = 98.0.4758.102)

Are you getting errors with captcha?

**Comment by calvinvalerian** [comment]
> @calvinvalerian I use opera gx to do other things while it runs on webdriver and half screen opera over the webdriver. Never get any errors unless clicking when the selling happens

Turned out the half screening my chrome browser does not interfere the program. Thanks for the idea
