### ISSUE TITLE
Properties are not being added

### ISSUE THREAD

**Issue by kaikecloss** [infotrex/bulk-upload-to-opensea#82]
Hello guys, the upload is working, but it doesn't open the properties part. My json file has the attributes, but it's not going. I will send a print of the file. Can you help me?

![image](https://user-images.githubusercontent.com/95150247/154823500-bbdaa18e-0416-41bd-9396-4e7a0ea45b61.png)

**Comment by kevin96vazquez** [comment]
> Hello guys, the upload is working, but it doesn't open the properties part. My json file has the attributes, but it's not going. I will send a print of the file. Can you help me?
> 
> ![image](https://user-images.githubusercontent.com/95150247/154823500-bbdaa18e-0416-41bd-9396-4e7a0ea45b61.png)
> 

Hi, I solved it by modifying this:

addmore_button = driver.find_element(By.XPATH, '//button[text()="Add more"]') 
                     driver.execute_script("arguments[0].click();", addmore_button) 
                 time.sleep(0.9)
         try: 
              save_button = driver.find_element(By.XPATH, '//button[text()="Save"]') 
              driver.execute_script("arguments[0].click();",  save_button) 
              time.sleep(0.8)  
         except:
              driver.find_element(By.XPATH, '//button[text()="Save"]').click() 
                 time.sleep(0.8)

**Comment by infotrex** [comment]
@kevin96vazquez great

**Comment by kaikecloss** [comment]
> > Hello guys, the upload is working, but it doesn't open the properties part. My json file has the attributes, but it's not going. I will send a print of the file. Can you help me?
> > ![image](https://user-images.githubusercontent.com/95150247/154823500-bbdaa18e-0416-41bd-9396-4e7a0ea45b61.png)
> 
> Hi, I solved it by modifying this:
> 
> addmore_button = driver.find_element(By.XPATH, '//button[text()="Add more"]') driver.execute_script("arguments[0].click();", addmore_button) time.sleep(0.9) try: save_button = driver.find_element(By.XPATH, '//button[text()="Save"]') driver.execute_script("arguments[0].click();", save_button) time.sleep(0.8) except: driver.find_element(By.XPATH, '//button[text()="Save"]').click() time.sleep(0.8)

Thank you for your support!!
But I'm a noob on the subject LOL 
where do I add this code, in the json file? If yes, there are 10K files :(

**Comment by kevin96vazquez** [comment]
> > > Hello guys, the upload is working, but it doesn't open the properties part. My json file has the attributes, but it's not going. I will send a print of the file. Can you help me?
> > > ![image](https://user-images.githubusercontent.com/95150247/154823500-bbdaa18e-0416-41bd-9396-4e7a0ea45b61.png)
> > 
> > Hi, I solved it by modifying this:
> > 
> > addmore_button = driver.find_element(By.XPATH, '//button[text()="Add more"]') driver.execute_script("arguments[0].click();", addmore_button) time.sleep(0.9) try: save_button = driver.find_element(By.XPATH, '//button[text()="Save"]') driver.execute_script("arguments[0].click();", save_button) time.sleep(0.8) except: driver.find_element(By.XPATH, '//button[text()="Save"]').click() time.sleep(0.8)
> 
> Thank you for your support!!
> But I'm a noob on the subject LOL 
> where do I add this code, in the json file? If yes, there are 10K files :(

This code snippet must be pasted into the upload18.py file, specifically from lines 298 to 303.
The file (upload18.py) can be modified from any text editor.

**Comment by kaikecloss** [comment]
Nice, thanks!

I tried to paste the snippet, but show this error now

![image](https://user-images.githubusercontent.com/95150247/154841527-ec203018-7432-4f46-83ff-c05040d61438.png)

**Comment by kevin96vazquez** [comment]
> Nice, thanks!
> 
> I tried to paste the snippet, but show this error now
> 
> ![image](https://user-images.githubusercontent.com/95150247/154841527-ec203018-7432-4f46-83ff-c05040d61438.png)
> 
> 

![Screenshot_20220220-060948_Chrome.jpg](https://user-images.githubusercontent.com/99713243/154841748-3aea8a13-8634-48e8-ab78-c11ae245a573.jpg)

Select the longest red line and press tab once, everything in try: also select and press tab, same with except, select everything inside and press tab.

**Comment by kaikecloss** [comment]
Thank you so much!!!

**Comment by kevin96vazquez** [comment]
> Thank you so much!!!

Something like that

![Screenshot_20220220-064912_Sublime Text.jpg](https://user-images.githubusercontent.com/99713243/154843348-86793261-b82d-4788-b6d9-adc03195855b.jpg)

you're welcome, good luck

**Comment by kishnachauhan** [comment]
I am facing the issue I just try to copy the above code but still no resolution 

**here is the code which I tried** 
![image](https://user-images.githubusercontent.com/7030485/154847753-2c15311c-b70f-4c1f-a9a0-1d6e1bb7c98f.png)

**This is the error message I get**
![image](https://user-images.githubusercontent.com/7030485/154847809-544b8a45-c3ee-4b76-93bc-d880b3fa8e77.png)

and my window stuck at this
![image](https://user-images.githubusercontent.com/7030485/154847834-00696fa3-ec20-42e0-b79f-72f45081f78b.png)

after that my start button again becomes green and nothing happens. please help.

**Comment by kaikecloss** [comment]
I added the snippet, it is running without error, but it is not adding the attributes 

![image](https://user-images.githubusercontent.com/95150247/154855110-26194155-dd9d-4b4d-ac91-d998a0b925b5.png)

**Comment by BirdWord** [comment]
First, thank you for support and all, but i also added the code, any errors, but it is not adding the attributes, just the image, please help!

**Comment by kaikecloss** [comment]
> Hello guys, the upload is working, but it doesn't open the properties part. My json file has the attributes, but it's not going. I will send a print of the file. Can you help me?
> 
> ![image](https://user-images.githubusercontent.com/95150247/154823500-bbdaa18e-0416-41bd-9396-4e7a0ea45b61.png)

Guys, this format: "image": "REPLACE-THIS-WITH-YOUR-URL/0.png" can it interfere with the code working?

**Comment by infotrex** [comment]
@kaikecloss
do you maximize your browser while it running?

**Comment by kaikecloss** [comment]
> @kaikecloss do you maximize your browser while it running?

Yes! 

![image](https://user-images.githubusercontent.com/95150247/154979208-bd60ca01-110f-4d0f-a996-164d49c1d785.png)

There is anything wrong with the code or my file json?

**Comment by BirdWord** [comment]
make sure the files in the scr folder have the extension ".json"

**Comment by Jakeo420** [comment]
I am having the same problem, it will upload and list the image except that it doesn't add any of the attributes. The window opens  to add properties on Opensea, but then closes again without adding anything. 
Any help would be amazing, thankyou for your time and I hope to hear back from you soon!

**Comment by wmahmoood** [comment]
Same issue with properties. Any help would be amazing, thankyou for your time!
