### ISSUE TITLE
Sign-In modal css for opensea has changed! STUCK @ Sign Page!

### ISSUE THREAD

**Issue by BurningDzire** [infotrex/bulk-upload-to-opensea#83]
Thanks for providing this tool.!. Great Job!! I think the Sign In modal css for open sea has changed. It now has a scroll button and the button style is different for Sign. It would be great if you could update Sign In  selector section in [upload18.py]

Can some please help on this!?

(note The issue is when using Ethereum blockchain)

**Comment by infotrex** [comment]
@BurningDzire
Only Ethereum blockchain have this sign issue.

**Comment by 4xMafole** [comment]
We all appreciate the great work you have done. Seems this problem  need your attention boss. Looking forward for your reply.

**Comment by infotrex** [comment]
@BurningDzire @4xMafole 
Pls twitter me your email address, i have a draft script for fix that error.
if you want for test, pls contact me and buy me a coffee :smile: 
TQ

**Comment by SJFAFA** [comment]
I am having the same problem. Can I get an code? woo1004312@gmail.com 
Thank you for your works.
