### ISSUE TITLE
Wyvern Signing - Small Grey Verify Button on MM

### ISSUE THREAD

**Issue by misterkayr** [infotrex/bulk-upload-to-opensea#84]
Every listing now stops and it requires a user to Sign Wyvern, making listings a start stop affair

**Comment by infotrex** [comment]
@misterkayr 
Are you using ETH blockchain for your default collection?
do you mean it stop at last metamask sign screen?

**Comment by madstupid** [comment]
I am also experiencing this issue. Has anyone figured out how to resolve it? We basically need to automate the click of two buttons and we will then be able to loop uploading an nft collection.

![wyvern issue](https://user-images.githubusercontent.com/100121628/155000919-4a4b795f-70d6-4398-a8fd-0db12097cffc.png)
[wyvern issue.txt](https://github.com/infotrex/bulk-upload-to-opensea/files/8111076/wyvern.issue.txt)
[upload18 - Copy.txt](https://github.com/infotrex/bulk-upload-to-opensea/files/8111117/upload18.-.Copy.txt)

**Comment by infotrex** [comment]
@madstupid
Pls twitter me your email address, i have a draft script for fix that error.
if you want for test, pls contact me and buy me a coffee :smile: 
TQ

**Comment by madstupid** [comment]
madstupid at gmail dot com

**Comment by misterkayr** [comment]
> @madstupid Pls twitter me your email address, i have a draft script for fix that error. if you want for test, pls contact me and buy me a coffee 😄 TQ

Is the script working?
Ill buy you a coffee, if it is :)

**Comment by infotrex** [comment]
> madstupid at gmail dot com

@madstupid 
sent to your gmail.
sorry for late reply.

**Comment by infotrex** [comment]
@misterkayr 
give me your email address. pls

**Comment by misterkayr** [comment]
I am real

**Comment by misterkayr** [comment]
> @misterkayr give me your email address. pls

juicedesignteam @ gmail . com

**Comment by skullmfers** [comment]
@infotrex I am also having that problem. Do you have an answer to that question?

**Comment by infotrex** [comment]
> @infotrex I am also having that problem. Do you have an answer to that question?

email address, pls

**Comment by skullmfers** [comment]
@infotrex  inwho123@gmail.com thx

**Comment by skullmfers** [comment]
@infotrex 
I received the email fine. Additional questions sent via email reply!

**Comment by retarge** [comment]
Hi, can i got the code too? mrtemaworld@gmail.com

**Comment by retarge** [comment]
Everything works but if i enable polygon blockchain grey button still is a problem.

**Comment by SJFAFA** [comment]
Can i get the code? woo1004312@gmail.com

**Comment by infotrex** [comment]
@SJFAFA
Sent

**Comment by VladHefner** [comment]
Hi, please code. very Thanks.
wascone1@gmail.com

**Comment by Heeta2316** [comment]
same problem here! HELP ME!
Thx a lot :)
yht2316@gmail.com

**Comment by infotrex** [comment]
@Heeta2316 
Pls download the latest file upload18. that issue was solved.
TQ
