### ISSUE TITLE
Program Not Responding after "Start"

### ISSUE THREAD

**Issue by Chronohumanus** [infotrex/bulk-upload-to-opensea#86]
Now let me start off by saying I'm no tech wiz, I definitely had a little struggle trying to get through the python and pip installation and functionality, but I believe I got there. I say this because I don't know if there was some way I messed up my inputs prior to the actual Upload tab (where the folder is linked and the actual "Start" button is), but after getting everything there situated and ready for creation. Now I want to note that at this time I have the new chrome page opened with my wallet linked and ready to go at the collection screen, and it IS also maximized. However, when I actually press "Start" to engage the software, I see the chrome tab start to load and begin something not visible, and then I get a "(Not Responding)" error message on the "Start" tab. There is a possibility that my internet connection is just sub-par right now but I'd rather look to the guys that are a lot more knowledgeable than I to see if there's something I missed or otherwise screwed up.

**Comment by infotrex** [comment]
@Chronohumanus 
Pls find me at twitter @klvntss
i believe you have something miss out the configuration.

**Comment by Moose2022-maker** [comment]
I am having the same issue, It keep saying "not responding"

**Comment by Chronohumanus** [comment]
@Moose2022-maker I felt incredibly stupid after realizing what my own problem was, so maybe it'll be the same case for you, here's to hoping. When you actually paste the link to your collection on the infotrex tab, you have to type "/assets/create" at the end to actually make the code upload your NFTs. Sorry if that doesn't work, but that was my fix

**Comment by infotrex** [comment]
@Chronohumanus
sorry for any inconvenience.
