### ISSUE TITLE
The image is not inserted into the open sea

### ISSUE THREAD

**Issue by GiraffeValley** [infotrex/bulk-upload-to-opensea#88]
the program inserts into the image something like
"blob:https://opensea.io/b2b251bf-8040-46b9-a892-6449
![Screenshot_10](https://user-images.githubusercontent.com/99540282/155004283-d3551e55-e049-4eae-b8ab-27254995b8f0.png)

**Comment by infotrex** [comment]
@GiraffeValley 
possible you select incorrect "src" folder or invalid file name. thx

**Comment by GiraffeValley** [comment]
> @GiraffeValley possible you select incorrect "src" folder or invalid file name. thx

https://user-images.githubusercontent.com/99540282/155072317-45a37d7e-7682-42da-88df-680c2fc0e014.mp4
