### ISSUE TITLE
I keep getting " not responding" after start

### ISSUE THREAD

**Issue by Moose2022-maker** [infotrex/bulk-upload-to-opensea#91]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\mosta\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "<string>", line 314, in main_program_loop
  File "<string>", line 227, in wait_xpath
  File "C:\Users\mosta\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x00EA7AC3+2587331]
        Ordinal0 [0x00E3ADD1+2141649]
        Ordinal0 [0x00D33BB8+1063864]
        Ordinal0 [0x00D601CE+1245646]
        Ordinal0 [0x00D603CB+1246155]
        Ordinal0 [0x00D8A612+1418770]
        Ordinal0 [0x00D786D4+1345236]
        Ordinal0 [0x00D88A0A+1411594]
        Ordinal0 [0x00D784A6+1344678]
        Ordinal0 [0x00D553F6+1201142]
        Ordinal0 [0x00D562E6+1204966]
        GetHandleVerifier [0x0104DF22+1680738]
        GetHandleVerifier [0x01100DBC+2413564]
        GetHandleVerifier [0x00F3D151+563089]
        GetHandleVerifier [0x00F3BF13+558419]
        Ordinal0 [0x00E4081E+2164766]
        Ordinal0 [0x00E45508+2184456]
        Ordinal0 [0x00E45650+2184784]
        Ordinal0 [0x00E4F5BC+2225596]
        BaseThreadInitThunk [0x756C6739+25]
        RtlGetFullPathName_UEx [0x77978E7F+1215]
        RtlGetFullPathName_UEx [0x77978E4D+1165]

**Comment by Moose2022-maker** [comment]
also it worked a little yesterday but without adding properties

**Comment by infotrex** [comment]
@Moose2022-maker 
stop at which section?

**Comment by Moose2022-maker** [comment]
first section , it doesn't add the name or the description only the picture

**Comment by Moose2022-maker** [comment]
I made a test with only 9 nfts and i had to click on open chrome and then start and it worked, It uploaded the 9 nfts while saying" not responding" but it never uploaded the properties! I verified my jason file and it is verified, Can you help me?

**Comment by infotrex** [comment]
@Moose2022-maker 
problem resolved -> wrong folder name.
