### ISSUE TITLE
properties not being added

### ISSUE THREAD

**Issue by Moose2022-maker** [infotrex/bulk-upload-to-opensea#92]
Can someone help with this? I verified my jason files but it just skips through the properties and create the listing without properties!

I appreciate all your help!!

**Comment by Moose2022-maker** [comment]
{
  "dna": "d45fcf3a10dbfb58552e989d9d36facf",
  "name": "Masked Morries #1",
  "description": null,
  "image": "REPLACE-THIS-WITH-YOUR-URL/1.png",
  "date": 1645479183923,
  "attributes": [
    {
      "trait_type": "BACKGROUND",
      "value": "PINK"
    },
    {
      "trait_type": "BODY",
      "value": "BODY CHERRY PINK"
    },
    {
      "trait_type": "OUTFIT",
      "value": "BLUE COLLAR PINK SHIRT"
    },
    {
      "trait_type": "HEAD",
      "value": "PINK TOP"
    },
    {
      "trait_type": "MASK",
      "value": "BRIGH PINK MASK"
    },
    {
      "trait_type": "EYES",
      "value": "SHOCK EYES"
    },
    {
      "trait_type": "HAT",
      "value": "HAVANA HAT"
    }
  ],
  "compiler": "mintables.club"
}

**Comment by Moose2022-maker** [comment]
![Screenshot 2022-02-22 092005](https://user-images.githubusercontent.com/100208383/155151036-12018555-0ee7-4059-9f75-497128f19f76.png)

**Comment by Moose2022-maker** [comment]
Thank you for your help!

**Comment by Moose2022-maker** [comment]
no

**Comment by ZacharyAkers** [comment]
Hmm ok can you open dev tools on create nft and select properties button? And send a picture of result as well as right clicking the element that pops up for button and select copy full xpath?

**Comment by ZacharyAkers** [comment]
If you don't know I put a step by step process on how to work dev tools in #60

**Comment by Moose2022-maker** [comment]
![Screenshot 2022-02-22 093921](https://user-images.githubusercontent.com/100208383/155155086-55dd0561-ad29-4635-9d60-0e6c3fea9152.png)

**Comment by Moose2022-maker** [comment]
Is this right?

**Comment by Moose2022-maker** [comment]
![Uploading Screenshot 2022-02-22 100600.png…]()

**Comment by Moose2022-maker** [comment]
Is this the one?

**Comment by Moose2022-maker** [comment]
![Screenshot 2022-02-22 100600](https://user-images.githubusercontent.com/100208383/155160610-a80b277f-c6c4-481e-9360-29df001e1ea9.png)

**Comment by Moose2022-maker** [comment]
![Screenshot 2022-02-22 100942](https://user-images.githubusercontent.com/100208383/155161115-2f5439e1-c9c8-44ae-960e-f826168de0f4.png)

**Comment by Moose2022-maker** [comment]
was this the right information?

**Comment by Moose2022-maker** [comment]
is there a solution to this?

**Comment by infotrex** [comment]
@Moose2022-maker
contact me via twitter. thx

**Comment by Moose2022-maker** [comment]
What is your Twitter name?
