### ISSUE TITLE
NFT is not registered. Continue to re-login OPENSEE

### ISSUE THREAD

**Issue by barraginim** [infotrex/bulk-upload-to-opensea#93]
After running upload18.py, the first 1.pngnft file is uploaded to the collection and metadata is automatically entered. In the automatic process of registering this, it is told to reconnect OPENSEA. So it's not registered. Is there a solution?

**Comment by infotrex** [comment]
@barraginim 
might be opensea website issue.
try run again the process. 
thank you.

**Comment by barraginim** [comment]
I solved the problem. It works well, but there is a final problem. The publication period is set to 7 days only. Even if you choose 30, 60, 90, 120, and 180 days, it will be uploaded only as 7 days. How can I solve this problem?
Also, the automatic robot confirmation window comes out every 10 registrations, is there a way to solve it? If you can solve two problems, I will provide you with delicious coffee.

**Comment by infotrex** [comment]
@barraginim 
1) for date duration you need to install "pip install python-dateutil", and set your windows date format to mm/dd/yyyy or mm.dd.yyyy. 
2) "robot" i cannot bypass.

**Comment by infotrex** [comment]
@barraginim 
can let me know how the delicious coffee. :)

**Comment by barraginim** [comment]
The problem hasn't been solved yet. I'll give you coffee when the problem is solved. :)

**Comment by infotrex** [comment]
@barraginim 
robot i cannot solve at the moment.
still seeking solution...:(

**Comment by infotrex** [comment]
@barraginim
give me your email address, will send you the bypass Captcha draft script for testing.
i will be glad if you want to support this project.
