### ISSUE TITLE
Exception in Tkinter callback ?

### ISSUE THREAD

**Issue by zhu021** [infotrex/bulk-upload-to-opensea#94]
I keep getting these regularly

Start creating NFT #7040
number  7040
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Emdad\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Emdad\bulk-upload-to-opensea-main\upload18.py", line 258, in main_program_loop  
    wait_xpath('//*[@id="media"]')
  File "C:\Users\Emdad\bulk-upload-to-opensea-main\upload18.py", line 244, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Users\Emdad\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x002F7AC3+2587331]
        Ordinal0 [0x0028ADD1+2141649]
        Ordinal0 [0x00183BB8+1063864]
        Ordinal0 [0x001B01CE+1245646]
        Ordinal0 [0x001B03CB+1246155]
        Ordinal0 [0x001DA612+1418770]
        Ordinal0 [0x001C86D4+1345236]
        Ordinal0 [0x001D8A0A+1411594]
        Ordinal0 [0x001C84A6+1344678]
        Ordinal0 [0x001A53F6+1201142]
        Ordinal0 [0x001A62E6+1204966]
        GetHandleVerifier [0x0049DF22+1680738]
        GetHandleVerifier [0x00550DBC+2413564]
        GetHandleVerifier [0x0038D151+563089]
        GetHandleVerifier [0x0038BF13+558419]
        Ordinal0 [0x0029081E+2164766]
        Ordinal0 [0x00295508+2184456]
        Ordinal0 [0x00295650+2184784]
        Ordinal0 [0x0029F5BC+2225596]
        BaseThreadInitThunk [0x74EFF989+25]
        RtlGetAppContainerNamedObjectPath [0x76EF74B4+228]
        RtlGetAppContainerNamedObjectPath [0x76EF7484+180]
        (No symbol) [0x00000000]

------------------------------------------------------------------------------------------------
Start creating NFT #4860
number  4860
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Emdad\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__, in __call__
    return self.func(*args)
  File "C:\Users\Emdad\bulk-upload-to-opensea-main\upload18.py", line 347, in main_program_loop  
    wait_xpath('//a[text()="Sell"]')
  File "C:\Users\Emdad\bulk-upload-to-opensea-main\upload18.py", line 244, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))                 r\support\wait.py", line 89, in until
  File "C:\Users\Emdad\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x00577AC3+2587331]
        Ordinal0 [0x0050ADD1+2141649]
        Ordinal0 [0x00403BB8+1063864]
        Ordinal0 [0x004301CE+1245646]
        Ordinal0 [0x004303CB+1246155]
        Ordinal0 [0x0045A612+1418770]
        Ordinal0 [0x004486D4+1345236]
        Ordinal0 [0x00458A0A+1411594]
        Ordinal0 [0x004484A6+1344678]
        Ordinal0 [0x004253F6+1201142]
        Ordinal0 [0x004262E6+1204966]
        GetHandleVerifier [0x0071DF22+1680738]
        GetHandleVerifier [0x007D0DBC+2413564]
        GetHandleVerifier [0x0060D151+563089]
        GetHandleVerifier [0x0060BF13+558419]
        Ordinal0 [0x0051081E+2164766]
        Ordinal0 [0x00515508+2184456]
        Ordinal0 [0x00515650+2184784]
        Ordinal0 [0x0051F5BC+2225596]
        BaseThreadInitThunk [0x75E4F989+25]
        RtlGetAppContainerNamedObjectPath [0x772274B4+228]
        RtlGetAppContainerNamedObjectPath [0x77227484+180]

**Comment by infotrex** [comment]
@zhu021 
**number 7040** 
- might be not select correct "SRC" folder or invalid image file name
**number 4860**
- might be not maximize your browser or zoom size.

**Comment by nftje** [comment]
It happend to me as well. I was able to fix by listening to the instruction carefully. So the solution was just type the correct OpenSea Collection link in the program. basically the complete link has to be: Opensea collection link: https://opensea.io/collection/kick-skull/assets/create. the missing last part of the link was creating the problem.
