### ISSUE TITLE
unlockable content

### ISSUE THREAD

**Issue by bandithilmi** [infotrex/bulk-upload-to-opensea#95]
Is there a way to upload also unlockable content?

**Comment by infotrex** [comment]
@hilmi005 
you can modify the script.
or i modify for you and have some charge. :)

**Comment by misterkayr** [comment]
> @hilmi005 you can modify the script. or i modify for you and have some charge. :)

I dont have much money, but I would like to be able to have unlockable content if the price is not to high

**Comment by misterkayr** [comment]
> @misterkayr
> 
> I have modified the script.

Is it modified on the "testing" recaptcha solving script or the current script?
Can I have a look?
